/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gezondheid van de server en de database */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inloggen met wachtwoord en, indien ingesteld, TOTP-code */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Uitloggen */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** De ingelogde gebruiker en de CSRF-token van de sessie */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wachtwoord wijzigen; andere sessies worden beëindigd */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/totp/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Nieuw TOTP-geheim aanmaken (nog niet actief) */
        post: operations["beginTotpSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/totp/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** TOTP activeren met een code uit de authenticator-app */
        post: operations["enableTotp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/totp/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** TOTP uitzetten met wachtwoord en een geldige code */
        post: operations["disableTotp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recente events, nieuwste eerst (alleen admin) */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Actieve gebruikers, voor bijvoorbeeld de keuze van owners */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alle clusters met aantallen nodes en VIP's */
        get: operations["listClusters"];
        put?: never;
        /** Cluster aanmaken (admin) */
        post: operations["createCluster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        /** Cluster met nodes, VIP's en owners */
        get: operations["getCluster"];
        put?: never;
        post?: never;
        /** Cluster verwijderen (admin); nodes blijven bestaan zonder cluster, VIP's verdwijnen */
        delete: operations["deleteCluster"];
        options?: never;
        head?: never;
        /** Cluster wijzigen (admin); alleen meegestuurde velden veranderen */
        patch: operations["updateCluster"];
        trace?: never;
    };
    "/clusters/{clusterId}/vips": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** VIP toevoegen aan een cluster (admin) */
        post: operations["createVip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vips/{vipId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vipId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** VIP verwijderen (admin) */
        delete: operations["deleteVip"];
        options?: never;
        head?: never;
        /** VIP wijzigen (admin) */
        patch: operations["updateVip"];
        trace?: never;
    };
    "/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alle nodes, met hun cluster */
        get: operations["listNodes"];
        put?: never;
        /** Node aanmaken (admin) */
        post: operations["createNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        /** Eén node */
        get: operations["getNode"];
        put?: never;
        post?: never;
        /** Node verwijderen (admin) */
        delete: operations["deleteNode"];
        options?: never;
        head?: never;
        /** Node wijzigen (admin); cluster_id null haalt de node uit zijn cluster */
        patch: operations["updateNode"];
        trace?: never;
    };
    "/nodes/{nodeId}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        /** Facts en laatste heartbeat van de agent op deze node */
        get: operations["getNodeFacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{nodeId}/metrics": {
        parameters: {
            query?: {
                range?: components["schemas"]["MetricsRange"];
            };
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        /** Grafieken van één node uit VictoriaMetrics */
        get: operations["getNodeMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterId}/metrics": {
        parameters: {
            query?: {
                range?: components["schemas"]["MetricsRange"];
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        /** Grafieken van een cluster, met een lijn per node */
        get: operations["getClusterMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live wijzigingen als Server-Sent Events
         * @description Een event `change` per nieuw event in de eventlog, met als data een
         *     JSON-object met id, action, subject_type, subject_id en cluster_id.
         *     De stream sluit na enkele minuten; de browser verbindt dan opnieuw.
         */
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instellingen van de server die de webinterface nodig heeft */
        get: operations["getInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrollment-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bruikbare enrollmenttokens (admin) */
        get: operations["listEnrollmentTokens"];
        put?: never;
        /** Enrollmenttoken aanmaken (admin); het token zelf staat alleen in dit antwoord */
        post: operations["createEnrollmentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrollment-tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Enrollmenttoken intrekken (admin) */
        delete: operations["deleteEnrollmentToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Een agent meldt zich aan met een enrollmenttoken (zonder sessie) */
        post: operations["enrollAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agentId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agent intrekken (admin); de verbinding wordt meteen verbroken */
        post: operations["revokeAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Stabiele foutcode, bijvoorbeeld invalid_credentials of totp_required */
            code: string;
            message: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            version: string;
            /** @enum {string} */
            database: "ok" | "unreachable";
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
            /** @description Zescijferige code */
            totp_code?: string;
        };
        /** @enum {string} */
        Role: "admin" | "viewer";
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            role: components["schemas"]["Role"];
            totp_enabled: boolean;
            /** Format: date-time */
            created_at: string;
        };
        Me: {
            user: components["schemas"]["User"];
            csrf_token: string;
            /** Format: date-time */
            session_expires_at: string;
        };
        ChangePasswordRequest: {
            /** Format: password */
            current_password: string;
            /** Format: password */
            new_password: string;
        };
        TotpSetup: {
            secret: string;
            otpauth_url: string;
        };
        TotpCodeRequest: {
            code: string;
        };
        TotpDisableRequest: {
            /** Format: password */
            password: string;
            code: string;
        };
        Event: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            ts: string;
            /** @enum {string} */
            actor_type: "user" | "agent" | "system";
            actor_id: string;
            subject_type: string;
            subject_id: string;
            /** Format: uuid */
            cluster_id?: string | null;
            action: string;
            payload: {
                [key: string]: unknown;
            };
        };
        UserRef: {
            /** Format: uuid */
            id: string;
            username: string;
        };
        /** @enum {string} */
        ClusterType: "keepalived" | "nginx" | "docker" | "cron" | "postgresql_ha" | "mariadb_ha" | "generic";
        /** @enum {string} */
        Environment: "lab" | "test" | "prod";
        /** @enum {string} */
        NodeLifecycle: "provisioning" | "active" | "maintenance" | "draining" | "decommissioned";
        /**
         * @description Berekend uit heartbeats, metrics en VIP's (zie internal/status).
         *     unknown betekent: geen agent of nog geen gegevens.
         * @enum {string}
         */
        Status: "unknown" | "healthy" | "degraded" | "down" | "split_brain";
        Cluster: {
            /** Format: uuid */
            id: string;
            /** @description Korte unieke naam, bijvoorbeeld webcluster-prod */
            slug: string;
            name: string;
            description: string;
            type: components["schemas"]["ClusterType"];
            environment: components["schemas"]["Environment"];
            status: components["schemas"]["Status"];
            /** @description Waarom de status niet healthy is */
            status_reason: string;
            /** Format: date-time */
            status_since: string | null;
            tags: string[];
            git_repo_url: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ClusterListItem: components["schemas"]["Cluster"] & {
            node_count: number;
            vip_count: number;
        };
        ClusterDetail: components["schemas"]["Cluster"] & {
            owners: components["schemas"]["UserRef"][];
            nodes: components["schemas"]["Node"][];
            vips: components["schemas"]["Vip"][];
        };
        ClusterInput: {
            slug: string;
            name: string;
            description?: string;
            type: components["schemas"]["ClusterType"];
            environment: components["schemas"]["Environment"];
            git_repo_url?: string;
            tags?: string[];
            owner_ids?: string[];
        };
        ClusterPatch: {
            slug?: string;
            name?: string;
            description?: string;
            type?: components["schemas"]["ClusterType"];
            environment?: components["schemas"]["Environment"];
            git_repo_url?: string;
            tags?: string[];
            owner_ids?: string[];
        };
        Node: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["Status"];
            /** @description Waarom de status niet healthy is */
            status_reason: string;
            /** Format: date-time */
            status_since: string | null;
            /** @description De actieve agent, of null als er (nog) geen agent is */
            agent: components["schemas"]["AgentSummary"] | null;
            /** Format: uuid */
            cluster_id: string | null;
            cluster_slug: string | null;
            cluster_name: string | null;
            hostname: string;
            role: string;
            description: string;
            lifecycle: components["schemas"]["NodeLifecycle"];
            primary_ip: string | null;
            tags: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        NodeInput: {
            hostname: string;
            /** Format: uuid */
            cluster_id?: string | null;
            role?: string;
            description?: string;
            lifecycle?: components["schemas"]["NodeLifecycle"];
            primary_ip?: string | null;
            tags?: string[];
        };
        NodePatch: {
            hostname?: string;
            /** Format: uuid */
            cluster_id?: string | null;
            role?: string;
            description?: string;
            lifecycle?: components["schemas"]["NodeLifecycle"];
            primary_ip?: string | null;
            tags?: string[];
        };
        Vip: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            cluster_id: string;
            address: string;
            interface: string;
            vrid: number | null;
            description: string;
            /** Format: uuid */
            owner_node_id: string | null;
            owner_hostname: string | null;
            /** Format: date-time */
            owner_since: string | null;
        };
        VipInput: {
            address: string;
            interface?: string;
            vrid?: number | null;
            description?: string;
        };
        VipPatch: {
            address?: string;
            interface?: string;
            vrid?: number | null;
            description?: string;
        };
        /**
         * @description online bij een heartbeat in de laatste 30 s, late tot 90 s, daarna offline
         * @enum {string}
         */
        AgentConnection: "online" | "late" | "offline";
        AgentSummary: {
            /** Format: uuid */
            id: string;
            version: string;
            /** Format: date-time */
            enrolled_at: string;
            /** Format: date-time */
            last_seen_at: string | null;
            connection: components["schemas"]["AgentConnection"];
        };
        NodeRuntime: {
            facts: components["schemas"]["Facts"] | null;
            /** Format: date-time */
            collected_at: string | null;
            /** Format: date-time */
            changed_at: string | null;
            heartbeat: components["schemas"]["HeartbeatStatus"] | null;
        };
        HeartbeatStatus: {
            /** Format: date-time */
            received_at: string;
            /** Format: int64 */
            uptime_seconds: number;
            load: number[];
            addresses: string[];
            services: {
                [key: string]: string;
            };
        };
        /** @description Zoals de agent ze verzamelt; zie pkg/protocol */
        Facts: {
            hostname: string;
            machine_id: string;
            os: {
                id: string;
                version_id: string;
                codename: string;
                pretty_name: string;
            };
            kernel: string;
            arch: string;
            virtualization: string;
            cpus: number;
            /** Format: int64 */
            memory_bytes: number;
            /** Format: int64 */
            swap_bytes: number;
            /** Format: date-time */
            boot_time: string;
            primary_address: string;
            interfaces: {
                name: string;
                mac: string;
                up: boolean;
                addresses: string[] | null;
            }[] | null;
            filesystems: {
                mount: string;
                device: string;
                type: string;
                /** Format: int64 */
                size_bytes: number;
                /** Format: int64 */
                used_bytes: number;
            }[] | null;
            services: {
                name: string;
                active: string;
                enabled: string;
            }[] | null;
            docker: {
                version: string;
                containers: number;
            } | null;
            keepalived: {
                active: string;
                vips: string[] | null;
            } | null;
            upgrades: {
                total: number;
                security: number;
                packages: string[] | null;
            } | null;
        };
        EnrollmentToken: {
            /** Format: uuid */
            id: string;
            description: string;
            /** Format: uuid */
            node_id: string | null;
            node_hostname: string | null;
            /** Format: uuid */
            cluster_id: string | null;
            cluster_name: string | null;
            max_uses: number;
            uses: number;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            created_at: string;
            /** @description Gebruikersnaam */
            created_by: string | null;
        };
        EnrollmentTokenInput: {
            description?: string;
            /**
             * Format: uuid
             * @description Alleen deze bestaande node mag zich ermee aanmelden
             */
            node_id?: string | null;
            /**
             * Format: uuid
             * @description Nieuwe nodes komen in dit cluster
             */
            cluster_id?: string | null;
            /** @description Standaard 1 */
            max_uses?: number;
            /** @description Standaard 24 */
            ttl_hours?: number;
        };
        NewEnrollmentToken: components["schemas"]["EnrollmentToken"] & {
            /** @description Alleen nu zichtbaar */
            token: string;
        };
        EnrollRequest: {
            token: string;
            nkey_public: string;
            hostname: string;
            machine_id: string;
            agent_version: string;
            protocol_version: number;
        };
        EnrollResponse: {
            /** Format: uuid */
            agent_id: string;
            /** Format: uuid */
            node_id: string;
            /** @description Bijvoorbeeld tls://clusterforge.lan:4222 */
            nats_url: string;
            /** @description Hex-sha256 van het NATS-certificaat; de agent pint het */
            nats_cert_sha256: string;
        };
        /**
         * @default 1h
         * @enum {string}
         */
        MetricsRange: "1h" | "6h" | "24h" | "7d";
        Metrics: {
            range: components["schemas"]["MetricsRange"];
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            step_seconds: number;
            /** @description Unix-tijden in seconden; de waarden van elke lijn horen hierbij */
            timestamps: number[];
            panels: components["schemas"]["MetricPanel"][];
        };
        MetricPanel: {
            id: string;
            title: string;
            /** @enum {string} */
            unit: "percent" | "load" | "bytes_per_second" | "celsius";
            series: components["schemas"]["MetricSeries"][];
        };
        MetricSeries: {
            label: string;
            /** @description Eén waarde per tijdstip in timestamps; null als er geen meting is */
            values: (number | null)[];
        };
        ServerInfo: {
            version: string;
            /** @description Of er een VictoriaMetrics is ingesteld */
            metrics_enabled: boolean;
            /** @description Link naar Grafana voor een node, met {hostname}, {node_id}, {cluster}, {cluster_id} en {env}; leeg als niet ingesteld */
            grafana_node_url: string;
            /** @description Link naar Grafana voor een cluster, met {cluster}, {cluster_id} en {env}; leeg als niet ingesteld */
            grafana_cluster_url: string;
        };
    };
    responses: {
        /** @description Fout */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Database niet bereikbaar */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Ingelogd; de sessiecookie staat in Set-Cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Uitgelogd */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Gewijzigd */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    beginTotpSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Geheim en otpauth-URL voor de authenticator-app */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpSetup"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    enableTotp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpCodeRequest"];
            };
        };
        responses: {
            /** @description Geactiveerd */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    disableTotp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpDisableRequest"];
            };
        };
        responses: {
            /** @description Uitgezet */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Event"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["UserRef"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listClusters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ClusterListItem"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createCluster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusterInput"];
            };
        };
        responses: {
            /** @description Aangemaakt */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterDetail"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterDetail"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verwijderd */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updateCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusterPatch"];
            };
        };
        responses: {
            /** @description Gewijzigd */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterDetail"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    createVip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VipInput"];
            };
        };
        responses: {
            /** @description Aangemaakt */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vip"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    deleteVip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vipId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verwijderd */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updateVip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vipId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VipPatch"];
            };
        };
        responses: {
            /** @description Gewijzigd */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vip"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Node"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createNode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeInput"];
            };
        };
        responses: {
            /** @description Aangemaakt */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verwijderd */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updateNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodePatch"];
            };
        };
        responses: {
            /** @description Gewijzigd */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getNodeFacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeRuntime"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getNodeMetrics: {
        parameters: {
            query?: {
                range?: components["schemas"]["MetricsRange"];
            };
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            502: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getClusterMetrics: {
        parameters: {
            query?: {
                range?: components["schemas"]["MetricsRange"];
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            502: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerInfo"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listEnrollmentTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["EnrollmentToken"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    createEnrollmentToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentTokenInput"];
            };
        };
        responses: {
            /** @description Aangemaakt */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewEnrollmentToken"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    deleteEnrollmentToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verwijderd */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    enrollAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollRequest"];
            };
        };
        responses: {
            /** @description Aangemeld */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    revokeAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingetrokken */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
}
