// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agents.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, node_id, nkey_public, machine_id, version, protocol_version)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, node_id, nkey_public, machine_id, version, protocol_version, enrolled_at, last_seen_at, revoked_at
`

type CreateAgentParams struct {
	ID              uuid.UUID
	NodeID          uuid.UUID
	NkeyPublic      string
	MachineID       string
	Version         string
	ProtocolVersion int32
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.ID,
		arg.NodeID,
		arg.NkeyPublic,
		arg.MachineID,
		arg.Version,
		arg.ProtocolVersion,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.NkeyPublic,
		&i.MachineID,
		&i.Version,
		&i.ProtocolVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const createEnrollmentToken = `-- name: CreateEnrollmentToken :one
INSERT INTO enrollment_tokens (token_hash, description, node_id, cluster_id, max_uses, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, token_hash, description, node_id, cluster_id, max_uses, uses, expires_at, created_by, created_at
`

type CreateEnrollmentTokenParams struct {
	TokenHash   []byte
	Description string
	NodeID      *uuid.UUID
	ClusterID   *uuid.UUID
	MaxUses     int32
	ExpiresAt   time.Time
	CreatedBy   *uuid.UUID
}

func (q *Queries) CreateEnrollmentToken(ctx context.Context, arg CreateEnrollmentTokenParams) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, createEnrollmentToken,
		arg.TokenHash,
		arg.Description,
		arg.NodeID,
		arg.ClusterID,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Description,
		&i.NodeID,
		&i.ClusterID,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEnrollmentToken = `-- name: DeleteEnrollmentToken :execrows
DELETE FROM enrollment_tokens WHERE id = $1
`

func (q *Queries) DeleteEnrollmentToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEnrollmentToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findNodeByHostname = `-- name: FindNodeByHostname :one
SELECT id, cluster_id, hostname, role, description, lifecycle, primary_ip, tags, created_at, updated_at, status, status_reason, status_since, proxmox_id, pve_vmid FROM nodes WHERE lower(hostname) = lower($1::text) FOR UPDATE
`

func (q *Queries) FindNodeByHostname(ctx context.Context, hostname string) (Node, error) {
	row := q.db.QueryRow(ctx, findNodeByHostname, hostname)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Hostname,
		&i.Role,
		&i.Description,
		&i.Lifecycle,
		&i.PrimaryIp,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.StatusSince,
		&i.ProxmoxID,
		&i.PveVmid,
	)
	return i, err
}

const getActiveAgentByNkey = `-- name: GetActiveAgentByNkey :one
SELECT id, node_id, nkey_public, machine_id, version, protocol_version, enrolled_at, last_seen_at, revoked_at FROM agents WHERE nkey_public = $1 AND revoked_at IS NULL
`

func (q *Queries) GetActiveAgentByNkey(ctx context.Context, nkeyPublic string) (Agent, error) {
	row := q.db.QueryRow(ctx, getActiveAgentByNkey, nkeyPublic)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.NkeyPublic,
		&i.MachineID,
		&i.Version,
		&i.ProtocolVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveAgentByNode = `-- name: GetActiveAgentByNode :one
SELECT id, node_id, nkey_public, machine_id, version, protocol_version, enrolled_at, last_seen_at, revoked_at FROM agents WHERE node_id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetActiveAgentByNode(ctx context.Context, nodeID uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getActiveAgentByNode, nodeID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.NkeyPublic,
		&i.MachineID,
		&i.Version,
		&i.ProtocolVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAgent = `-- name: GetAgent :one
SELECT id, node_id, nkey_public, machine_id, version, protocol_version, enrolled_at, last_seen_at, revoked_at FROM agents WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.NkeyPublic,
		&i.MachineID,
		&i.Version,
		&i.ProtocolVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getNodeFacts = `-- name: GetNodeFacts :one
SELECT node_id, hash, facts, collected_at, changed_at FROM node_facts WHERE node_id = $1
`

func (q *Queries) GetNodeFacts(ctx context.Context, nodeID uuid.UUID) (NodeFact, error) {
	row := q.db.QueryRow(ctx, getNodeFacts, nodeID)
	var i NodeFact
	err := row.Scan(
		&i.NodeID,
		&i.Hash,
		&i.Facts,
		&i.CollectedAt,
		&i.ChangedAt,
	)
	return i, err
}

const getNodeStatus = `-- name: GetNodeStatus :one
SELECT node_id, heartbeat_at, uptime_seconds, load1, load5, load15, addresses, services, disk_used_ratio, disk_used_mount FROM node_status WHERE node_id = $1
`

func (q *Queries) GetNodeStatus(ctx context.Context, nodeID uuid.UUID) (NodeStatus, error) {
	row := q.db.QueryRow(ctx, getNodeStatus, nodeID)
	var i NodeStatus
	err := row.Scan(
		&i.NodeID,
		&i.HeartbeatAt,
		&i.UptimeSeconds,
		&i.Load1,
		&i.Load5,
		&i.Load15,
		&i.Addresses,
		&i.Services,
		&i.DiskUsedRatio,
		&i.DiskUsedMount,
	)
	return i, err
}

const getServerSecret = `-- name: GetServerSecret :one
SELECT value FROM server_secrets WHERE name = $1
`

func (q *Queries) GetServerSecret(ctx context.Context, name string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getServerSecret, name)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const insertServerSecret = `-- name: InsertServerSecret :exec
INSERT INTO server_secrets (name, value) VALUES ($1, $2) ON CONFLICT (name) DO NOTHING
`

type InsertServerSecretParams struct {
	Name  string
	Value []byte
}

func (q *Queries) InsertServerSecret(ctx context.Context, arg InsertServerSecretParams) error {
	_, err := q.db.Exec(ctx, insertServerSecret, arg.Name, arg.Value)
	return err
}

const listActiveEnrollmentTokens = `-- name: ListActiveEnrollmentTokens :many
SELECT t.id, t.token_hash, t.description, t.node_id, t.cluster_id, t.max_uses, t.uses, t.expires_at, t.created_by, t.created_at, n.hostname AS node_hostname, c.name AS cluster_name, u.username AS created_by_username
FROM enrollment_tokens t
LEFT JOIN nodes n ON n.id = t.node_id
LEFT JOIN clusters c ON c.id = t.cluster_id
LEFT JOIN users u ON u.id = t.created_by
WHERE t.expires_at > now() AND t.uses < t.max_uses
ORDER BY t.created_at DESC
`

type ListActiveEnrollmentTokensRow struct {
	ID                uuid.UUID
	TokenHash         []byte
	Description       string
	NodeID            *uuid.UUID
	ClusterID         *uuid.UUID
	MaxUses           int32
	Uses              int32
	ExpiresAt         time.Time
	CreatedBy         *uuid.UUID
	CreatedAt         time.Time
	NodeHostname      *string
	ClusterName       *string
	CreatedByUsername *string
}

func (q *Queries) ListActiveEnrollmentTokens(ctx context.Context) ([]ListActiveEnrollmentTokensRow, error) {
	rows, err := q.db.Query(ctx, listActiveEnrollmentTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveEnrollmentTokensRow{}
	for rows.Next() {
		var i ListActiveEnrollmentTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.Description,
			&i.NodeID,
			&i.ClusterID,
			&i.MaxUses,
			&i.Uses,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.NodeHostname,
			&i.ClusterName,
			&i.CreatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEnrollmentTokenByHash = `-- name: LockEnrollmentTokenByHash :one
SELECT id, token_hash, description, node_id, cluster_id, max_uses, uses, expires_at, created_by, created_at FROM enrollment_tokens WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) LockEnrollmentTokenByHash(ctx context.Context, tokenHash []byte) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, lockEnrollmentTokenByHash, tokenHash)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Description,
		&i.NodeID,
		&i.ClusterID,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const lockNodeFacts = `-- name: LockNodeFacts :one
SELECT node_id, hash, facts, collected_at, changed_at FROM node_facts WHERE node_id = $1 FOR UPDATE
`

func (q *Queries) LockNodeFacts(ctx context.Context, nodeID uuid.UUID) (NodeFact, error) {
	row := q.db.QueryRow(ctx, lockNodeFacts, nodeID)
	var i NodeFact
	err := row.Scan(
		&i.NodeID,
		&i.Hash,
		&i.Facts,
		&i.CollectedAt,
		&i.ChangedAt,
	)
	return i, err
}

const revokeAgent = `-- name: RevokeAgent :one
UPDATE agents SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, node_id, nkey_public, machine_id, version, protocol_version, enrolled_at, last_seen_at, revoked_at
`

func (q *Queries) RevokeAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, revokeAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.NkeyPublic,
		&i.MachineID,
		&i.Version,
		&i.ProtocolVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAgentsOfNode = `-- name: RevokeAgentsOfNode :many
UPDATE agents SET revoked_at = now()
WHERE node_id = $1 AND revoked_at IS NULL
RETURNING id, node_id, nkey_public, machine_id, version, protocol_version, enrolled_at, last_seen_at, revoked_at
`

func (q *Queries) RevokeAgentsOfNode(ctx context.Context, nodeID uuid.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, revokeAgentsOfNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.NkeyPublic,
			&i.MachineID,
			&i.Version,
			&i.ProtocolVersion,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNodePrimaryIPIfEmpty = `-- name: SetNodePrimaryIPIfEmpty :exec
UPDATE nodes SET primary_ip = $2, updated_at = now() WHERE id = $1 AND primary_ip IS NULL
`

type SetNodePrimaryIPIfEmptyParams struct {
	ID        uuid.UUID
	PrimaryIp *netip.Addr
}

func (q *Queries) SetNodePrimaryIPIfEmpty(ctx context.Context, arg SetNodePrimaryIPIfEmptyParams) error {
	_, err := q.db.Exec(ctx, setNodePrimaryIPIfEmpty, arg.ID, arg.PrimaryIp)
	return err
}

const setVIPOwner = `-- name: SetVIPOwner :exec
UPDATE vips SET owner_node_id = $2, owner_since = now() WHERE id = $1
`

type SetVIPOwnerParams struct {
	ID          uuid.UUID
	OwnerNodeID *uuid.UUID
}

func (q *Queries) SetVIPOwner(ctx context.Context, arg SetVIPOwnerParams) error {
	_, err := q.db.Exec(ctx, setVIPOwner, arg.ID, arg.OwnerNodeID)
	return err
}

const touchAgent = `-- name: TouchAgent :exec
UPDATE agents SET last_seen_at = now(), version = $2, protocol_version = $3
WHERE node_id = $1 AND revoked_at IS NULL
`

type TouchAgentParams struct {
	NodeID          uuid.UUID
	Version         string
	ProtocolVersion int32
}

func (q *Queries) TouchAgent(ctx context.Context, arg TouchAgentParams) error {
	_, err := q.db.Exec(ctx, touchAgent, arg.NodeID, arg.Version, arg.ProtocolVersion)
	return err
}

const upsertNodeFacts = `-- name: UpsertNodeFacts :exec
INSERT INTO node_facts (node_id, hash, facts, collected_at, changed_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (node_id) DO UPDATE
SET facts = EXCLUDED.facts, collected_at = EXCLUDED.collected_at,
    changed_at = CASE WHEN node_facts.hash = EXCLUDED.hash THEN node_facts.changed_at ELSE now() END,
    hash = EXCLUDED.hash
`

type UpsertNodeFactsParams struct {
	NodeID      uuid.UUID
	Hash        string
	Facts       []byte
	CollectedAt time.Time
}

// De facts zelf altijd vervangen (schijfgebruik verandert steeds), changed_at
// alleen als de hash van de stabiele velden verandert.
func (q *Queries) UpsertNodeFacts(ctx context.Context, arg UpsertNodeFactsParams) error {
	_, err := q.db.Exec(ctx, upsertNodeFacts,
		arg.NodeID,
		arg.Hash,
		arg.Facts,
		arg.CollectedAt,
	)
	return err
}

const upsertNodeStatus = `-- name: UpsertNodeStatus :exec
INSERT INTO node_status (node_id, heartbeat_at, uptime_seconds, load1, load5, load15, addresses, services)
VALUES ($1, now(), $2, $3, $4, $5, $6, $7)
ON CONFLICT (node_id) DO UPDATE
SET heartbeat_at = now(), uptime_seconds = EXCLUDED.uptime_seconds, load1 = EXCLUDED.load1,
    load5 = EXCLUDED.load5, load15 = EXCLUDED.load15, addresses = EXCLUDED.addresses,
    services = EXCLUDED.services
`

type UpsertNodeStatusParams struct {
	NodeID        uuid.UUID
	UptimeSeconds int64
	Load1         float64
	Load5         float64
	Load15        float64
	Addresses     []string
	Services      []byte
}

func (q *Queries) UpsertNodeStatus(ctx context.Context, arg UpsertNodeStatusParams) error {
	_, err := q.db.Exec(ctx, upsertNodeStatus,
		arg.NodeID,
		arg.UptimeSeconds,
		arg.Load1,
		arg.Load5,
		arg.Load15,
		arg.Addresses,
		arg.Services,
	)
	return err
}

const useEnrollmentToken = `-- name: UseEnrollmentToken :exec
UPDATE enrollment_tokens SET uses = uses + 1 WHERE id = $1
`

func (q *Queries) UseEnrollmentToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, useEnrollmentToken, id)
	return err
}
