// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: backups.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countBackupTargets = `-- name: CountBackupTargets :one
SELECT (SELECT count(*) FROM nodes WHERE proxmox_id = $1::uuid)
     + (SELECT count(*) FROM backup_watch WHERE connection_id = $1::uuid) AS count
`

// Hoeveel VM's van een koppeling we bewaken: gekoppelde nodes en de lijst
// "ook bewaken".
func (q *Queries) CountBackupTargets(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countBackupTargets, id)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const deleteBackupStatus = `-- name: DeleteBackupStatus :exec
DELETE FROM backup_status WHERE connection_id = $1 AND vmid = $2
`

type DeleteBackupStatusParams struct {
	ConnectionID uuid.UUID
	Vmid         int32
}

func (q *Queries) DeleteBackupStatus(ctx context.Context, arg DeleteBackupStatusParams) error {
	_, err := q.db.Exec(ctx, deleteBackupStatus, arg.ConnectionID, arg.Vmid)
	return err
}

const deleteBackupWatch = `-- name: DeleteBackupWatch :exec
DELETE FROM backup_watch WHERE connection_id = $1
`

func (q *Queries) DeleteBackupWatch(ctx context.Context, connectionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBackupWatch, connectionID)
	return err
}

const deleteStaleProxmoxBackups = `-- name: DeleteStaleProxmoxBackups :exec
DELETE FROM proxmox_backups
WHERE connection_id = $1 AND synced_at < $2
  AND NOT (storage = ANY ($3::text[]) OR storage || '@' || pve_node = ANY ($3::text[]))
`

type DeleteStaleProxmoxBackupsParams struct {
	ConnectionID uuid.UUID
	SyncedAt     time.Time
	Keep         []string
}

// Verwijdert back-ups die niet meer in de lijst stonden, behalve op storages
// die deze keer niet te lezen waren: keep bevat "storage" (gedeeld) of
// "storage@host".
func (q *Queries) DeleteStaleProxmoxBackups(ctx context.Context, arg DeleteStaleProxmoxBackupsParams) error {
	_, err := q.db.Exec(ctx, deleteStaleProxmoxBackups, arg.ConnectionID, arg.SyncedAt, arg.Keep)
	return err
}

const getBackupPolicy = `-- name: GetBackupPolicy :one
SELECT cluster_id, max_age_hours, updated_at, updated_by, verify_enabled, next_run_at FROM backup_policies WHERE cluster_id = $1
`

func (q *Queries) GetBackupPolicy(ctx context.Context, clusterID uuid.UUID) (BackupPolicy, error) {
	row := q.db.QueryRow(ctx, getBackupPolicy, clusterID)
	var i BackupPolicy
	err := row.Scan(
		&i.ClusterID,
		&i.MaxAgeHours,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.VerifyEnabled,
		&i.NextRunAt,
	)
	return i, err
}

const insertBackupStatus = `-- name: InsertBackupStatus :exec
INSERT INTO backup_status (connection_id, vmid, freshness, latest_backup_at)
VALUES ($1, $2, $3, $4)
`

type InsertBackupStatusParams struct {
	ConnectionID   uuid.UUID
	Vmid           int32
	Freshness      string
	LatestBackupAt *time.Time
}

func (q *Queries) InsertBackupStatus(ctx context.Context, arg InsertBackupStatusParams) error {
	_, err := q.db.Exec(ctx, insertBackupStatus,
		arg.ConnectionID,
		arg.Vmid,
		arg.Freshness,
		arg.LatestBackupAt,
	)
	return err
}

const insertBackupWatch = `-- name: InsertBackupWatch :exec
INSERT INTO backup_watch (connection_id, vmid, label) VALUES ($1, $2, $3)
`

type InsertBackupWatchParams struct {
	ConnectionID uuid.UUID
	Vmid         int32
	Label        string
}

func (q *Queries) InsertBackupWatch(ctx context.Context, arg InsertBackupWatchParams) error {
	_, err := q.db.Exec(ctx, insertBackupWatch, arg.ConnectionID, arg.Vmid, arg.Label)
	return err
}

const listBackupConnections = `-- name: ListBackupConnections :many
SELECT id, name, last_error, backup_checked_at, backup_error, not_backed_up,
       (SELECT count(*) FROM proxmox_backups b WHERE b.connection_id = c.id)::integer AS backup_count
FROM proxmox_connections c
ORDER BY lower(name)
`

type ListBackupConnectionsRow struct {
	ID              uuid.UUID
	Name            string
	LastError       string
	BackupCheckedAt *time.Time
	BackupError     string
	NotBackedUp     []byte
	BackupCount     int32
}

func (q *Queries) ListBackupConnections(ctx context.Context) ([]ListBackupConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listBackupConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackupConnectionsRow{}
	for rows.Next() {
		var i ListBackupConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LastError,
			&i.BackupCheckedAt,
			&i.BackupError,
			&i.NotBackedUp,
			&i.BackupCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupStatus = `-- name: ListBackupStatus :many
SELECT connection_id, vmid, freshness, latest_backup_at, changed_at FROM backup_status
`

func (q *Queries) ListBackupStatus(ctx context.Context) ([]BackupStatus, error) {
	rows, err := q.db.Query(ctx, listBackupStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupStatus{}
	for rows.Next() {
		var i BackupStatus
		if err := rows.Scan(
			&i.ConnectionID,
			&i.Vmid,
			&i.Freshness,
			&i.LatestBackupAt,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupStorages = `-- name: ListBackupStorages :many
SELECT s.pve_node, s.name AS storage, coalesce((s.data->>'shared')::int, 0) = 1 AS shared,
       coalesce(h.status, '') = 'online' AS host_online
FROM proxmox_resources s
LEFT JOIN proxmox_resources h ON h.connection_id = s.connection_id AND h.type = 'node' AND h.pve_node = s.pve_node
WHERE s.connection_id = $1 AND s.type = 'storage'
  AND 'backup' = ANY (string_to_array(coalesce(s.data->>'content', ''), ','))
  AND coalesce(s.status, '') IN ('', 'available')
ORDER BY s.name, s.pve_node
`

type ListBackupStoragesRow struct {
	PveNode    string
	Storage    string
	Shared     bool
	HostOnline bool
}

// Storages die back-ups mogen bevatten, met de host waarop ze staan en of
// die host online is. Gedeelde storage staat er per host in.
func (q *Queries) ListBackupStorages(ctx context.Context, connectionID uuid.UUID) ([]ListBackupStoragesRow, error) {
	rows, err := q.db.Query(ctx, listBackupStorages, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackupStoragesRow{}
	for rows.Next() {
		var i ListBackupStoragesRow
		if err := rows.Scan(
			&i.PveNode,
			&i.Storage,
			&i.Shared,
			&i.HostOnline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupTargets = `-- name: ListBackupTargets :many
WITH targets AS (
    SELECT n.proxmox_id AS connection_id, n.pve_vmid::integer AS vmid, false AS watched, '' AS label
    FROM nodes n WHERE n.proxmox_id IS NOT NULL
    UNION ALL
    SELECT w.connection_id, w.vmid, true, w.label
    FROM backup_watch w
    WHERE NOT EXISTS (SELECT 1 FROM nodes n WHERE n.proxmox_id = w.connection_id AND n.pve_vmid = w.vmid)
)
SELECT c.id AS connection_id, t.vmid::integer AS vmid, t.watched::boolean AS watched, t.label::text AS label,
       c.name AS connection_name, coalesce(bp.max_age_hours, 30)::integer AS max_age_hours,
       c.backup_checked_at, c.backup_error, c.last_error,
       n.id AS node_id, n.hostname AS node_hostname, n.cluster_id, cl.name AS cluster_name,
       r.name AS guest_name, r.type AS guest_type,
       (SELECT count(*) FROM proxmox_backups x WHERE x.connection_id = t.connection_id AND x.vmid = t.vmid)::integer
           AS backup_count,
       s.freshness AS last_freshness, s.changed_at AS freshness_since
FROM targets t
JOIN proxmox_connections c ON c.id = t.connection_id
LEFT JOIN nodes n ON n.proxmox_id = t.connection_id AND n.pve_vmid = t.vmid
LEFT JOIN clusters cl ON cl.id = n.cluster_id
LEFT JOIN backup_policies bp ON bp.cluster_id = n.cluster_id
LEFT JOIN proxmox_resources r ON r.connection_id = t.connection_id AND r.vmid = t.vmid AND r.type IN ('qemu', 'lxc')
LEFT JOIN backup_status s ON s.connection_id = t.connection_id AND s.vmid = t.vmid
ORDER BY t.watched, cl.name NULLS LAST, n.hostname NULLS LAST, c.name, t.vmid
`

type ListBackupTargetsRow struct {
	ConnectionID    uuid.UUID
	Vmid            int32
	Watched         bool
	Label           string
	ConnectionName  string
	MaxAgeHours     int32
	BackupCheckedAt *time.Time
	BackupError     string
	LastError       string
	NodeID          *uuid.UUID
	NodeHostname    *string
	ClusterID       *uuid.UUID
	ClusterName     *string
	GuestName       *string
	GuestType       *string
	BackupCount     int32
	LastFreshness   *string
	FreshnessSince  *time.Time
}

// Elke bewaakte VM met zijn node, cluster, maximale leeftijd en het aantal
// back-ups.
func (q *Queries) ListBackupTargets(ctx context.Context) ([]ListBackupTargetsRow, error) {
	rows, err := q.db.Query(ctx, listBackupTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackupTargetsRow{}
	for rows.Next() {
		var i ListBackupTargetsRow
		if err := rows.Scan(
			&i.ConnectionID,
			&i.Vmid,
			&i.Watched,
			&i.Label,
			&i.ConnectionName,
			&i.MaxAgeHours,
			&i.BackupCheckedAt,
			&i.BackupError,
			&i.LastError,
			&i.NodeID,
			&i.NodeHostname,
			&i.ClusterID,
			&i.ClusterName,
			&i.GuestName,
			&i.GuestType,
			&i.BackupCount,
			&i.LastFreshness,
			&i.FreshnessSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupWatch = `-- name: ListBackupWatch :many
SELECT connection_id, vmid, label, created_at FROM backup_watch ORDER BY connection_id, vmid
`

func (q *Queries) ListBackupWatch(ctx context.Context) ([]BackupWatch, error) {
	rows, err := q.db.Query(ctx, listBackupWatch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupWatch{}
	for rows.Next() {
		var i BackupWatch
		if err := rows.Scan(
			&i.ConnectionID,
			&i.Vmid,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueBackupVerifies = `-- name: ListDueBackupVerifies :many
SELECT bp.cluster_id, bp.next_run_at, c.name AS cluster_name
FROM backup_policies bp
JOIN clusters c ON c.id = bp.cluster_id
WHERE bp.verify_enabled AND bp.next_run_at <= $1
ORDER BY bp.next_run_at, c.name
`

type ListDueBackupVerifiesRow struct {
	ClusterID   uuid.UUID
	NextRunAt   *time.Time
	ClusterName string
}

// Clusters waarvan de geplande back-upcontrole aan de beurt is.
func (q *Queries) ListDueBackupVerifies(ctx context.Context, now *time.Time) ([]ListDueBackupVerifiesRow, error) {
	rows, err := q.db.Query(ctx, listDueBackupVerifies, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueBackupVerifiesRow{}
	for rows.Next() {
		var i ListDueBackupVerifiesRow
		if err := rows.Scan(&i.ClusterID, &i.NextRunAt, &i.ClusterName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuestBackups = `-- name: ListGuestBackups :many
SELECT connection_id, volid, storage, pve_node, vmid, guest_type, ctime, size_bytes, format, notes, protected, verify_state, synced_at FROM proxmox_backups
WHERE connection_id = $1 AND vmid = $2
ORDER BY ctime DESC
`

type ListGuestBackupsParams struct {
	ConnectionID uuid.UUID
	Vmid         int32
}

func (q *Queries) ListGuestBackups(ctx context.Context, arg ListGuestBackupsParams) ([]ProxmoxBackup, error) {
	rows, err := q.db.Query(ctx, listGuestBackups, arg.ConnectionID, arg.Vmid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxmoxBackup{}
	for rows.Next() {
		var i ProxmoxBackup
		if err := rows.Scan(
			&i.ConnectionID,
			&i.Volid,
			&i.Storage,
			&i.PveNode,
			&i.Vmid,
			&i.GuestType,
			&i.Ctime,
			&i.SizeBytes,
			&i.Format,
			&i.Notes,
			&i.Protected,
			&i.VerifyState,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestBackups = `-- name: ListLatestBackups :many
SELECT DISTINCT ON (connection_id, vmid) connection_id, volid, storage, pve_node, vmid, guest_type, ctime, size_bytes, format, notes, protected, verify_state, synced_at
FROM proxmox_backups
ORDER BY connection_id, vmid, ctime DESC
`

// De nieuwste back-up per VM.
func (q *Queries) ListLatestBackups(ctx context.Context) ([]ProxmoxBackup, error) {
	rows, err := q.db.Query(ctx, listLatestBackups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxmoxBackup{}
	for rows.Next() {
		var i ProxmoxBackup
		if err := rows.Scan(
			&i.ConnectionID,
			&i.Volid,
			&i.Storage,
			&i.PveNode,
			&i.Vmid,
			&i.GuestType,
			&i.Ctime,
			&i.SizeBytes,
			&i.Format,
			&i.Notes,
			&i.Protected,
			&i.VerifyState,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifyCandidates = `-- name: ListVerifyCandidates :many
SELECT n.id, n.hostname,
       coalesce((SELECT max(r.created_at) FROM test_runs r
                 WHERE r.node_id = n.id AND r.kind = 'backup.verify' AND r.result IN ('pass', 'warning', 'fail')),
                'epoch'::timestamptz)::timestamptz AS last_verified_at
FROM nodes n
WHERE n.cluster_id = $1 AND n.proxmox_id IS NOT NULL AND n.pve_vmid IS NOT NULL
ORDER BY last_verified_at, n.hostname
`

type ListVerifyCandidatesRow struct {
	ID             uuid.UUID
	Hostname       string
	LastVerifiedAt time.Time
}

// De nodes van een cluster die aan een VM gekoppeld zijn, de langst niet
// gecontroleerde eerst.
func (q *Queries) ListVerifyCandidates(ctx context.Context, clusterID *uuid.UUID) ([]ListVerifyCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listVerifyCandidates, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVerifyCandidatesRow{}
	for rows.Next() {
		var i ListVerifyCandidatesRow
		if err := rows.Scan(&i.ID, &i.Hostname, &i.LastVerifiedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBackupInventoryResult = `-- name: SetBackupInventoryResult :exec
UPDATE proxmox_connections
SET backup_checked_at = now(), backup_error = $1::text,
    not_backed_up = CASE WHEN $1::text = '' THEN $2::jsonb ELSE not_backed_up END
WHERE id = $3
`

type SetBackupInventoryResultParams struct {
	Error       string
	NotBackedUp []byte
	ID          uuid.UUID
}

func (q *Queries) SetBackupInventoryResult(ctx context.Context, arg SetBackupInventoryResultParams) error {
	_, err := q.db.Exec(ctx, setBackupInventoryResult, arg.Error, arg.NotBackedUp, arg.ID)
	return err
}

const setBackupVerifyNextRun = `-- name: SetBackupVerifyNextRun :exec
UPDATE backup_policies SET next_run_at = $1 WHERE cluster_id = $2 AND verify_enabled
`

type SetBackupVerifyNextRunParams struct {
	NextRunAt *time.Time
	ClusterID uuid.UUID
}

func (q *Queries) SetBackupVerifyNextRun(ctx context.Context, arg SetBackupVerifyNextRunParams) error {
	_, err := q.db.Exec(ctx, setBackupVerifyNextRun, arg.NextRunAt, arg.ClusterID)
	return err
}

const setBackupVerifySchedule = `-- name: SetBackupVerifySchedule :exec
INSERT INTO backup_policies (cluster_id, verify_enabled, next_run_at, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (cluster_id) DO UPDATE
SET verify_enabled = EXCLUDED.verify_enabled, next_run_at = EXCLUDED.next_run_at,
    updated_by = EXCLUDED.updated_by, updated_at = now()
`

type SetBackupVerifyScheduleParams struct {
	ClusterID     uuid.UUID
	VerifyEnabled bool
	NextRunAt     *time.Time
	UpdatedBy     *uuid.UUID
}

// De back-upcontrole van een cluster gepland aan of uit.
func (q *Queries) SetBackupVerifySchedule(ctx context.Context, arg SetBackupVerifyScheduleParams) error {
	_, err := q.db.Exec(ctx, setBackupVerifySchedule,
		arg.ClusterID,
		arg.VerifyEnabled,
		arg.NextRunAt,
		arg.UpdatedBy,
	)
	return err
}

const updateBackupStatus = `-- name: UpdateBackupStatus :exec
UPDATE backup_status
SET freshness = $3, latest_backup_at = $4,
    changed_at = CASE WHEN freshness = $3 THEN changed_at ELSE now() END
WHERE connection_id = $1 AND vmid = $2
`

type UpdateBackupStatusParams struct {
	ConnectionID   uuid.UUID
	Vmid           int32
	Freshness      string
	LatestBackupAt *time.Time
}

func (q *Queries) UpdateBackupStatus(ctx context.Context, arg UpdateBackupStatusParams) error {
	_, err := q.db.Exec(ctx, updateBackupStatus,
		arg.ConnectionID,
		arg.Vmid,
		arg.Freshness,
		arg.LatestBackupAt,
	)
	return err
}

const upsertBackupPolicy = `-- name: UpsertBackupPolicy :exec
INSERT INTO backup_policies (cluster_id, max_age_hours, updated_by)
VALUES ($1, $2, $3)
ON CONFLICT (cluster_id) DO UPDATE
SET max_age_hours = EXCLUDED.max_age_hours, updated_by = EXCLUDED.updated_by, updated_at = now()
`

type UpsertBackupPolicyParams struct {
	ClusterID   uuid.UUID
	MaxAgeHours int32
	UpdatedBy   *uuid.UUID
}

func (q *Queries) UpsertBackupPolicy(ctx context.Context, arg UpsertBackupPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertBackupPolicy, arg.ClusterID, arg.MaxAgeHours, arg.UpdatedBy)
	return err
}
