// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package store

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertProxmoxResource = `-- name: UpsertProxmoxResource :batchexec
INSERT INTO proxmox_resources (connection_id, pve_id, type, pve_node, vmid, name, status, template, data, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (connection_id, pve_id) DO UPDATE
SET type = EXCLUDED.type, pve_node = EXCLUDED.pve_node, vmid = EXCLUDED.vmid, name = EXCLUDED.name,
    status = EXCLUDED.status, template = EXCLUDED.template, data = EXCLUDED.data, synced_at = EXCLUDED.synced_at
`

type UpsertProxmoxResourceBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertProxmoxResourceParams struct {
	ConnectionID uuid.UUID
	PveID        string
	Type         string
	PveNode      string
	Vmid         *int32
	Name         string
	Status       string
	Template     bool
	Data         []byte
	SyncedAt     time.Time
}

func (q *Queries) UpsertProxmoxResource(ctx context.Context, arg []UpsertProxmoxResourceParams) *UpsertProxmoxResourceBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ConnectionID,
			a.PveID,
			a.Type,
			a.PveNode,
			a.Vmid,
			a.Name,
			a.Status,
			a.Template,
			a.Data,
			a.SyncedAt,
		}
		batch.Queue(upsertProxmoxResource, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertProxmoxResourceBatchResults{br, len(arg), false}
}

func (b *UpsertProxmoxResourceBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertProxmoxResourceBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
