// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: clusters.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addClusterOwner = `-- name: AddClusterOwner :exec
INSERT INTO cluster_owners (cluster_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddClusterOwnerParams struct {
	ClusterID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) AddClusterOwner(ctx context.Context, arg AddClusterOwnerParams) error {
	_, err := q.db.Exec(ctx, addClusterOwner, arg.ClusterID, arg.UserID)
	return err
}

const clearClusterOwners = `-- name: ClearClusterOwners :exec
DELETE FROM cluster_owners WHERE cluster_id = $1
`

func (q *Queries) ClearClusterOwners(ctx context.Context, clusterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearClusterOwners, clusterID)
	return err
}

const createCluster = `-- name: CreateCluster :one
INSERT INTO clusters (slug, name, description, type, environment, git_repo_url, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, slug, name, description, type, environment, git_repo_url, tags, status, spec, spec_revision, template_name, template_version, created_at, updated_at, status_reason, status_since
`

type CreateClusterParams struct {
	Slug        string
	Name        string
	Description string
	Type        string
	Environment Environment
	GitRepoUrl  string
	Tags        []string
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, createCluster,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Environment,
		arg.GitRepoUrl,
		arg.Tags,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Environment,
		&i.GitRepoUrl,
		&i.Tags,
		&i.Status,
		&i.Spec,
		&i.SpecRevision,
		&i.TemplateName,
		&i.TemplateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusReason,
		&i.StatusSince,
	)
	return i, err
}

const deleteCluster = `-- name: DeleteCluster :execrows
DELETE FROM clusters WHERE id = $1
`

func (q *Queries) DeleteCluster(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCluster, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCluster = `-- name: GetCluster :one
SELECT id, slug, name, description, type, environment, git_repo_url, tags, status, spec, spec_revision, template_name, template_version, created_at, updated_at, status_reason, status_since FROM clusters WHERE id = $1
`

func (q *Queries) GetCluster(ctx context.Context, id uuid.UUID) (Cluster, error) {
	row := q.db.QueryRow(ctx, getCluster, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Environment,
		&i.GitRepoUrl,
		&i.Tags,
		&i.Status,
		&i.Spec,
		&i.SpecRevision,
		&i.TemplateName,
		&i.TemplateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusReason,
		&i.StatusSince,
	)
	return i, err
}

const listClusterOwners = `-- name: ListClusterOwners :many
SELECT u.id, u.username
FROM cluster_owners o JOIN users u ON u.id = o.user_id
WHERE o.cluster_id = $1
ORDER BY u.username
`

type ListClusterOwnersRow struct {
	ID       uuid.UUID
	Username string
}

func (q *Queries) ListClusterOwners(ctx context.Context, clusterID uuid.UUID) ([]ListClusterOwnersRow, error) {
	rows, err := q.db.Query(ctx, listClusterOwners, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClusterOwnersRow{}
	for rows.Next() {
		var i ListClusterOwnersRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusters = `-- name: ListClusters :many
SELECT c.id, c.slug, c.name, c.description, c.type, c.environment, c.git_repo_url, c.tags, c.status, c.spec, c.spec_revision, c.template_name, c.template_version, c.created_at, c.updated_at, c.status_reason, c.status_since,
       (SELECT count(*) FROM nodes n WHERE n.cluster_id = c.id)::int AS node_count,
       (SELECT count(*) FROM vips v WHERE v.cluster_id = c.id)::int AS vip_count,
       (SELECT count(*) FROM nodes n JOIN drift_checks d ON d.node_id = n.id
        WHERE n.cluster_id = c.id AND n.lifecycle = 'active' AND d.status = 'drift')::int AS drift_nodes,
       (SELECT count(*) FROM nodes n LEFT JOIN drift_checks d ON d.node_id = n.id
        WHERE n.cluster_id = c.id AND n.lifecycle = 'active' AND (d.node_id IS NULL OR d.status = 'error'))::int AS drift_unknown,
       (SELECT min(d.checked_at) FROM nodes n JOIN drift_checks d ON d.node_id = n.id
        WHERE n.cluster_id = c.id AND n.lifecycle = 'active') AS drift_checked_at
FROM clusters c
ORDER BY c.name
`

type ListClustersRow struct {
	Cluster        Cluster
	NodeCount      int32
	VipCount       int32
	DriftNodes     int32
	DriftUnknown   int32
	DriftCheckedAt interface{}
}

// Met de samenvatting van de drift over de actieve nodes: hoeveel drift
// hebben, hoeveel niet of met een fout gecontroleerd zijn, en de oudste
// controle.
func (q *Queries) ListClusters(ctx context.Context) ([]ListClustersRow, error) {
	rows, err := q.db.Query(ctx, listClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClustersRow{}
	for rows.Next() {
		var i ListClustersRow
		if err := rows.Scan(
			&i.Cluster.ID,
			&i.Cluster.Slug,
			&i.Cluster.Name,
			&i.Cluster.Description,
			&i.Cluster.Type,
			&i.Cluster.Environment,
			&i.Cluster.GitRepoUrl,
			&i.Cluster.Tags,
			&i.Cluster.Status,
			&i.Cluster.Spec,
			&i.Cluster.SpecRevision,
			&i.Cluster.TemplateName,
			&i.Cluster.TemplateVersion,
			&i.Cluster.CreatedAt,
			&i.Cluster.UpdatedAt,
			&i.Cluster.StatusReason,
			&i.Cluster.StatusSince,
			&i.NodeCount,
			&i.VipCount,
			&i.DriftNodes,
			&i.DriftUnknown,
			&i.DriftCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCluster = `-- name: LockCluster :one
SELECT id, slug, name, description, type, environment, git_repo_url, tags, status, spec, spec_revision, template_name, template_version, created_at, updated_at, status_reason, status_since FROM clusters WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockCluster(ctx context.Context, id uuid.UUID) (Cluster, error) {
	row := q.db.QueryRow(ctx, lockCluster, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Environment,
		&i.GitRepoUrl,
		&i.Tags,
		&i.Status,
		&i.Spec,
		&i.SpecRevision,
		&i.TemplateName,
		&i.TemplateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusReason,
		&i.StatusSince,
	)
	return i, err
}

const touchCluster = `-- name: TouchCluster :exec
UPDATE clusters SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchCluster(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchCluster, id)
	return err
}

const updateCluster = `-- name: UpdateCluster :one
UPDATE clusters
SET slug = $2, name = $3, description = $4, type = $5, environment = $6,
    git_repo_url = $7, tags = $8, updated_at = now()
WHERE id = $1
RETURNING id, slug, name, description, type, environment, git_repo_url, tags, status, spec, spec_revision, template_name, template_version, created_at, updated_at, status_reason, status_since
`

type UpdateClusterParams struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Description string
	Type        string
	Environment Environment
	GitRepoUrl  string
	Tags        []string
}

func (q *Queries) UpdateCluster(ctx context.Context, arg UpdateClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, updateCluster,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Environment,
		arg.GitRepoUrl,
		arg.Tags,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Environment,
		&i.GitRepoUrl,
		&i.Tags,
		&i.Status,
		&i.Spec,
		&i.SpecRevision,
		&i.TemplateName,
		&i.TemplateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusReason,
		&i.StatusSince,
	)
	return i, err
}
