// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deploy.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clusterSlugTaken = `-- name: ClusterSlugTaken :one
SELECT EXISTS (SELECT 1 FROM clusters WHERE slug = $1)
`

func (q *Queries) ClusterSlugTaken(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, clusterSlugTaken, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDeployNode = `-- name: GetDeployNode :one
SELECT n.id, n.hostname, n.role, n.lifecycle, coalesce(host(n.primary_ip), '')::text AS primary_ip,
       a.protocol_version AS agent_protocol, s.heartbeat_at, s.addresses,
       f.facts
FROM nodes n
LEFT JOIN agents a ON a.node_id = n.id AND a.revoked_at IS NULL
LEFT JOIN node_status s ON s.node_id = n.id
LEFT JOIN node_facts f ON f.node_id = n.id
WHERE n.id = $1
`

type GetDeployNodeRow struct {
	ID            uuid.UUID
	Hostname      string
	Role          string
	Lifecycle     NodeLifecycle
	PrimaryIp     string
	AgentProtocol *int32
	HeartbeatAt   *time.Time
	Addresses     []string
	Facts         []byte
}

// Wat een uitrol van een node moet weten: agent, heartbeat en facts.
func (q *Queries) GetDeployNode(ctx context.Context, id uuid.UUID) (GetDeployNodeRow, error) {
	row := q.db.QueryRow(ctx, getDeployNode, id)
	var i GetDeployNodeRow
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.Role,
		&i.Lifecycle,
		&i.PrimaryIp,
		&i.AgentProtocol,
		&i.HeartbeatAt,
		&i.Addresses,
		&i.Facts,
	)
	return i, err
}

const getSecret = `-- name: GetSecret :one
SELECT id, cluster_id, name, value_enc, key_id, created_at FROM secrets WHERE cluster_id = $1 AND name = $2
`

type GetSecretParams struct {
	ClusterID uuid.UUID
	Name      string
}

func (q *Queries) GetSecret(ctx context.Context, arg GetSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecret, arg.ClusterID, arg.Name)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Name,
		&i.ValueEnc,
		&i.KeyID,
		&i.CreatedAt,
	)
	return i, err
}

const insertSecret = `-- name: InsertSecret :exec
INSERT INTO secrets (cluster_id, name, value_enc, key_id) VALUES ($1, $2, $3, $4)
`

type InsertSecretParams struct {
	ClusterID uuid.UUID
	Name      string
	ValueEnc  []byte
	KeyID     string
}

func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) error {
	_, err := q.db.Exec(ctx, insertSecret,
		arg.ClusterID,
		arg.Name,
		arg.ValueEnc,
		arg.KeyID,
	)
	return err
}

const insertSpecRevision = `-- name: InsertSpecRevision :exec
INSERT INTO cluster_spec_revisions (cluster_id, revision, spec, source, created_by, commit_sha)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSpecRevisionParams struct {
	ClusterID uuid.UUID
	Revision  int32
	Spec      []byte
	Source    string
	CreatedBy *uuid.UUID
	CommitSha *string
}

func (q *Queries) InsertSpecRevision(ctx context.Context, arg InsertSpecRevisionParams) error {
	_, err := q.db.Exec(ctx, insertSpecRevision,
		arg.ClusterID,
		arg.Revision,
		arg.Spec,
		arg.Source,
		arg.CreatedBy,
		arg.CommitSha,
	)
	return err
}

const listDesiredNodes = `-- name: ListDesiredNodes :many
SELECT n.id, n.hostname, n.lifecycle, coalesce(host(n.primary_ip), '')::text AS primary_ip, f.facts
FROM nodes n
LEFT JOIN node_facts f ON f.node_id = n.id
WHERE n.cluster_id = $1
ORDER BY n.hostname
`

type ListDesiredNodesRow struct {
	ID        uuid.UUID
	Hostname  string
	Lifecycle NodeLifecycle
	PrimaryIp string
	Facts     []byte
}

// De nodes van een cluster met wat renderen nodig heeft: het vaste adres
// en de facts.
func (q *Queries) ListDesiredNodes(ctx context.Context, clusterID *uuid.UUID) ([]ListDesiredNodesRow, error) {
	rows, err := q.db.Query(ctx, listDesiredNodes, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDesiredNodesRow{}
	for rows.Next() {
		var i ListDesiredNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.Lifecycle,
			&i.PrimaryIp,
			&i.Facts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecRevisions = `-- name: ListSpecRevisions :many
SELECT r.revision, r.spec, r.source, r.commit_sha, r.created_at, r.created_by, u.username AS created_by_name
FROM cluster_spec_revisions r
LEFT JOIN users u ON u.id = r.created_by
WHERE r.cluster_id = $1
ORDER BY r.revision DESC
`

type ListSpecRevisionsRow struct {
	Revision      int32
	Spec          []byte
	Source        string
	CommitSha     *string
	CreatedAt     time.Time
	CreatedBy     *uuid.UUID
	CreatedByName *string
}

func (q *Queries) ListSpecRevisions(ctx context.Context, clusterID uuid.UUID) ([]ListSpecRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listSpecRevisions, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpecRevisionsRow{}
	for rows.Next() {
		var i ListSpecRevisionsRow
		if err := rows.Scan(
			&i.Revision,
			&i.Spec,
			&i.Source,
			&i.CommitSha,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateClusters = `-- name: ListTemplateClusters :many
SELECT name, template_name::text AS template_name, template_version::text AS template_version
FROM clusters WHERE template_name IS NOT NULL AND template_version IS NOT NULL
ORDER BY name
`

type ListTemplateClustersRow struct {
	Name            string
	TemplateName    string
	TemplateVersion string
}

func (q *Queries) ListTemplateClusters(ctx context.Context) ([]ListTemplateClustersRow, error) {
	rows, err := q.db.Query(ctx, listTemplateClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplateClustersRow{}
	for rows.Next() {
		var i ListTemplateClustersRow
		if err := rows.Scan(&i.Name, &i.TemplateName, &i.TemplateVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSpecApplied = `-- name: MarkSpecApplied :exec
UPDATE clusters SET applied_revision = spec_revision WHERE id = $1
`

// Na een geslaagde uitrol staat de huidige revisie op alle nodes.
func (q *Queries) MarkSpecApplied(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSpecApplied, id)
	return err
}

const retryJob = `-- name: RetryJob :one
UPDATE jobs
SET status = 'queued', error = '', cancel_requested = false, attempts = 0, finished_at = NULL, heartbeat_at = NULL
WHERE id = $1 AND status IN ('failed', 'canceled') AND kind = ANY($2::text[])
RETURNING id, kind, title, status, params, cluster_id, node_id, proxmox_id, requested_by, error, cancel_requested, attempts, created_at, started_at, finished_at, heartbeat_at, cluster_slot
`

type RetryJobParams struct {
	ID    uuid.UUID
	Kinds []string
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, retryJob, arg.ID, arg.Kinds)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Title,
		&i.Status,
		&i.Params,
		&i.ClusterID,
		&i.NodeID,
		&i.ProxmoxID,
		&i.RequestedBy,
		&i.Error,
		&i.CancelRequested,
		&i.Attempts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HeartbeatAt,
		&i.ClusterSlot,
	)
	return i, err
}

const setAppliedRevision = `-- name: SetAppliedRevision :exec
UPDATE clusters SET applied_revision = greatest(applied_revision, $1::int)
WHERE id = $2 AND spec_revision >= $1::int
`

type SetAppliedRevisionParams struct {
	Revision int32
	ID       uuid.UUID
}

// Na een geslaagde toepassing; een oudere revisie zet hem nooit terug.
func (q *Queries) SetAppliedRevision(ctx context.Context, arg SetAppliedRevisionParams) error {
	_, err := q.db.Exec(ctx, setAppliedRevision, arg.Revision, arg.ID)
	return err
}

const setClusterSpec = `-- name: SetClusterSpec :one
UPDATE clusters
SET spec = $1, spec_revision = spec_revision + 1, template_name = $2,
    template_version = $3, updated_at = now()
WHERE id = $4
RETURNING spec_revision
`

type SetClusterSpecParams struct {
	Spec            []byte
	TemplateName    *string
	TemplateVersion *string
	ID              uuid.UUID
}

func (q *Queries) SetClusterSpec(ctx context.Context, arg SetClusterSpecParams) (int32, error) {
	row := q.db.QueryRow(ctx, setClusterSpec,
		arg.Spec,
		arg.TemplateName,
		arg.TemplateVersion,
		arg.ID,
	)
	var spec_revision int32
	err := row.Scan(&spec_revision)
	return spec_revision, err
}

const setNodeProxmox = `-- name: SetNodeProxmox :exec
UPDATE nodes SET proxmox_id = $1, pve_vmid = $2, updated_at = now() WHERE id = $3
`

type SetNodeProxmoxParams struct {
	ProxmoxID *uuid.UUID
	PveVmid   *int32
	ID        uuid.UUID
}

func (q *Queries) SetNodeProxmox(ctx context.Context, arg SetNodeProxmoxParams) error {
	_, err := q.db.Exec(ctx, setNodeProxmox, arg.ProxmoxID, arg.PveVmid, arg.ID)
	return err
}

const setVIPInterface = `-- name: SetVIPInterface :exec
UPDATE vips SET interface = $1, updated_at = now()
WHERE cluster_id = $2 AND host(address) = $3::text AND interface = ''
`

type SetVIPInterfaceParams struct {
	Interface string
	ClusterID uuid.UUID
	Address   string
}

// Na een uitrol: de netwerkkaart van het VIP, als die nog leeg is.
func (q *Queries) SetVIPInterface(ctx context.Context, arg SetVIPInterfaceParams) error {
	_, err := q.db.Exec(ctx, setVIPInterface, arg.Interface, arg.ClusterID, arg.Address)
	return err
}

const usedAddresses = `-- name: UsedAddresses :many
SELECT host(primary_ip)::text AS address FROM nodes WHERE primary_ip IS NOT NULL
UNION
SELECT host(address)::text FROM vips
`

// Adressen die al bij een node of VIP horen, om botsingen te vermijden.
func (q *Queries) UsedAddresses(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, usedAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, err
		}
		items = append(items, address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usedVRIDs = `-- name: UsedVRIDs :many
SELECT vrid::int FROM vips WHERE vrid IS NOT NULL
`

func (q *Queries) UsedVRIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.Query(ctx, usedVRIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var vrid int32
		if err := rows.Scan(&vrid); err != nil {
			return nil, err
		}
		items = append(items, vrid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
