// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deploy.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clusterSlugTaken = `-- name: ClusterSlugTaken :one
SELECT EXISTS (SELECT 1 FROM clusters WHERE slug = $1)
`

func (q *Queries) ClusterSlugTaken(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, clusterSlugTaken, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDeployNode = `-- name: GetDeployNode :one
SELECT n.id, n.hostname, n.role, n.lifecycle, coalesce(host(n.primary_ip), '')::text AS primary_ip,
       a.protocol_version AS agent_protocol, s.heartbeat_at, s.addresses,
       f.facts
FROM nodes n
LEFT JOIN agents a ON a.node_id = n.id AND a.revoked_at IS NULL
LEFT JOIN node_status s ON s.node_id = n.id
LEFT JOIN node_facts f ON f.node_id = n.id
WHERE n.id = $1
`

type GetDeployNodeRow struct {
	ID            uuid.UUID
	Hostname      string
	Role          string
	Lifecycle     NodeLifecycle
	PrimaryIp     string
	AgentProtocol *int32
	HeartbeatAt   *time.Time
	Addresses     []string
	Facts         []byte
}

// Wat een uitrol van een node moet weten: agent, heartbeat en facts.
func (q *Queries) GetDeployNode(ctx context.Context, id uuid.UUID) (GetDeployNodeRow, error) {
	row := q.db.QueryRow(ctx, getDeployNode, id)
	var i GetDeployNodeRow
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.Role,
		&i.Lifecycle,
		&i.PrimaryIp,
		&i.AgentProtocol,
		&i.HeartbeatAt,
		&i.Addresses,
		&i.Facts,
	)
	return i, err
}

const getSecret = `-- name: GetSecret :one
SELECT id, cluster_id, name, value_enc, key_id, created_at FROM secrets WHERE cluster_id = $1 AND name = $2
`

type GetSecretParams struct {
	ClusterID uuid.UUID
	Name      string
}

func (q *Queries) GetSecret(ctx context.Context, arg GetSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecret, arg.ClusterID, arg.Name)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Name,
		&i.ValueEnc,
		&i.KeyID,
		&i.CreatedAt,
	)
	return i, err
}

const insertSecret = `-- name: InsertSecret :exec
INSERT INTO secrets (cluster_id, name, value_enc, key_id) VALUES ($1, $2, $3, $4)
`

type InsertSecretParams struct {
	ClusterID uuid.UUID
	Name      string
	ValueEnc  []byte
	KeyID     string
}

func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) error {
	_, err := q.db.Exec(ctx, insertSecret,
		arg.ClusterID,
		arg.Name,
		arg.ValueEnc,
		arg.KeyID,
	)
	return err
}

const insertSpecRevision = `-- name: InsertSpecRevision :exec
INSERT INTO cluster_spec_revisions (cluster_id, revision, spec, source, created_by)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSpecRevisionParams struct {
	ClusterID uuid.UUID
	Revision  int32
	Spec      []byte
	Source    string
	CreatedBy *uuid.UUID
}

func (q *Queries) InsertSpecRevision(ctx context.Context, arg InsertSpecRevisionParams) error {
	_, err := q.db.Exec(ctx, insertSpecRevision,
		arg.ClusterID,
		arg.Revision,
		arg.Spec,
		arg.Source,
		arg.CreatedBy,
	)
	return err
}

const retryJob = `-- name: RetryJob :one
UPDATE jobs
SET status = 'queued', error = '', cancel_requested = false, attempts = 0, finished_at = NULL, heartbeat_at = NULL
WHERE id = $1 AND status IN ('failed', 'canceled') AND kind = ANY($2::text[])
RETURNING id, kind, title, status, params, cluster_id, node_id, proxmox_id, requested_by, error, cancel_requested, attempts, created_at, started_at, finished_at, heartbeat_at, cluster_slot
`

type RetryJobParams struct {
	ID    uuid.UUID
	Kinds []string
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, retryJob, arg.ID, arg.Kinds)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Title,
		&i.Status,
		&i.Params,
		&i.ClusterID,
		&i.NodeID,
		&i.ProxmoxID,
		&i.RequestedBy,
		&i.Error,
		&i.CancelRequested,
		&i.Attempts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HeartbeatAt,
		&i.ClusterSlot,
	)
	return i, err
}

const setClusterSpec = `-- name: SetClusterSpec :one
UPDATE clusters
SET spec = $1, spec_revision = spec_revision + 1, template_name = $2,
    template_version = $3, updated_at = now()
WHERE id = $4
RETURNING spec_revision
`

type SetClusterSpecParams struct {
	Spec            []byte
	TemplateName    *string
	TemplateVersion *string
	ID              uuid.UUID
}

func (q *Queries) SetClusterSpec(ctx context.Context, arg SetClusterSpecParams) (int32, error) {
	row := q.db.QueryRow(ctx, setClusterSpec,
		arg.Spec,
		arg.TemplateName,
		arg.TemplateVersion,
		arg.ID,
	)
	var spec_revision int32
	err := row.Scan(&spec_revision)
	return spec_revision, err
}

const setNodeProxmox = `-- name: SetNodeProxmox :exec
UPDATE nodes SET proxmox_id = $1, pve_vmid = $2, updated_at = now() WHERE id = $3
`

type SetNodeProxmoxParams struct {
	ProxmoxID *uuid.UUID
	PveVmid   *int32
	ID        uuid.UUID
}

func (q *Queries) SetNodeProxmox(ctx context.Context, arg SetNodeProxmoxParams) error {
	_, err := q.db.Exec(ctx, setNodeProxmox, arg.ProxmoxID, arg.PveVmid, arg.ID)
	return err
}

const setVIPInterface = `-- name: SetVIPInterface :exec
UPDATE vips SET interface = $1, updated_at = now()
WHERE cluster_id = $2 AND host(address) = $3::text AND interface = ''
`

type SetVIPInterfaceParams struct {
	Interface string
	ClusterID uuid.UUID
	Address   string
}

// Na een uitrol: de netwerkkaart van het VIP, als die nog leeg is.
func (q *Queries) SetVIPInterface(ctx context.Context, arg SetVIPInterfaceParams) error {
	_, err := q.db.Exec(ctx, setVIPInterface, arg.Interface, arg.ClusterID, arg.Address)
	return err
}

const usedAddresses = `-- name: UsedAddresses :many
SELECT host(primary_ip)::text AS address FROM nodes WHERE primary_ip IS NOT NULL
UNION
SELECT host(address)::text FROM vips
`

// Adressen die al bij een node of VIP horen, om botsingen te vermijden.
func (q *Queries) UsedAddresses(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, usedAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, err
		}
		items = append(items, address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usedVRIDs = `-- name: UsedVRIDs :many
SELECT vrid::int FROM vips WHERE vrid IS NOT NULL
`

func (q *Queries) UsedVRIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.Query(ctx, usedVRIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var vrid int32
		if err := rows.Scan(&vrid); err != nil {
			return nil, err
		}
		items = append(items, vrid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
