// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deps.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteDependenciesOfService = `-- name: DeleteDependenciesOfService :many
DELETE FROM service_dependencies WHERE from_service_id = $1 OR to_service_id = $1
RETURNING id, from_service_id, to_service_id, strength, source, state, note, created_at, updated_at
`

func (q *Queries) DeleteDependenciesOfService(ctx context.Context, serviceID uuid.UUID) ([]ServiceDependency, error) {
	rows, err := q.db.Query(ctx, deleteDependenciesOfService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceDependency{}
	for rows.Next() {
		var i ServiceDependency
		if err := rows.Scan(
			&i.ID,
			&i.FromServiceID,
			&i.ToServiceID,
			&i.Strength,
			&i.Source,
			&i.State,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const deleteServiceDependency = `-- name: DeleteServiceDependency :exec
DELETE FROM service_dependencies WHERE id = $1
`

func (q *Queries) DeleteServiceDependency(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteServiceDependency, id)
	return err
}

const findServiceByName = `-- name: FindServiceByName :one
SELECT id, cluster_id, node_id, name, kind, unit, port, address, description, source, state, last_seen_at, created_at, updated_at, status, status_reason, impact, impact_reason, impact_cause_id, impact_since FROM services
WHERE cluster_id IS NOT DISTINCT FROM $1::uuid
  AND node_id IS NOT DISTINCT FROM $2::uuid
  AND lower(name) = lower($3)
`

type FindServiceByNameParams struct {
	ClusterID *uuid.UUID
	NodeID    *uuid.UUID
	Name      string
}

// De dienst met deze naam in dezelfde scope: een cluster, een losse node of
// extern (beide NULL).
func (q *Queries) FindServiceByName(ctx context.Context, arg FindServiceByNameParams) (Service, error) {
	row := q.db.QueryRow(ctx, findServiceByName, arg.ClusterID, arg.NodeID, arg.Name)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.Name,
		&i.Kind,
		&i.Unit,
		&i.Port,
		&i.Address,
		&i.Description,
		&i.Source,
		&i.State,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.Impact,
		&i.ImpactReason,
		&i.ImpactCauseID,
		&i.ImpactSince,
	)
	return i, err
}

const getService = `-- name: GetService :one
SELECT id, cluster_id, node_id, name, kind, unit, port, address, description, source, state, last_seen_at, created_at, updated_at, status, status_reason, impact, impact_reason, impact_cause_id, impact_since FROM services WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.Name,
		&i.Kind,
		&i.Unit,
		&i.Port,
		&i.Address,
		&i.Description,
		&i.Source,
		&i.State,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.Impact,
		&i.ImpactReason,
		&i.ImpactCauseID,
		&i.ImpactSince,
	)
	return i, err
}

const getServiceDependency = `-- name: GetServiceDependency :one
SELECT id, from_service_id, to_service_id, strength, source, state, note, created_at, updated_at FROM service_dependencies WHERE id = $1
`

func (q *Queries) GetServiceDependency(ctx context.Context, id uuid.UUID) (ServiceDependency, error) {
	row := q.db.QueryRow(ctx, getServiceDependency, id)
	var i ServiceDependency
	err := row.Scan(
		&i.ID,
		&i.FromServiceID,
		&i.ToServiceID,
		&i.Strength,
		&i.Source,
		&i.State,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertService = `-- name: InsertService :one
INSERT INTO services (cluster_id, node_id, name, kind, unit, port, address, description, source, state, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, cluster_id, node_id, name, kind, unit, port, address, description, source, state, last_seen_at, created_at, updated_at, status, status_reason, impact, impact_reason, impact_cause_id, impact_since
`

type InsertServiceParams struct {
	ClusterID   *uuid.UUID
	NodeID      *uuid.UUID
	Name        string
	Kind        string
	Unit        string
	Port        *int32
	Address     string
	Description string
	Source      string
	State       string
	LastSeenAt  *time.Time
}

func (q *Queries) InsertService(ctx context.Context, arg InsertServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, insertService,
		arg.ClusterID,
		arg.NodeID,
		arg.Name,
		arg.Kind,
		arg.Unit,
		arg.Port,
		arg.Address,
		arg.Description,
		arg.Source,
		arg.State,
		arg.LastSeenAt,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.Name,
		&i.Kind,
		&i.Unit,
		&i.Port,
		&i.Address,
		&i.Description,
		&i.Source,
		&i.State,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.Impact,
		&i.ImpactReason,
		&i.ImpactCauseID,
		&i.ImpactSince,
	)
	return i, err
}

const insertServiceDependency = `-- name: InsertServiceDependency :one
INSERT INTO service_dependencies (from_service_id, to_service_id, strength, source, state, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, from_service_id, to_service_id, strength, source, state, note, created_at, updated_at
`

type InsertServiceDependencyParams struct {
	FromServiceID uuid.UUID
	ToServiceID   uuid.UUID
	Strength      string
	Source        string
	State         string
	Note          string
}

func (q *Queries) InsertServiceDependency(ctx context.Context, arg InsertServiceDependencyParams) (ServiceDependency, error) {
	row := q.db.QueryRow(ctx, insertServiceDependency,
		arg.FromServiceID,
		arg.ToServiceID,
		arg.Strength,
		arg.Source,
		arg.State,
		arg.Note,
	)
	var i ServiceDependency
	err := row.Scan(
		&i.ID,
		&i.FromServiceID,
		&i.ToServiceID,
		&i.Strength,
		&i.Source,
		&i.State,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClusterImpacts = `-- name: ListClusterImpacts :many
SELECT s.cluster_id::uuid AS cluster_id, s.impact,
       coalesce(cc.name, cn.hostname, 'extern')::text AS cause_group
FROM services s
JOIN services cause ON cause.id = s.impact_cause_id
LEFT JOIN clusters cc ON cc.id = cause.cluster_id
LEFT JOIN nodes cn ON cn.id = cause.node_id
WHERE s.state = 'confirmed' AND s.impact <> 'none' AND s.cluster_id IS NOT NULL
  AND cause.cluster_id IS DISTINCT FROM s.cluster_id
ORDER BY 1, 3
`

type ListClusterImpactsRow struct {
	ClusterID  uuid.UUID
	Impact     string
	CauseGroup string
}

// Per cluster de doorgegeven uitval op zijn bevestigde diensten, met de groep
// waar ze begint. Uitval binnen het cluster zelf telt niet: dat zegt de
// status van het cluster al.
func (q *Queries) ListClusterImpacts(ctx context.Context) ([]ListClusterImpactsRow, error) {
	rows, err := q.db.Query(ctx, listClusterImpacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClusterImpactsRow{}
	for rows.Next() {
		var i ListClusterImpactsRow
		if err := rows.Scan(&i.ClusterID, &i.Impact, &i.CauseGroup); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepClusters = `-- name: ListDepClusters :many
SELECT id, name, slug, environment, type, status, status_reason FROM clusters ORDER BY name
`

type ListDepClustersRow struct {
	ID           uuid.UUID
	Name         string
	Slug         string
	Environment  Environment
	Type         string
	Status       string
	StatusReason string
}

func (q *Queries) ListDepClusters(ctx context.Context) ([]ListDepClustersRow, error) {
	rows, err := q.db.Query(ctx, listDepClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDepClustersRow{}
	for rows.Next() {
		var i ListDepClustersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Environment,
			&i.Type,
			&i.Status,
			&i.StatusReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingDependencies = `-- name: ListIncomingDependencies :many
SELECT d.id, d.strength, d.source, p.name AS provider, c.name AS consumer,
       coalesce(cc.name, cn.hostname, 'extern')::text AS consumer_scope
FROM service_dependencies d
JOIN services p ON p.id = d.to_service_id
JOIN services c ON c.id = d.from_service_id
LEFT JOIN clusters cc ON cc.id = c.cluster_id
LEFT JOIN nodes cn ON cn.id = c.node_id
WHERE (p.cluster_id = $1::uuid OR p.node_id = $2::uuid)
  AND (c.cluster_id IS DISTINCT FROM p.cluster_id OR c.node_id IS DISTINCT FROM p.node_id)
  AND d.state = 'confirmed' AND c.state = 'confirmed'
ORDER BY consumer_scope, c.name, p.name
`

type ListIncomingDependenciesParams struct {
	ClusterID *uuid.UUID
	NodeID    *uuid.UUID
}

type ListIncomingDependenciesRow struct {
	ID            uuid.UUID
	Strength      string
	Source        string
	Provider      string
	Consumer      string
	ConsumerScope string
}

// De pijlen van buiten naar de diensten van een cluster of een losse node:
// die verdwijnen met het cluster of de node, en komen in het event.
func (q *Queries) ListIncomingDependencies(ctx context.Context, arg ListIncomingDependenciesParams) ([]ListIncomingDependenciesRow, error) {
	rows, err := q.db.Query(ctx, listIncomingDependencies, arg.ClusterID, arg.NodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncomingDependenciesRow{}
	for rows.Next() {
		var i ListIncomingDependenciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Strength,
			&i.Source,
			&i.Provider,
			&i.Consumer,
			&i.ConsumerScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceDependencies = `-- name: ListServiceDependencies :many
SELECT id, from_service_id, to_service_id, strength, source, state, note, created_at, updated_at FROM service_dependencies ORDER BY created_at, id
`

func (q *Queries) ListServiceDependencies(ctx context.Context) ([]ServiceDependency, error) {
	rows, err := q.db.Query(ctx, listServiceDependencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceDependency{}
	for rows.Next() {
		var i ServiceDependency
		if err := rows.Scan(
			&i.ID,
			&i.FromServiceID,
			&i.ToServiceID,
			&i.Strength,
			&i.Source,
			&i.State,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, cluster_id, node_id, name, kind, unit, port, address, description, source, state, last_seen_at, created_at, updated_at, status, status_reason, impact, impact_reason, impact_cause_id, impact_since FROM services ORDER BY lower(name), id
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.NodeID,
			&i.Name,
			&i.Kind,
			&i.Unit,
			&i.Port,
			&i.Address,
			&i.Description,
			&i.Source,
			&i.State,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.StatusReason,
			&i.Impact,
			&i.ImpactReason,
			&i.ImpactCauseID,
			&i.ImpactSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockService = `-- name: LockService :one
SELECT id, cluster_id, node_id, name, kind, unit, port, address, description, source, state, last_seen_at, created_at, updated_at, status, status_reason, impact, impact_reason, impact_cause_id, impact_since FROM services WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockService(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, lockService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.Name,
		&i.Kind,
		&i.Unit,
		&i.Port,
		&i.Address,
		&i.Description,
		&i.Source,
		&i.State,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.Impact,
		&i.ImpactReason,
		&i.ImpactCauseID,
		&i.ImpactSince,
	)
	return i, err
}

const lockServiceDependency = `-- name: LockServiceDependency :one
SELECT id, from_service_id, to_service_id, strength, source, state, note, created_at, updated_at FROM service_dependencies WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockServiceDependency(ctx context.Context, id uuid.UUID) (ServiceDependency, error) {
	row := q.db.QueryRow(ctx, lockServiceDependency, id)
	var i ServiceDependency
	err := row.Scan(
		&i.ID,
		&i.FromServiceID,
		&i.ToServiceID,
		&i.Strength,
		&i.Source,
		&i.State,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setServiceStatus = `-- name: SetServiceStatus :exec
UPDATE services
SET status = $1, status_reason = $2, impact = $3, impact_reason = $4,
    impact_cause_id = $5, impact_since = $6
WHERE id = $7
`

type SetServiceStatusParams struct {
	Status        *string
	StatusReason  string
	Impact        string
	ImpactReason  string
	ImpactCauseID *uuid.UUID
	ImpactSince   *time.Time
	ID            uuid.UUID
}

// deps.Evaluate schrijft de status en impact; updated_at blijft staan, want
// die zegt wanneer iemand de dienst wijzigde.
func (q *Queries) SetServiceStatus(ctx context.Context, arg SetServiceStatusParams) error {
	_, err := q.db.Exec(ctx, setServiceStatus,
		arg.Status,
		arg.StatusReason,
		arg.Impact,
		arg.ImpactReason,
		arg.ImpactCauseID,
		arg.ImpactSince,
		arg.ID,
	)
	return err
}

const touchServices = `-- name: TouchServices :exec
UPDATE services SET last_seen_at = $1
WHERE cluster_id = $2 AND unit = ANY($3::text[])
`

type TouchServicesParams struct {
	SeenAt    *time.Time
	ClusterID *uuid.UUID
	Units     []string
}

// De resolver zag deze units nog; de staat van de rijen blijft wat ze was.
func (q *Queries) TouchServices(ctx context.Context, arg TouchServicesParams) error {
	_, err := q.db.Exec(ctx, touchServices, arg.SeenAt, arg.ClusterID, arg.Units)
	return err
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = $1, kind = $2, unit = $3, port = $4, address = $5, description = $6,
    source = $7, state = $8, updated_at = now()
WHERE id = $9
RETURNING id, cluster_id, node_id, name, kind, unit, port, address, description, source, state, last_seen_at, created_at, updated_at, status, status_reason, impact, impact_reason, impact_cause_id, impact_since
`

type UpdateServiceParams struct {
	Name        string
	Kind        string
	Unit        string
	Port        *int32
	Address     string
	Description string
	Source      string
	State       string
	ID          uuid.UUID
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.Name,
		arg.Kind,
		arg.Unit,
		arg.Port,
		arg.Address,
		arg.Description,
		arg.Source,
		arg.State,
		arg.ID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.Name,
		&i.Kind,
		&i.Unit,
		&i.Port,
		&i.Address,
		&i.Description,
		&i.Source,
		&i.State,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.Impact,
		&i.ImpactReason,
		&i.ImpactCauseID,
		&i.ImpactSince,
	)
	return i, err
}

const updateServiceDependency = `-- name: UpdateServiceDependency :one
UPDATE service_dependencies SET strength = $1, note = $2, updated_at = now()
WHERE id = $3
RETURNING id, from_service_id, to_service_id, strength, source, state, note, created_at, updated_at
`

type UpdateServiceDependencyParams struct {
	Strength string
	Note     string
	ID       uuid.UUID
}

func (q *Queries) UpdateServiceDependency(ctx context.Context, arg UpdateServiceDependencyParams) (ServiceDependency, error) {
	row := q.db.QueryRow(ctx, updateServiceDependency, arg.Strength, arg.Note, arg.ID)
	var i ServiceDependency
	err := row.Scan(
		&i.ID,
		&i.FromServiceID,
		&i.ToServiceID,
		&i.Strength,
		&i.Source,
		&i.State,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
