// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: drift.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getDriftCheck = `-- name: GetDriftCheck :one
SELECT node_id, status, source, spec_revision, template_version, findings, unchecked, fingerprint, error, checked_at, drift_since FROM drift_checks WHERE node_id = $1
`

func (q *Queries) GetDriftCheck(ctx context.Context, nodeID uuid.UUID) (DriftCheck, error) {
	row := q.db.QueryRow(ctx, getDriftCheck, nodeID)
	var i DriftCheck
	err := row.Scan(
		&i.NodeID,
		&i.Status,
		&i.Source,
		&i.SpecRevision,
		&i.TemplateVersion,
		&i.Findings,
		&i.Unchecked,
		&i.Fingerprint,
		&i.Error,
		&i.CheckedAt,
		&i.DriftSince,
	)
	return i, err
}

const listClusterDriftChecks = `-- name: ListClusterDriftChecks :many
SELECT d.node_id, d.status, d.source, d.spec_revision, d.template_version, d.findings, d.unchecked, d.fingerprint, d.error, d.checked_at, d.drift_since FROM drift_checks d JOIN nodes n ON n.id = d.node_id WHERE n.cluster_id = $1
`

func (q *Queries) ListClusterDriftChecks(ctx context.Context, clusterID *uuid.UUID) ([]DriftCheck, error) {
	rows, err := q.db.Query(ctx, listClusterDriftChecks, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriftCheck{}
	for rows.Next() {
		var i DriftCheck
		if err := rows.Scan(
			&i.NodeID,
			&i.Status,
			&i.Source,
			&i.SpecRevision,
			&i.TemplateVersion,
			&i.Findings,
			&i.Unchecked,
			&i.Fingerprint,
			&i.Error,
			&i.CheckedAt,
			&i.DriftSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriftNodes = `-- name: ListDriftNodes :many
SELECT n.id, n.hostname, n.cluster_id, n.lifecycle,
       coalesce(a.protocol_version, 0)::int AS agent_protocol,
       (a.id IS NOT NULL)::boolean AS has_agent,
       s.heartbeat_at
FROM nodes n
JOIN clusters c ON c.id = n.cluster_id AND c.template_name IS NOT NULL
LEFT JOIN agents a ON a.node_id = n.id AND a.revoked_at IS NULL
LEFT JOIN node_status s ON s.node_id = n.id
WHERE ($1::uuid IS NULL OR n.cluster_id = $1)
  AND ($2::uuid IS NULL OR n.id = $2)
ORDER BY n.hostname
`

type ListDriftNodesParams struct {
	ClusterID *uuid.UUID
	NodeID    *uuid.UUID
}

type ListDriftNodesRow struct {
	ID            uuid.UUID
	Hostname      string
	ClusterID     *uuid.UUID
	Lifecycle     NodeLifecycle
	AgentProtocol int32
	HasAgent      bool
	HeartbeatAt   *time.Time
}

// De nodes van clusters met een gewenste staat, met wat de scanner moet
// weten om te beslissen of hij ze controleert. Zonder cluster_id alle.
func (q *Queries) ListDriftNodes(ctx context.Context, arg ListDriftNodesParams) ([]ListDriftNodesRow, error) {
	rows, err := q.db.Query(ctx, listDriftNodes, arg.ClusterID, arg.NodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDriftNodesRow{}
	for rows.Next() {
		var i ListDriftNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.ClusterID,
			&i.Lifecycle,
			&i.AgentProtocol,
			&i.HasAgent,
			&i.HeartbeatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDriftNode = `-- name: LockDriftNode :exec
SELECT pg_advisory_xact_lock(hashtextextended('drift:' || $1::text, 0))
`

// Eén schrijver per node, zoals de evaluator, zodat er nooit een dubbel
// event komt.
func (q *Queries) LockDriftNode(ctx context.Context, nodeID string) error {
	_, err := q.db.Exec(ctx, lockDriftNode, nodeID)
	return err
}

const nodeJobBusy = `-- name: NodeJobBusy :one
SELECT EXISTS (
    SELECT 1 FROM jobs
    WHERE status IN ('queued', 'running')
      AND (node_id = $1 OR (cluster_slot AND cluster_id = $2::uuid))
)::boolean
`

type NodeJobBusyParams struct {
	NodeID    *uuid.UUID
	ClusterID *uuid.UUID
}

// Er wacht of loopt een taak op deze node, of een schrijvende taak in zijn
// cluster. De agent doet één commando tegelijk; een controle wacht niet.
func (q *Queries) NodeJobBusy(ctx context.Context, arg NodeJobBusyParams) (bool, error) {
	row := q.db.QueryRow(ctx, nodeJobBusy, arg.NodeID, arg.ClusterID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertDriftCheck = `-- name: UpsertDriftCheck :exec
INSERT INTO drift_checks (node_id, status, source, spec_revision, template_version, findings, unchecked,
                          fingerprint, error, checked_at, drift_since)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11)
ON CONFLICT (node_id) DO UPDATE
SET status = EXCLUDED.status, source = EXCLUDED.source, spec_revision = EXCLUDED.spec_revision,
    template_version = EXCLUDED.template_version, findings = EXCLUDED.findings, unchecked = EXCLUDED.unchecked,
    fingerprint = EXCLUDED.fingerprint, error = EXCLUDED.error, checked_at = EXCLUDED.checked_at,
    drift_since = EXCLUDED.drift_since
`

type UpsertDriftCheckParams struct {
	NodeID          uuid.UUID
	Status          string
	Source          string
	SpecRevision    int32
	TemplateVersion string
	Findings        []byte
	Unchecked       []byte
	Fingerprint     string
	Error           string
	CheckedAt       time.Time
	DriftSince      *time.Time
}

func (q *Queries) UpsertDriftCheck(ctx context.Context, arg UpsertDriftCheckParams) error {
	_, err := q.db.Exec(ctx, upsertDriftCheck,
		arg.NodeID,
		arg.Status,
		arg.Source,
		arg.SpecRevision,
		arg.TemplateVersion,
		arg.Findings,
		arg.Unchecked,
		arg.Fingerprint,
		arg.Error,
		arg.CheckedAt,
		arg.DriftSince,
	)
	return err
}
