// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (actor_type, actor_id, subject_type, subject_id, cluster_id, action, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEventParams struct {
	ActorType   ActorType
	ActorID     string
	SubjectType string
	SubjectID   string
	ClusterID   *uuid.UUID
	Action      string
	Payload     []byte
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ActorType,
		arg.ActorID,
		arg.SubjectType,
		arg.SubjectID,
		arg.ClusterID,
		arg.Action,
		arg.Payload,
	)
	return err
}

const listRecentEvents = `-- name: ListRecentEvents :many
SELECT id, ts, actor_type, actor_id, subject_type, subject_id, cluster_id, action, payload FROM events ORDER BY id DESC LIMIT $1
`

func (q *Queries) ListRecentEvents(ctx context.Context, limit int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, listRecentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.ActorType,
			&i.ActorID,
			&i.SubjectType,
			&i.SubjectID,
			&i.ClusterID,
			&i.Action,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
