// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: failover.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const deleteFailoverTest = `-- name: DeleteFailoverTest :execrows
DELETE FROM failover_tests WHERE id = $1
`

func (q *Queries) DeleteFailoverTest(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFailoverTest, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishTestRun = `-- name: FinishTestRun :one
UPDATE test_runs
SET result = $1, restored = $2, summary = $3, checks = $4,
    timeline = $5, measurements = $6, finished_at = now()
WHERE id = $7 AND result IS NULL
RETURNING id, kind, trigger, cluster_id, test_id, node_id, hostname, job_id, definition, result, restored, summary, checks, timeline, measurements, requested_by, created_at, finished_at
`

type FinishTestRunParams struct {
	Result       *string
	Restored     *bool
	Summary      string
	Checks       []byte
	Timeline     []byte
	Measurements []byte
	ID           uuid.UUID
}

// Rondt een run af; een run met een resultaat blijft zoals hij is.
func (q *Queries) FinishTestRun(ctx context.Context, arg FinishTestRunParams) (TestRun, error) {
	row := q.db.QueryRow(ctx, finishTestRun,
		arg.Result,
		arg.Restored,
		arg.Summary,
		arg.Checks,
		arg.Timeline,
		arg.Measurements,
		arg.ID,
	)
	var i TestRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Trigger,
		&i.ClusterID,
		&i.TestID,
		&i.NodeID,
		&i.Hostname,
		&i.JobID,
		&i.Definition,
		&i.Result,
		&i.Restored,
		&i.Summary,
		&i.Checks,
		&i.Timeline,
		&i.Measurements,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getFailoverTest = `-- name: GetFailoverTest :one
SELECT t.id, t.cluster_id, t.vip_id, t.name, t.scenario, t.service, t.max_takeover_seconds, t.expect_failback, t.probe, t.created_by, t.created_at, t.updated_at, t.scheduled, t.next_run_at, v.address AS vip_address
FROM failover_tests t
JOIN vips v ON v.id = t.vip_id
WHERE t.id = $1
`

type GetFailoverTestRow struct {
	FailoverTest FailoverTest
	VipAddress   netip.Addr
}

func (q *Queries) GetFailoverTest(ctx context.Context, id uuid.UUID) (GetFailoverTestRow, error) {
	row := q.db.QueryRow(ctx, getFailoverTest, id)
	var i GetFailoverTestRow
	err := row.Scan(
		&i.FailoverTest.ID,
		&i.FailoverTest.ClusterID,
		&i.FailoverTest.VipID,
		&i.FailoverTest.Name,
		&i.FailoverTest.Scenario,
		&i.FailoverTest.Service,
		&i.FailoverTest.MaxTakeoverSeconds,
		&i.FailoverTest.ExpectFailback,
		&i.FailoverTest.Probe,
		&i.FailoverTest.CreatedBy,
		&i.FailoverTest.CreatedAt,
		&i.FailoverTest.UpdatedAt,
		&i.FailoverTest.Scheduled,
		&i.FailoverTest.NextRunAt,
		&i.VipAddress,
	)
	return i, err
}

const getTestRun = `-- name: GetTestRun :one
SELECT r.id, r.kind, r.trigger, r.cluster_id, r.test_id, r.node_id, r.hostname, r.job_id, r.definition, r.result, r.restored, r.summary, r.checks, r.timeline, r.measurements, r.requested_by, r.created_at, r.finished_at, j.status AS job_status, u.username AS requested_by_name, c.name AS cluster_name
FROM test_runs r
LEFT JOIN jobs j ON j.id = r.job_id
LEFT JOIN users u ON u.id = r.requested_by
LEFT JOIN clusters c ON c.id = r.cluster_id
WHERE r.id = $1
`

type GetTestRunRow struct {
	TestRun         TestRun
	JobStatus       NullJobStatus
	RequestedByName *string
	ClusterName     *string
}

func (q *Queries) GetTestRun(ctx context.Context, id uuid.UUID) (GetTestRunRow, error) {
	row := q.db.QueryRow(ctx, getTestRun, id)
	var i GetTestRunRow
	err := row.Scan(
		&i.TestRun.ID,
		&i.TestRun.Kind,
		&i.TestRun.Trigger,
		&i.TestRun.ClusterID,
		&i.TestRun.TestID,
		&i.TestRun.NodeID,
		&i.TestRun.Hostname,
		&i.TestRun.JobID,
		&i.TestRun.Definition,
		&i.TestRun.Result,
		&i.TestRun.Restored,
		&i.TestRun.Summary,
		&i.TestRun.Checks,
		&i.TestRun.Timeline,
		&i.TestRun.Measurements,
		&i.TestRun.RequestedBy,
		&i.TestRun.CreatedAt,
		&i.TestRun.FinishedAt,
		&i.JobStatus,
		&i.RequestedByName,
		&i.ClusterName,
	)
	return i, err
}

const getTestRunByJob = `-- name: GetTestRunByJob :one
SELECT id, kind, trigger, cluster_id, test_id, node_id, hostname, job_id, definition, result, restored, summary, checks, timeline, measurements, requested_by, created_at, finished_at FROM test_runs WHERE job_id = $1
`

func (q *Queries) GetTestRunByJob(ctx context.Context, jobID *uuid.UUID) (TestRun, error) {
	row := q.db.QueryRow(ctx, getTestRunByJob, jobID)
	var i TestRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Trigger,
		&i.ClusterID,
		&i.TestID,
		&i.NodeID,
		&i.Hostname,
		&i.JobID,
		&i.Definition,
		&i.Result,
		&i.Restored,
		&i.Summary,
		&i.Checks,
		&i.Timeline,
		&i.Measurements,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getTestSlotJob = `-- name: GetTestSlotJob :one
SELECT id, title FROM jobs
WHERE kind IN ('backup.verify', 'failover.test') AND status IN ('queued', 'running')
ORDER BY created_at LIMIT 1
`

type GetTestSlotJobRow struct {
	ID    uuid.UUID
	Title string
}

// De invasieve test die nu wacht of loopt, over heel ClusterForge.
func (q *Queries) GetTestSlotJob(ctx context.Context) (GetTestSlotJobRow, error) {
	row := q.db.QueryRow(ctx, getTestSlotJob)
	var i GetTestSlotJobRow
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const getTestSlotReleasedAt = `-- name: GetTestSlotReleasedAt :one
SELECT coalesce(max(finished_at), 'epoch'::timestamptz)::timestamptz AS released_at FROM jobs
WHERE kind IN ('backup.verify', 'failover.test') AND status NOT IN ('queued', 'running')
`

// Wanneer de laatste invasieve test klaar was; een geplande run die daarop
// wachtte, is niet te laat.
func (q *Queries) GetTestSlotReleasedAt(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, getTestSlotReleasedAt)
	var released_at time.Time
	err := row.Scan(&released_at)
	return released_at, err
}

const insertFailoverTest = `-- name: InsertFailoverTest :one
INSERT INTO failover_tests (cluster_id, vip_id, name, scenario, service, max_takeover_seconds, expect_failback, probe, created_by,
                            scheduled, next_run_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11)
RETURNING id, cluster_id, vip_id, name, scenario, service, max_takeover_seconds, expect_failback, probe, created_by, created_at, updated_at, scheduled, next_run_at
`

type InsertFailoverTestParams struct {
	ClusterID          uuid.UUID
	VipID              uuid.UUID
	Name               string
	Scenario           string
	Service            string
	MaxTakeoverSeconds int32
	ExpectFailback     bool
	Probe              []byte
	CreatedBy          *uuid.UUID
	Scheduled          bool
	NextRunAt          *time.Time
}

func (q *Queries) InsertFailoverTest(ctx context.Context, arg InsertFailoverTestParams) (FailoverTest, error) {
	row := q.db.QueryRow(ctx, insertFailoverTest,
		arg.ClusterID,
		arg.VipID,
		arg.Name,
		arg.Scenario,
		arg.Service,
		arg.MaxTakeoverSeconds,
		arg.ExpectFailback,
		arg.Probe,
		arg.CreatedBy,
		arg.Scheduled,
		arg.NextRunAt,
	)
	var i FailoverTest
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.VipID,
		&i.Name,
		&i.Scenario,
		&i.Service,
		&i.MaxTakeoverSeconds,
		&i.ExpectFailback,
		&i.Probe,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scheduled,
		&i.NextRunAt,
	)
	return i, err
}

const insertTestRun = `-- name: InsertTestRun :one
INSERT INTO test_runs (kind, trigger, cluster_id, test_id, node_id, hostname, job_id, definition, checks, requested_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, kind, trigger, cluster_id, test_id, node_id, hostname, job_id, definition, result, restored, summary, checks, timeline, measurements, requested_by, created_at, finished_at
`

type InsertTestRunParams struct {
	Kind        string
	Trigger     string
	ClusterID   *uuid.UUID
	TestID      *uuid.UUID
	NodeID      *uuid.UUID
	Hostname    string
	JobID       *uuid.UUID
	Definition  []byte
	Checks      []byte
	RequestedBy *uuid.UUID
}

func (q *Queries) InsertTestRun(ctx context.Context, arg InsertTestRunParams) (TestRun, error) {
	row := q.db.QueryRow(ctx, insertTestRun,
		arg.Kind,
		arg.Trigger,
		arg.ClusterID,
		arg.TestID,
		arg.NodeID,
		arg.Hostname,
		arg.JobID,
		arg.Definition,
		arg.Checks,
		arg.RequestedBy,
	)
	var i TestRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Trigger,
		&i.ClusterID,
		&i.TestID,
		&i.NodeID,
		&i.Hostname,
		&i.JobID,
		&i.Definition,
		&i.Result,
		&i.Restored,
		&i.Summary,
		&i.Checks,
		&i.Timeline,
		&i.Measurements,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const lastTestedAt = `-- name: LastTestedAt :one
SELECT coalesce(max(finished_at), 'epoch'::timestamptz)::timestamptz AS tested_at FROM test_runs
WHERE cluster_id = $1 AND kind = $2 AND result = ANY($3::text[])
`

type LastTestedAtParams struct {
	ClusterID *uuid.UUID
	Kind      string
	Results   []string
}

// Wanneer een cluster het laatst echt getest of gecontroleerd is; epoch als
// nooit.
func (q *Queries) LastTestedAt(ctx context.Context, arg LastTestedAtParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, lastTestedAt, arg.ClusterID, arg.Kind, arg.Results)
	var tested_at time.Time
	err := row.Scan(&tested_at)
	return tested_at, err
}

const latestTestRuns = `-- name: LatestTestRuns :many
SELECT DISTINCT ON (r.test_id) r.id, r.kind, r.trigger, r.cluster_id, r.test_id, r.node_id, r.hostname, r.job_id, r.definition, r.result, r.restored, r.summary, r.checks, r.timeline, r.measurements, r.requested_by, r.created_at, r.finished_at, j.status AS job_status
FROM test_runs r
LEFT JOIN jobs j ON j.id = r.job_id
WHERE r.cluster_id = $1 AND r.test_id IS NOT NULL
ORDER BY r.test_id, r.created_at DESC
`

type LatestTestRunsRow struct {
	TestRun   TestRun
	JobStatus NullJobStatus
}

// De laatste run per test van een cluster.
func (q *Queries) LatestTestRuns(ctx context.Context, clusterID *uuid.UUID) ([]LatestTestRunsRow, error) {
	rows, err := q.db.Query(ctx, latestTestRuns, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestTestRunsRow{}
	for rows.Next() {
		var i LatestTestRunsRow
		if err := rows.Scan(
			&i.TestRun.ID,
			&i.TestRun.Kind,
			&i.TestRun.Trigger,
			&i.TestRun.ClusterID,
			&i.TestRun.TestID,
			&i.TestRun.NodeID,
			&i.TestRun.Hostname,
			&i.TestRun.JobID,
			&i.TestRun.Definition,
			&i.TestRun.Result,
			&i.TestRun.Restored,
			&i.TestRun.Summary,
			&i.TestRun.Checks,
			&i.TestRun.Timeline,
			&i.TestRun.Measurements,
			&i.TestRun.RequestedBy,
			&i.TestRun.CreatedAt,
			&i.TestRun.FinishedAt,
			&i.JobStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueFailoverTests = `-- name: ListDueFailoverTests :many
SELECT t.id, t.cluster_id, t.vip_id, t.name, t.scenario, t.service, t.max_takeover_seconds, t.expect_failback, t.probe, t.created_by, t.created_at, t.updated_at, t.scheduled, t.next_run_at, v.address AS vip_address
FROM failover_tests t
JOIN vips v ON v.id = t.vip_id
WHERE t.scheduled AND t.next_run_at <= $1
ORDER BY t.next_run_at, t.created_at
`

type ListDueFailoverTestsRow struct {
	FailoverTest FailoverTest
	VipAddress   netip.Addr
}

// Geplande tests waarvan het moment voorbij is, oudste eerst.
func (q *Queries) ListDueFailoverTests(ctx context.Context, now *time.Time) ([]ListDueFailoverTestsRow, error) {
	rows, err := q.db.Query(ctx, listDueFailoverTests, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueFailoverTestsRow{}
	for rows.Next() {
		var i ListDueFailoverTestsRow
		if err := rows.Scan(
			&i.FailoverTest.ID,
			&i.FailoverTest.ClusterID,
			&i.FailoverTest.VipID,
			&i.FailoverTest.Name,
			&i.FailoverTest.Scenario,
			&i.FailoverTest.Service,
			&i.FailoverTest.MaxTakeoverSeconds,
			&i.FailoverTest.ExpectFailback,
			&i.FailoverTest.Probe,
			&i.FailoverTest.CreatedBy,
			&i.FailoverTest.CreatedAt,
			&i.FailoverTest.UpdatedAt,
			&i.FailoverTest.Scheduled,
			&i.FailoverTest.NextRunAt,
			&i.VipAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailoverNodes = `-- name: ListFailoverNodes :many
SELECT n.id, n.hostname, n.lifecycle, n.status, n.proxmox_id, n.pve_vmid,
       (a.id IS NOT NULL)::boolean AS has_agent,
       coalesce(a.protocol_version, 0)::int AS agent_protocol,
       s.heartbeat_at,
       coalesce(s.addresses, '{}')::text[] AS addresses,
       coalesce(s.services, '{}'::jsonb)::jsonb AS services,
       coalesce(f.facts -> 'keepalived' -> 'vips', '[]'::jsonb)::jsonb AS keepalived_vips
FROM nodes n
LEFT JOIN agents a ON a.node_id = n.id AND a.revoked_at IS NULL
LEFT JOIN node_status s ON s.node_id = n.id AND a.id IS NOT NULL
LEFT JOIN node_facts f ON f.node_id = n.id AND a.id IS NOT NULL
WHERE n.cluster_id = $1
ORDER BY n.hostname
`

type ListFailoverNodesRow struct {
	ID             uuid.UUID
	Hostname       string
	Lifecycle      NodeLifecycle
	Status         string
	ProxmoxID      *uuid.UUID
	PveVmid        *int32
	HasAgent       bool
	AgentProtocol  int32
	HeartbeatAt    *time.Time
	Addresses      []string
	Services       []byte
	KeepalivedVips []byte
}

// Wat de voorcontrole van een failovertest per node moet weten, uit de
// laatste heartbeat en facts.
func (q *Queries) ListFailoverNodes(ctx context.Context, clusterID *uuid.UUID) ([]ListFailoverNodesRow, error) {
	rows, err := q.db.Query(ctx, listFailoverNodes, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFailoverNodesRow{}
	for rows.Next() {
		var i ListFailoverNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.Lifecycle,
			&i.Status,
			&i.ProxmoxID,
			&i.PveVmid,
			&i.HasAgent,
			&i.AgentProtocol,
			&i.HeartbeatAt,
			&i.Addresses,
			&i.Services,
			&i.KeepalivedVips,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailoverTests = `-- name: ListFailoverTests :many
SELECT t.id, t.cluster_id, t.vip_id, t.name, t.scenario, t.service, t.max_takeover_seconds, t.expect_failback, t.probe, t.created_by, t.created_at, t.updated_at, t.scheduled, t.next_run_at, v.address AS vip_address, v.owner_node_id AS vip_owner_id, o.hostname AS vip_owner_hostname
FROM failover_tests t
JOIN vips v ON v.id = t.vip_id
LEFT JOIN nodes o ON o.id = v.owner_node_id
WHERE t.cluster_id = $1
ORDER BY t.created_at
`

type ListFailoverTestsRow struct {
	FailoverTest     FailoverTest
	VipAddress       netip.Addr
	VipOwnerID       *uuid.UUID
	VipOwnerHostname *string
}

func (q *Queries) ListFailoverTests(ctx context.Context, clusterID uuid.UUID) ([]ListFailoverTestsRow, error) {
	rows, err := q.db.Query(ctx, listFailoverTests, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFailoverTestsRow{}
	for rows.Next() {
		var i ListFailoverTestsRow
		if err := rows.Scan(
			&i.FailoverTest.ID,
			&i.FailoverTest.ClusterID,
			&i.FailoverTest.VipID,
			&i.FailoverTest.Name,
			&i.FailoverTest.Scenario,
			&i.FailoverTest.Service,
			&i.FailoverTest.MaxTakeoverSeconds,
			&i.FailoverTest.ExpectFailback,
			&i.FailoverTest.Probe,
			&i.FailoverTest.CreatedBy,
			&i.FailoverTest.CreatedAt,
			&i.FailoverTest.UpdatedAt,
			&i.FailoverTest.Scheduled,
			&i.FailoverTest.NextRunAt,
			&i.VipAddress,
			&i.VipOwnerID,
			&i.VipOwnerHostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestRuns = `-- name: ListTestRuns :many
SELECT r.id, r.kind, r.trigger, r.cluster_id, r.test_id, r.node_id, r.hostname, r.job_id, r.definition, r.result, r.restored, r.summary, r.checks, r.timeline, r.measurements, r.requested_by, r.created_at, r.finished_at, j.status AS job_status, u.username AS requested_by_name
FROM test_runs r
LEFT JOIN jobs j ON j.id = r.job_id
LEFT JOIN users u ON u.id = r.requested_by
WHERE r.test_id = $1
ORDER BY r.created_at DESC
LIMIT $2
`

type ListTestRunsParams struct {
	TestID *uuid.UUID
	Lim    int32
}

type ListTestRunsRow struct {
	TestRun         TestRun
	JobStatus       NullJobStatus
	RequestedByName *string
}

// De runs van één test, nieuwste eerst.
func (q *Queries) ListTestRuns(ctx context.Context, arg ListTestRunsParams) ([]ListTestRunsRow, error) {
	rows, err := q.db.Query(ctx, listTestRuns, arg.TestID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestRunsRow{}
	for rows.Next() {
		var i ListTestRunsRow
		if err := rows.Scan(
			&i.TestRun.ID,
			&i.TestRun.Kind,
			&i.TestRun.Trigger,
			&i.TestRun.ClusterID,
			&i.TestRun.TestID,
			&i.TestRun.NodeID,
			&i.TestRun.Hostname,
			&i.TestRun.JobID,
			&i.TestRun.Definition,
			&i.TestRun.Result,
			&i.TestRun.Restored,
			&i.TestRun.Summary,
			&i.TestRun.Checks,
			&i.TestRun.Timeline,
			&i.TestRun.Measurements,
			&i.TestRun.RequestedBy,
			&i.TestRun.CreatedAt,
			&i.TestRun.FinishedAt,
			&i.JobStatus,
			&i.RequestedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnrestoredRuns = `-- name: ListUnrestoredRuns :many
SELECT id, kind, trigger, cluster_id, test_id, node_id, hostname, job_id, definition, result, restored, summary, checks, timeline, measurements, requested_by, created_at, finished_at FROM test_runs
WHERE cluster_id = $1 AND restored = false
ORDER BY created_at DESC
`

// Runs waarvan het herstel niet lukte; ze geven een rode balk bij het
// cluster tot iemand ze opnieuw herstelt.
func (q *Queries) ListUnrestoredRuns(ctx context.Context, clusterID *uuid.UUID) ([]TestRun, error) {
	rows, err := q.db.Query(ctx, listUnrestoredRuns, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestRun{}
	for rows.Next() {
		var i TestRun
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Trigger,
			&i.ClusterID,
			&i.TestID,
			&i.NodeID,
			&i.Hostname,
			&i.JobID,
			&i.Definition,
			&i.Result,
			&i.Restored,
			&i.Summary,
			&i.Checks,
			&i.Timeline,
			&i.Measurements,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFailoverTestNextRun = `-- name: SetFailoverTestNextRun :exec
UPDATE failover_tests SET scheduled = $1, next_run_at = $2 WHERE id = $3
`

type SetFailoverTestNextRunParams struct {
	Scheduled bool
	NextRunAt *time.Time
	ID        uuid.UUID
}

// Na een geplande run of een overgeslagen run: het volgende venster, of de
// planning uit.
func (q *Queries) SetFailoverTestNextRun(ctx context.Context, arg SetFailoverTestNextRunParams) error {
	_, err := q.db.Exec(ctx, setFailoverTestNextRun, arg.Scheduled, arg.NextRunAt, arg.ID)
	return err
}

const setTestRunChecks = `-- name: SetTestRunChecks :exec
UPDATE test_runs SET checks = $1 WHERE id = $2
`

type SetTestRunChecksParams struct {
	Checks []byte
	ID     uuid.UUID
}

func (q *Queries) SetTestRunChecks(ctx context.Context, arg SetTestRunChecksParams) error {
	_, err := q.db.Exec(ctx, setTestRunChecks, arg.Checks, arg.ID)
	return err
}

const setTestRunJob = `-- name: SetTestRunJob :exec
UPDATE test_runs SET job_id = $1 WHERE id = $2
`

type SetTestRunJobParams struct {
	JobID *uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) SetTestRunJob(ctx context.Context, arg SetTestRunJobParams) error {
	_, err := q.db.Exec(ctx, setTestRunJob, arg.JobID, arg.ID)
	return err
}

const setTestRunRestored = `-- name: SetTestRunRestored :exec
UPDATE test_runs SET restored = true, summary = $1 WHERE id = $2
`

type SetTestRunRestoredParams struct {
	Summary string
	ID      uuid.UUID
}

func (q *Queries) SetTestRunRestored(ctx context.Context, arg SetTestRunRestoredParams) error {
	_, err := q.db.Exec(ctx, setTestRunRestored, arg.Summary, arg.ID)
	return err
}

const updateFailoverTest = `-- name: UpdateFailoverTest :one
UPDATE failover_tests
SET vip_id = $1, name = $2, scenario = $3, service = $4,
    max_takeover_seconds = $5, expect_failback = $6, probe = $7,
    scheduled = $8, next_run_at = $9, updated_at = now()
WHERE id = $10
RETURNING id, cluster_id, vip_id, name, scenario, service, max_takeover_seconds, expect_failback, probe, created_by, created_at, updated_at, scheduled, next_run_at
`

type UpdateFailoverTestParams struct {
	VipID              uuid.UUID
	Name               string
	Scenario           string
	Service            string
	MaxTakeoverSeconds int32
	ExpectFailback     bool
	Probe              []byte
	Scheduled          bool
	NextRunAt          *time.Time
	ID                 uuid.UUID
}

func (q *Queries) UpdateFailoverTest(ctx context.Context, arg UpdateFailoverTestParams) (FailoverTest, error) {
	row := q.db.QueryRow(ctx, updateFailoverTest,
		arg.VipID,
		arg.Name,
		arg.Scenario,
		arg.Service,
		arg.MaxTakeoverSeconds,
		arg.ExpectFailback,
		arg.Probe,
		arg.Scheduled,
		arg.NextRunAt,
		arg.ID,
	)
	var i FailoverTest
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.VipID,
		&i.Name,
		&i.Scenario,
		&i.Service,
		&i.MaxTakeoverSeconds,
		&i.ExpectFailback,
		&i.Probe,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scheduled,
		&i.NextRunAt,
	)
	return i, err
}
