// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: gitops.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPendingGitChanges = `-- name: CountPendingGitChanges :one
SELECT count(*)::int FROM git_changes WHERE status = 'pending'
`

func (q *Queries) CountPendingGitChanges(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingGitChanges)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createGitRepo = `-- name: CreateGitRepo :one
INSERT INTO git_repos (id, api_url, owner, name, branch, path, token_enc, key_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, api_url, owner, name, branch, path, token_enc, key_id, head_sha, head_etag, synced_sha, head_commit, scan, last_sync_at, last_error, created_at, updated_at
`

type CreateGitRepoParams struct {
	ID       uuid.UUID
	ApiUrl   string
	Owner    string
	Name     string
	Branch   string
	Path     string
	TokenEnc []byte
	KeyID    string
}

func (q *Queries) CreateGitRepo(ctx context.Context, arg CreateGitRepoParams) (GitRepo, error) {
	row := q.db.QueryRow(ctx, createGitRepo,
		arg.ID,
		arg.ApiUrl,
		arg.Owner,
		arg.Name,
		arg.Branch,
		arg.Path,
		arg.TokenEnc,
		arg.KeyID,
	)
	var i GitRepo
	err := row.Scan(
		&i.ID,
		&i.ApiUrl,
		&i.Owner,
		&i.Name,
		&i.Branch,
		&i.Path,
		&i.TokenEnc,
		&i.KeyID,
		&i.HeadSha,
		&i.HeadEtag,
		&i.SyncedSha,
		&i.HeadCommit,
		&i.Scan,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decideGitChange = `-- name: DecideGitChange :one
UPDATE git_changes
SET status = $1, revision = $2, job_id = $3, reason = $4,
    decided_by = $5, decided_at = now(), updated_at = now()
WHERE id = $6 AND status = 'pending'
RETURNING id, repo_id, cluster_id, slug, path, kind, commit_sha, commit_message, commit_author, commit_verified, commit_url, committed_at, blob_sha, base_revision, spec, metadata, plan, status, job_id, decided_by, decided_at, reason, created_at, updated_at, revision
`

type DecideGitChangeParams struct {
	Status    string
	Revision  *int32
	JobID     *uuid.UUID
	Reason    string
	DecidedBy *uuid.UUID
	ID        uuid.UUID
}

// Goedkeuren (applying met een taak, of meteen applied) of afwijzen.
func (q *Queries) DecideGitChange(ctx context.Context, arg DecideGitChangeParams) (GitChange, error) {
	row := q.db.QueryRow(ctx, decideGitChange,
		arg.Status,
		arg.Revision,
		arg.JobID,
		arg.Reason,
		arg.DecidedBy,
		arg.ID,
	)
	var i GitChange
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.ClusterID,
		&i.Slug,
		&i.Path,
		&i.Kind,
		&i.CommitSha,
		&i.CommitMessage,
		&i.CommitAuthor,
		&i.CommitVerified,
		&i.CommitUrl,
		&i.CommittedAt,
		&i.BlobSha,
		&i.BaseRevision,
		&i.Spec,
		&i.Metadata,
		&i.Plan,
		&i.Status,
		&i.JobID,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const deleteGitRepo = `-- name: DeleteGitRepo :execrows
DELETE FROM git_repos WHERE id = $1
`

func (q *Queries) DeleteGitRepo(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGitRepo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishGitChange = `-- name: FinishGitChange :one
UPDATE git_changes SET status = $1, reason = $2, updated_at = now()
WHERE job_id = $3 AND status = 'applying'
RETURNING id, repo_id, cluster_id, slug, path, kind, commit_sha, commit_message, commit_author, commit_verified, commit_url, committed_at, blob_sha, base_revision, spec, metadata, plan, status, job_id, decided_by, decided_at, reason, created_at, updated_at, revision
`

type FinishGitChangeParams struct {
	Status string
	Reason string
	JobID  *uuid.UUID
}

// Na de taak: applied of failed.
func (q *Queries) FinishGitChange(ctx context.Context, arg FinishGitChangeParams) (GitChange, error) {
	row := q.db.QueryRow(ctx, finishGitChange, arg.Status, arg.Reason, arg.JobID)
	var i GitChange
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.ClusterID,
		&i.Slug,
		&i.Path,
		&i.Kind,
		&i.CommitSha,
		&i.CommitMessage,
		&i.CommitAuthor,
		&i.CommitVerified,
		&i.CommitUrl,
		&i.CommittedAt,
		&i.BlobSha,
		&i.BaseRevision,
		&i.Spec,
		&i.Metadata,
		&i.Plan,
		&i.Status,
		&i.JobID,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const getGitChange = `-- name: GetGitChange :one
SELECT g.id, g.repo_id, g.cluster_id, g.slug, g.path, g.kind, g.commit_sha, g.commit_message, g.commit_author, g.commit_verified, g.commit_url, g.committed_at, g.blob_sha, g.base_revision, g.spec, g.metadata, g.plan, g.status, g.job_id, g.decided_by, g.decided_at, g.reason, g.created_at, g.updated_at, g.revision, c.name AS cluster_name, c.environment AS cluster_environment, u.username AS decided_by_name
FROM git_changes g
LEFT JOIN clusters c ON c.id = g.cluster_id
LEFT JOIN users u ON u.id = g.decided_by
WHERE g.id = $1
`

type GetGitChangeRow struct {
	ID                 uuid.UUID
	RepoID             uuid.UUID
	ClusterID          *uuid.UUID
	Slug               string
	Path               string
	Kind               string
	CommitSha          string
	CommitMessage      string
	CommitAuthor       string
	CommitVerified     bool
	CommitUrl          string
	CommittedAt        *time.Time
	BlobSha            string
	BaseRevision       int32
	Spec               []byte
	Metadata           []byte
	Plan               []byte
	Status             string
	JobID              *uuid.UUID
	DecidedBy          *uuid.UUID
	DecidedAt          *time.Time
	Reason             string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Revision           *int32
	ClusterName        *string
	ClusterEnvironment NullEnvironment
	DecidedByName      *string
}

func (q *Queries) GetGitChange(ctx context.Context, id uuid.UUID) (GetGitChangeRow, error) {
	row := q.db.QueryRow(ctx, getGitChange, id)
	var i GetGitChangeRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.ClusterID,
		&i.Slug,
		&i.Path,
		&i.Kind,
		&i.CommitSha,
		&i.CommitMessage,
		&i.CommitAuthor,
		&i.CommitVerified,
		&i.CommitUrl,
		&i.CommittedAt,
		&i.BlobSha,
		&i.BaseRevision,
		&i.Spec,
		&i.Metadata,
		&i.Plan,
		&i.Status,
		&i.JobID,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
		&i.ClusterName,
		&i.ClusterEnvironment,
		&i.DecidedByName,
	)
	return i, err
}

const getGitRepo = `-- name: GetGitRepo :one
SELECT id, api_url, owner, name, branch, path, token_enc, key_id, head_sha, head_etag, synced_sha, head_commit, scan, last_sync_at, last_error, created_at, updated_at FROM git_repos LIMIT 1
`

func (q *Queries) GetGitRepo(ctx context.Context) (GitRepo, error) {
	row := q.db.QueryRow(ctx, getGitRepo)
	var i GitRepo
	err := row.Scan(
		&i.ID,
		&i.ApiUrl,
		&i.Owner,
		&i.Name,
		&i.Branch,
		&i.Path,
		&i.TokenEnc,
		&i.KeyID,
		&i.HeadSha,
		&i.HeadEtag,
		&i.SyncedSha,
		&i.HeadCommit,
		&i.Scan,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingGitChange = `-- name: GetPendingGitChange :one
SELECT id, repo_id, cluster_id, slug, path, kind, commit_sha, commit_message, commit_author, commit_verified, commit_url, committed_at, blob_sha, base_revision, spec, metadata, plan, status, job_id, decided_by, decided_at, reason, created_at, updated_at, revision FROM git_changes WHERE slug = $1 AND status = 'pending'
`

func (q *Queries) GetPendingGitChange(ctx context.Context, slug string) (GitChange, error) {
	row := q.db.QueryRow(ctx, getPendingGitChange, slug)
	var i GitChange
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.ClusterID,
		&i.Slug,
		&i.Path,
		&i.Kind,
		&i.CommitSha,
		&i.CommitMessage,
		&i.CommitAuthor,
		&i.CommitVerified,
		&i.CommitUrl,
		&i.CommittedAt,
		&i.BlobSha,
		&i.BaseRevision,
		&i.Spec,
		&i.Metadata,
		&i.Plan,
		&i.Status,
		&i.JobID,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const insertGitChange = `-- name: InsertGitChange :one
INSERT INTO git_changes (repo_id, cluster_id, slug, path, kind, commit_sha, commit_message, commit_author,
                         commit_verified, commit_url, committed_at, blob_sha, base_revision, spec, metadata, plan)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, repo_id, cluster_id, slug, path, kind, commit_sha, commit_message, commit_author, commit_verified, commit_url, committed_at, blob_sha, base_revision, spec, metadata, plan, status, job_id, decided_by, decided_at, reason, created_at, updated_at, revision
`

type InsertGitChangeParams struct {
	RepoID         uuid.UUID
	ClusterID      *uuid.UUID
	Slug           string
	Path           string
	Kind           string
	CommitSha      string
	CommitMessage  string
	CommitAuthor   string
	CommitVerified bool
	CommitUrl      string
	CommittedAt    *time.Time
	BlobSha        string
	BaseRevision   int32
	Spec           []byte
	Metadata       []byte
	Plan           []byte
}

func (q *Queries) InsertGitChange(ctx context.Context, arg InsertGitChangeParams) (GitChange, error) {
	row := q.db.QueryRow(ctx, insertGitChange,
		arg.RepoID,
		arg.ClusterID,
		arg.Slug,
		arg.Path,
		arg.Kind,
		arg.CommitSha,
		arg.CommitMessage,
		arg.CommitAuthor,
		arg.CommitVerified,
		arg.CommitUrl,
		arg.CommittedAt,
		arg.BlobSha,
		arg.BaseRevision,
		arg.Spec,
		arg.Metadata,
		arg.Plan,
	)
	var i GitChange
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.ClusterID,
		&i.Slug,
		&i.Path,
		&i.Kind,
		&i.CommitSha,
		&i.CommitMessage,
		&i.CommitAuthor,
		&i.CommitVerified,
		&i.CommitUrl,
		&i.CommittedAt,
		&i.BlobSha,
		&i.BaseRevision,
		&i.Spec,
		&i.Metadata,
		&i.Plan,
		&i.Status,
		&i.JobID,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const listGitChanges = `-- name: ListGitChanges :many
SELECT g.id, g.repo_id, g.cluster_id, g.slug, g.path, g.kind, g.commit_sha, g.commit_message, g.commit_author, g.commit_verified, g.commit_url, g.committed_at, g.blob_sha, g.base_revision, g.spec, g.metadata, g.plan, g.status, g.job_id, g.decided_by, g.decided_at, g.reason, g.created_at, g.updated_at, g.revision, c.name AS cluster_name, c.environment AS cluster_environment, u.username AS decided_by_name
FROM git_changes g
LEFT JOIN clusters c ON c.id = g.cluster_id
LEFT JOIN users u ON u.id = g.decided_by
WHERE ($1::text IS NULL OR g.status = $1)
  AND ($2::uuid IS NULL OR g.cluster_id = $2)
ORDER BY (g.status IN ('pending', 'applying')) DESC, g.created_at DESC
LIMIT $3
`

type ListGitChangesParams struct {
	Status    *string
	ClusterID *uuid.UUID
	Max       int32
}

type ListGitChangesRow struct {
	ID                 uuid.UUID
	RepoID             uuid.UUID
	ClusterID          *uuid.UUID
	Slug               string
	Path               string
	Kind               string
	CommitSha          string
	CommitMessage      string
	CommitAuthor       string
	CommitVerified     bool
	CommitUrl          string
	CommittedAt        *time.Time
	BlobSha            string
	BaseRevision       int32
	Spec               []byte
	Metadata           []byte
	Plan               []byte
	Status             string
	JobID              *uuid.UUID
	DecidedBy          *uuid.UUID
	DecidedAt          *time.Time
	Reason             string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Revision           *int32
	ClusterName        *string
	ClusterEnvironment NullEnvironment
	DecidedByName      *string
}

// Eerst wat wacht of loopt, dan de rest van nieuw naar oud.
func (q *Queries) ListGitChanges(ctx context.Context, arg ListGitChangesParams) ([]ListGitChangesRow, error) {
	rows, err := q.db.Query(ctx, listGitChanges, arg.Status, arg.ClusterID, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGitChangesRow{}
	for rows.Next() {
		var i ListGitChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.ClusterID,
			&i.Slug,
			&i.Path,
			&i.Kind,
			&i.CommitSha,
			&i.CommitMessage,
			&i.CommitAuthor,
			&i.CommitVerified,
			&i.CommitUrl,
			&i.CommittedAt,
			&i.BlobSha,
			&i.BaseRevision,
			&i.Spec,
			&i.Metadata,
			&i.Plan,
			&i.Status,
			&i.JobID,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
			&i.ClusterName,
			&i.ClusterEnvironment,
			&i.DecidedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitClusters = `-- name: ListGitClusters :many
SELECT id, slug, name, description, environment, tags, type, spec, spec_revision, applied_revision,
       template_name, template_version, git_repo_id
FROM clusters
ORDER BY slug
`

type ListGitClustersRow struct {
	ID              uuid.UUID
	Slug            string
	Name            string
	Description     string
	Environment     Environment
	Tags            []string
	Type            string
	Spec            []byte
	SpecRevision    int32
	AppliedRevision int32
	TemplateName    *string
	TemplateVersion *string
	GitRepoID       *uuid.UUID
}

// De clusters die bij een scan horen: alle clusters met hun slug, of ze
// uit een template komen en of ze gekoppeld zijn.
func (q *Queries) ListGitClusters(ctx context.Context) ([]ListGitClustersRow, error) {
	rows, err := q.db.Query(ctx, listGitClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGitClustersRow{}
	for rows.Next() {
		var i ListGitClustersRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Environment,
			&i.Tags,
			&i.Type,
			&i.Spec,
			&i.SpecRevision,
			&i.AppliedRevision,
			&i.TemplateName,
			&i.TemplateVersion,
			&i.GitRepoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestGitChanges = `-- name: ListLatestGitChanges :many
SELECT DISTINCT ON (slug) id, repo_id, cluster_id, slug, path, kind, commit_sha, commit_message, commit_author, commit_verified, commit_url, committed_at, blob_sha, base_revision, spec, metadata, plan, status, job_id, decided_by, decided_at, reason, created_at, updated_at, revision FROM git_changes ORDER BY slug, created_at DESC, id
`

// De nieuwste wijziging per slug, ongeacht haar status.
func (q *Queries) ListLatestGitChanges(ctx context.Context) ([]GitChange, error) {
	rows, err := q.db.Query(ctx, listLatestGitChanges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitChange{}
	for rows.Next() {
		var i GitChange
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.ClusterID,
			&i.Slug,
			&i.Path,
			&i.Kind,
			&i.CommitSha,
			&i.CommitMessage,
			&i.CommitAuthor,
			&i.CommitVerified,
			&i.CommitUrl,
			&i.CommittedAt,
			&i.BlobSha,
			&i.BaseRevision,
			&i.Spec,
			&i.Metadata,
			&i.Plan,
			&i.Status,
			&i.JobID,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingGitChanges = `-- name: ListPendingGitChanges :many
SELECT id, repo_id, cluster_id, slug, path, kind, commit_sha, commit_message, commit_author, commit_verified, commit_url, committed_at, blob_sha, base_revision, spec, metadata, plan, status, job_id, decided_by, decided_at, reason, created_at, updated_at, revision FROM git_changes WHERE status = 'pending' ORDER BY slug
`

func (q *Queries) ListPendingGitChanges(ctx context.Context) ([]GitChange, error) {
	rows, err := q.db.Query(ctx, listPendingGitChanges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitChange{}
	for rows.Next() {
		var i GitChange
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.ClusterID,
			&i.Slug,
			&i.Path,
			&i.Kind,
			&i.CommitSha,
			&i.CommitMessage,
			&i.CommitAuthor,
			&i.CommitVerified,
			&i.CommitUrl,
			&i.CommittedAt,
			&i.BlobSha,
			&i.BaseRevision,
			&i.Spec,
			&i.Metadata,
			&i.Plan,
			&i.Status,
			&i.JobID,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGitChange = `-- name: LockGitChange :one
SELECT id, repo_id, cluster_id, slug, path, kind, commit_sha, commit_message, commit_author, commit_verified, commit_url, committed_at, blob_sha, base_revision, spec, metadata, plan, status, job_id, decided_by, decided_at, reason, created_at, updated_at, revision FROM git_changes WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockGitChange(ctx context.Context, id uuid.UUID) (GitChange, error) {
	row := q.db.QueryRow(ctx, lockGitChange, id)
	var i GitChange
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.ClusterID,
		&i.Slug,
		&i.Path,
		&i.Kind,
		&i.CommitSha,
		&i.CommitMessage,
		&i.CommitAuthor,
		&i.CommitVerified,
		&i.CommitUrl,
		&i.CommittedAt,
		&i.BlobSha,
		&i.BaseRevision,
		&i.Spec,
		&i.Metadata,
		&i.Plan,
		&i.Status,
		&i.JobID,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const lockGitRepo = `-- name: LockGitRepo :one
SELECT id, api_url, owner, name, branch, path, token_enc, key_id, head_sha, head_etag, synced_sha, head_commit, scan, last_sync_at, last_error, created_at, updated_at FROM git_repos LIMIT 1 FOR UPDATE
`

func (q *Queries) LockGitRepo(ctx context.Context) (GitRepo, error) {
	row := q.db.QueryRow(ctx, lockGitRepo)
	var i GitRepo
	err := row.Scan(
		&i.ID,
		&i.ApiUrl,
		&i.Owner,
		&i.Name,
		&i.Branch,
		&i.Path,
		&i.TokenEnc,
		&i.KeyID,
		&i.HeadSha,
		&i.HeadEtag,
		&i.SyncedSha,
		&i.HeadCommit,
		&i.Scan,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setClusterGit = `-- name: SetClusterGit :exec
UPDATE clusters SET git_repo_id = $1, git_repo_url = $2, updated_at = now() WHERE id = $3
`

type SetClusterGitParams struct {
	GitRepoID  *uuid.UUID
	GitRepoUrl string
	ID         uuid.UUID
}

func (q *Queries) SetClusterGit(ctx context.Context, arg SetClusterGitParams) error {
	_, err := q.db.Exec(ctx, setClusterGit, arg.GitRepoID, arg.GitRepoUrl, arg.ID)
	return err
}

const setGitError = `-- name: SetGitError :exec
UPDATE git_repos SET last_error = $1, last_sync_at = $2 WHERE id = $3
`

type SetGitErrorParams struct {
	LastError  string
	LastSyncAt *time.Time
	ID         uuid.UUID
}

func (q *Queries) SetGitError(ctx context.Context, arg SetGitErrorParams) error {
	_, err := q.db.Exec(ctx, setGitError, arg.LastError, arg.LastSyncAt, arg.ID)
	return err
}

const setGitHead = `-- name: SetGitHead :exec
UPDATE git_repos SET head_sha = $1, head_etag = $2, head_commit = $3 WHERE id = $4
`

type SetGitHeadParams struct {
	HeadSha    string
	HeadEtag   string
	HeadCommit []byte
	ID         uuid.UUID
}

func (q *Queries) SetGitHead(ctx context.Context, arg SetGitHeadParams) error {
	_, err := q.db.Exec(ctx, setGitHead,
		arg.HeadSha,
		arg.HeadEtag,
		arg.HeadCommit,
		arg.ID,
	)
	return err
}

const setGitScan = `-- name: SetGitScan :exec
UPDATE git_repos
SET synced_sha = $1, scan = $2, last_sync_at = $3, last_error = ''
WHERE id = $4
`

type SetGitScanParams struct {
	SyncedSha  string
	Scan       []byte
	LastSyncAt *time.Time
	ID         uuid.UUID
}

func (q *Queries) SetGitScan(ctx context.Context, arg SetGitScanParams) error {
	_, err := q.db.Exec(ctx, setGitScan,
		arg.SyncedSha,
		arg.Scan,
		arg.LastSyncAt,
		arg.ID,
	)
	return err
}

const supersedeGitChange = `-- name: SupersedeGitChange :one
UPDATE git_changes SET status = 'superseded', reason = $1, updated_at = now()
WHERE id = $2 AND status = 'pending'
RETURNING id, repo_id, cluster_id, slug, path, kind, commit_sha, commit_message, commit_author, commit_verified, commit_url, committed_at, blob_sha, base_revision, spec, metadata, plan, status, job_id, decided_by, decided_at, reason, created_at, updated_at, revision
`

type SupersedeGitChangeParams struct {
	Reason string
	ID     uuid.UUID
}

func (q *Queries) SupersedeGitChange(ctx context.Context, arg SupersedeGitChangeParams) (GitChange, error) {
	row := q.db.QueryRow(ctx, supersedeGitChange, arg.Reason, arg.ID)
	var i GitChange
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.ClusterID,
		&i.Slug,
		&i.Path,
		&i.Kind,
		&i.CommitSha,
		&i.CommitMessage,
		&i.CommitAuthor,
		&i.CommitVerified,
		&i.CommitUrl,
		&i.CommittedAt,
		&i.BlobSha,
		&i.BaseRevision,
		&i.Spec,
		&i.Metadata,
		&i.Plan,
		&i.Status,
		&i.JobID,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const unlinkGitClusters = `-- name: UnlinkGitClusters :many
UPDATE clusters SET git_repo_id = NULL, updated_at = now()
WHERE git_repo_id = $1
RETURNING id, name, slug
`

type UnlinkGitClustersRow struct {
	ID   uuid.UUID
	Name string
	Slug string
}

// Ontkoppelt alle clusters van een repository, voor het verwijderen ervan.
func (q *Queries) UnlinkGitClusters(ctx context.Context, repoID *uuid.UUID) ([]UnlinkGitClustersRow, error) {
	rows, err := q.db.Query(ctx, unlinkGitClusters, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnlinkGitClustersRow{}
	for rows.Next() {
		var i UnlinkGitClustersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGitRepo = `-- name: UpdateGitRepo :one
UPDATE git_repos
SET api_url = $1, owner = $2, name = $3, branch = $4, path = $5,
    token_enc = $6, key_id = $7,
    head_sha = CASE WHEN $8::boolean THEN '' ELSE head_sha END,
    head_etag = '',
    synced_sha = CASE WHEN $8::boolean THEN '' ELSE synced_sha END,
    head_commit = CASE WHEN $8::boolean THEN NULL ELSE head_commit END,
    scan = CASE WHEN $8::boolean THEN '[]'::jsonb ELSE scan END,
    last_error = '', updated_at = now()
WHERE id = $9
RETURNING id, api_url, owner, name, branch, path, token_enc, key_id, head_sha, head_etag, synced_sha, head_commit, scan, last_sync_at, last_error, created_at, updated_at
`

type UpdateGitRepoParams struct {
	ApiUrl   string
	Owner    string
	Name     string
	Branch   string
	Path     string
	TokenEnc []byte
	KeyID    string
	Reset    bool
	ID       uuid.UUID
}

// Een andere repository, branch of map begint opnieuw: de kop, de ETag en
// de scan vervallen.
func (q *Queries) UpdateGitRepo(ctx context.Context, arg UpdateGitRepoParams) (GitRepo, error) {
	row := q.db.QueryRow(ctx, updateGitRepo,
		arg.ApiUrl,
		arg.Owner,
		arg.Name,
		arg.Branch,
		arg.Path,
		arg.TokenEnc,
		arg.KeyID,
		arg.Reset,
		arg.ID,
	)
	var i GitRepo
	err := row.Scan(
		&i.ID,
		&i.ApiUrl,
		&i.Owner,
		&i.Name,
		&i.Branch,
		&i.Path,
		&i.TokenEnc,
		&i.KeyID,
		&i.HeadSha,
		&i.HeadEtag,
		&i.SyncedSha,
		&i.HeadCommit,
		&i.Scan,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
