// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jobs.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelQueuedJob = `-- name: CancelQueuedJob :one
UPDATE jobs SET status = 'canceled', finished_at = now() WHERE id = $1 AND status = 'queued' RETURNING id, kind, title, status, params, cluster_id, node_id, proxmox_id, requested_by, error, cancel_requested, attempts, created_at, started_at, finished_at, heartbeat_at
`

func (q *Queries) CancelQueuedJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, cancelQueuedJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Title,
		&i.Status,
		&i.Params,
		&i.ClusterID,
		&i.NodeID,
		&i.ProxmoxID,
		&i.RequestedBy,
		&i.Error,
		&i.CancelRequested,
		&i.Attempts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET status = 'running', attempts = attempts + 1, started_at = coalesce(started_at, now()), heartbeat_at = now()
WHERE id = (
    SELECT j.id FROM jobs j WHERE j.status = 'queued' ORDER BY j.created_at FOR UPDATE SKIP LOCKED LIMIT 1
)
RETURNING id, kind, title, status, params, cluster_id, node_id, proxmox_id, requested_by, error, cancel_requested, attempts, created_at, started_at, finished_at, heartbeat_at
`

// Neemt de oudste wachtende taak; SKIP LOCKED laat meerdere workers naast
// elkaar claimen zonder op elkaar te wachten.
func (q *Queries) ClaimJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Title,
		&i.Status,
		&i.Params,
		&i.ClusterID,
		&i.NodeID,
		&i.ProxmoxID,
		&i.RequestedBy,
		&i.Error,
		&i.CancelRequested,
		&i.Attempts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (kind, title, params, cluster_id, node_id, proxmox_id, requested_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, kind, title, status, params, cluster_id, node_id, proxmox_id, requested_by, error, cancel_requested, attempts, created_at, started_at, finished_at, heartbeat_at
`

type CreateJobParams struct {
	Kind        string
	Title       string
	Params      []byte
	ClusterID   *uuid.UUID
	NodeID      *uuid.UUID
	ProxmoxID   *uuid.UUID
	RequestedBy *uuid.UUID
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Kind,
		arg.Title,
		arg.Params,
		arg.ClusterID,
		arg.NodeID,
		arg.ProxmoxID,
		arg.RequestedBy,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Title,
		&i.Status,
		&i.Params,
		&i.ClusterID,
		&i.NodeID,
		&i.ProxmoxID,
		&i.RequestedBy,
		&i.Error,
		&i.CancelRequested,
		&i.Attempts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const finishJob = `-- name: FinishJob :one
UPDATE jobs SET status = $2, error = $3, finished_at = now()
WHERE id = $1 AND status IN ('queued', 'running')
RETURNING id, kind, title, status, params, cluster_id, node_id, proxmox_id, requested_by, error, cancel_requested, attempts, created_at, started_at, finished_at, heartbeat_at
`

type FinishJobParams struct {
	ID     uuid.UUID
	Status JobStatus
	Error  string
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, finishJob, arg.ID, arg.Status, arg.Error)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Title,
		&i.Status,
		&i.Params,
		&i.ClusterID,
		&i.NodeID,
		&i.ProxmoxID,
		&i.RequestedBy,
		&i.Error,
		&i.CancelRequested,
		&i.Attempts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT j.id, j.kind, j.title, j.status, j.params, j.cluster_id, j.node_id, j.proxmox_id, j.requested_by, j.error, j.cancel_requested, j.attempts, j.created_at, j.started_at, j.finished_at, j.heartbeat_at, u.username AS requested_by_name
FROM jobs j LEFT JOIN users u ON u.id = j.requested_by
WHERE j.id = $1
`

type GetJobRow struct {
	Job             Job
	RequestedByName *string
}

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (GetJobRow, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i GetJobRow
	err := row.Scan(
		&i.Job.ID,
		&i.Job.Kind,
		&i.Job.Title,
		&i.Job.Status,
		&i.Job.Params,
		&i.Job.ClusterID,
		&i.Job.NodeID,
		&i.Job.ProxmoxID,
		&i.Job.RequestedBy,
		&i.Job.Error,
		&i.Job.CancelRequested,
		&i.Job.Attempts,
		&i.Job.CreatedAt,
		&i.Job.StartedAt,
		&i.Job.FinishedAt,
		&i.Job.HeartbeatAt,
		&i.RequestedByName,
	)
	return i, err
}

const jobHeartbeat = `-- name: JobHeartbeat :one
UPDATE jobs SET heartbeat_at = now() WHERE id = $1 AND status = 'running' RETURNING cancel_requested
`

func (q *Queries) JobHeartbeat(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, jobHeartbeat, id)
	var cancel_requested bool
	err := row.Scan(&cancel_requested)
	return cancel_requested, err
}

const listJobSteps = `-- name: ListJobSteps :many
SELECT job_id, seq, name, status, started_at, finished_at, state, log, error FROM job_steps WHERE job_id = $1 ORDER BY seq
`

func (q *Queries) ListJobSteps(ctx context.Context, jobID uuid.UUID) ([]JobStep, error) {
	rows, err := q.db.Query(ctx, listJobSteps, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobStep{}
	for rows.Next() {
		var i JobStep
		if err := rows.Scan(
			&i.JobID,
			&i.Seq,
			&i.Name,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.State,
			&i.Log,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT j.id, j.kind, j.title, j.status, j.params, j.cluster_id, j.node_id, j.proxmox_id, j.requested_by, j.error, j.cancel_requested, j.attempts, j.created_at, j.started_at, j.finished_at, j.heartbeat_at, u.username AS requested_by_name
FROM jobs j LEFT JOIN users u ON u.id = j.requested_by
WHERE ($1::uuid IS NULL OR j.node_id = $1)
  AND ($2::uuid IS NULL OR j.proxmox_id = $2)
  AND ($3::uuid IS NULL OR j.cluster_id = $3)
ORDER BY j.created_at DESC
LIMIT $4
`

type ListJobsParams struct {
	NodeID    *uuid.UUID
	ProxmoxID *uuid.UUID
	ClusterID *uuid.UUID
	MaxRows   int32
}

type ListJobsRow struct {
	Job             Job
	RequestedByName *string
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs,
		arg.NodeID,
		arg.ProxmoxID,
		arg.ClusterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsRow{}
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.Job.ID,
			&i.Job.Kind,
			&i.Job.Title,
			&i.Job.Status,
			&i.Job.Params,
			&i.Job.ClusterID,
			&i.Job.NodeID,
			&i.Job.ProxmoxID,
			&i.Job.RequestedBy,
			&i.Job.Error,
			&i.Job.CancelRequested,
			&i.Job.Attempts,
			&i.Job.CreatedAt,
			&i.Job.StartedAt,
			&i.Job.FinishedAt,
			&i.Job.HeartbeatAt,
			&i.RequestedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestJobCancel = `-- name: RequestJobCancel :one
UPDATE jobs SET cancel_requested = true WHERE id = $1 AND status = 'running' RETURNING id, kind, title, status, params, cluster_id, node_id, proxmox_id, requested_by, error, cancel_requested, attempts, created_at, started_at, finished_at, heartbeat_at
`

func (q *Queries) RequestJobCancel(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, requestJobCancel, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Title,
		&i.Status,
		&i.Params,
		&i.ClusterID,
		&i.NodeID,
		&i.ProxmoxID,
		&i.RequestedBy,
		&i.Error,
		&i.CancelRequested,
		&i.Attempts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const requeueJob = `-- name: RequeueJob :exec
UPDATE jobs SET status = 'queued' WHERE id = $1 AND status = 'running'
`

func (q *Queries) RequeueJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, requeueJob, id)
	return err
}

const requeueStaleJobs = `-- name: RequeueStaleJobs :many
UPDATE jobs SET status = 'queued'
WHERE status = 'running' AND heartbeat_at < now() - make_interval(secs => $1::float8)
RETURNING id
`

// Taken waarvan de heartbeat stilstaat, horen bij een gestopte server.
func (q *Queries) RequeueStaleJobs(ctx context.Context, staleSeconds float64) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, requeueStaleJobs, staleSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveJobStep = `-- name: SaveJobStep :exec
INSERT INTO job_steps (job_id, seq, name, status, finished_at, state, log, error)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (job_id, seq) DO UPDATE
SET name = EXCLUDED.name, status = EXCLUDED.status, finished_at = EXCLUDED.finished_at,
    state = EXCLUDED.state, log = EXCLUDED.log, error = EXCLUDED.error
`

type SaveJobStepParams struct {
	JobID      uuid.UUID
	Seq        int32
	Name       string
	Status     JobStatus
	FinishedAt *time.Time
	State      []byte
	Log        []string
	Error      string
}

func (q *Queries) SaveJobStep(ctx context.Context, arg SaveJobStepParams) error {
	_, err := q.db.Exec(ctx, saveJobStep,
		arg.JobID,
		arg.Seq,
		arg.Name,
		arg.Status,
		arg.FinishedAt,
		arg.State,
		arg.Log,
		arg.Error,
	)
	return err
}
