// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lifecycle.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getActiveNodeJob = `-- name: GetActiveNodeJob :one
SELECT id, title FROM jobs
WHERE node_id = $1 AND kind = $2 AND status IN ('queued', 'running')
ORDER BY created_at LIMIT 1
`

type GetActiveNodeJobParams struct {
	NodeID *uuid.UUID
	Kind   string
}

type GetActiveNodeJobRow struct {
	ID    uuid.UUID
	Title string
}

func (q *Queries) GetActiveNodeJob(ctx context.Context, arg GetActiveNodeJobParams) (GetActiveNodeJobRow, error) {
	row := q.db.QueryRow(ctx, getActiveNodeJob, arg.NodeID, arg.Kind)
	var i GetActiveNodeJobRow
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const getNodeRuntime = `-- name: GetNodeRuntime :one
SELECT n.id, n.hostname, n.cluster_id, n.lifecycle,
       (a.id IS NOT NULL)::boolean AS has_agent,
       coalesce(a.protocol_version, 0)::int AS agent_protocol,
       s.heartbeat_at,
       coalesce(s.uptime_seconds, 0)::bigint AS uptime_seconds,
       coalesce(s.addresses, '{}')::text[] AS addresses,
       coalesce(s.services, '{}'::jsonb)::jsonb AS services
FROM nodes n
LEFT JOIN agents a ON a.node_id = n.id AND a.revoked_at IS NULL
LEFT JOIN node_status s ON s.node_id = n.id
WHERE n.id = $1
`

type GetNodeRuntimeRow struct {
	ID            uuid.UUID
	Hostname      string
	ClusterID     *uuid.UUID
	Lifecycle     NodeLifecycle
	HasAgent      bool
	AgentProtocol int32
	HeartbeatAt   *time.Time
	UptimeSeconds int64
	Addresses     []string
	Services      []byte
}

// Wat een actie op een node over die node moet weten.
func (q *Queries) GetNodeRuntime(ctx context.Context, id uuid.UUID) (GetNodeRuntimeRow, error) {
	row := q.db.QueryRow(ctx, getNodeRuntime, id)
	var i GetNodeRuntimeRow
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.ClusterID,
		&i.Lifecycle,
		&i.HasAgent,
		&i.AgentProtocol,
		&i.HeartbeatAt,
		&i.UptimeSeconds,
		&i.Addresses,
		&i.Services,
	)
	return i, err
}

const listClusterPeers = `-- name: ListClusterPeers :many
SELECT n.id, n.hostname, n.lifecycle, s.heartbeat_at,
       coalesce(s.services, '{}'::jsonb)::jsonb AS services
FROM nodes n
LEFT JOIN agents a ON a.node_id = n.id AND a.revoked_at IS NULL
LEFT JOIN node_status s ON s.node_id = n.id AND a.id IS NOT NULL
WHERE n.cluster_id = $1 AND n.id <> $2
ORDER BY n.hostname
`

type ListClusterPeersParams struct {
	ClusterID *uuid.UUID
	NodeID    uuid.UUID
}

type ListClusterPeersRow struct {
	ID          uuid.UUID
	Hostname    string
	Lifecycle   NodeLifecycle
	HeartbeatAt *time.Time
	Services    []byte
}

// De andere nodes van een cluster, om te zien wie een VIP kan overnemen.
func (q *Queries) ListClusterPeers(ctx context.Context, arg ListClusterPeersParams) ([]ListClusterPeersRow, error) {
	rows, err := q.db.Query(ctx, listClusterPeers, arg.ClusterID, arg.NodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClusterPeersRow{}
	for rows.Next() {
		var i ListClusterPeersRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.Lifecycle,
			&i.HeartbeatAt,
			&i.Services,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNodeLifecycle = `-- name: SetNodeLifecycle :one
UPDATE nodes n SET lifecycle = $1, updated_at = now()
FROM (SELECT o.id, o.lifecycle FROM nodes o WHERE o.id = $2 FOR UPDATE) old
WHERE n.id = old.id
RETURNING old.lifecycle AS previous, n.hostname, n.cluster_id
`

type SetNodeLifecycleParams struct {
	Lifecycle NodeLifecycle
	NodeID    uuid.UUID
}

type SetNodeLifecycleRow struct {
	Previous  NodeLifecycle
	Hostname  string
	ClusterID *uuid.UUID
}

func (q *Queries) SetNodeLifecycle(ctx context.Context, arg SetNodeLifecycleParams) (SetNodeLifecycleRow, error) {
	row := q.db.QueryRow(ctx, setNodeLifecycle, arg.Lifecycle, arg.NodeID)
	var i SetNodeLifecycleRow
	err := row.Scan(&i.Previous, &i.Hostname, &i.ClusterID)
	return i, err
}
