// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type ActorType string

const (
	ActorTypeUser   ActorType = "user"
	ActorTypeAgent  ActorType = "agent"
	ActorTypeSystem ActorType = "system"
)

func (e *ActorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActorType(s)
	case string:
		*e = ActorType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActorType: %T", src)
	}
	return nil
}

type NullActorType struct {
	ActorType ActorType
	Valid     bool // Valid is true if ActorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActorType) Scan(value interface{}) error {
	if value == nil {
		ns.ActorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActorType), nil
}

type Environment string

const (
	EnvironmentLab  Environment = "lab"
	EnvironmentTest Environment = "test"
	EnvironmentProd Environment = "prod"
)

func (e *Environment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Environment(s)
	case string:
		*e = Environment(s)
	default:
		return fmt.Errorf("unsupported scan type for Environment: %T", src)
	}
	return nil
}

type NullEnvironment struct {
	Environment Environment
	Valid       bool // Valid is true if Environment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnvironment) Scan(value interface{}) error {
	if value == nil {
		ns.Environment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Environment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnvironment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Environment), nil
}

type JobStatus string

const (
	JobStatusQueued    JobStatus = "queued"
	JobStatusRunning   JobStatus = "running"
	JobStatusSucceeded JobStatus = "succeeded"
	JobStatusFailed    JobStatus = "failed"
	JobStatusCanceled  JobStatus = "canceled"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus
	Valid     bool // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type NodeLifecycle string

const (
	NodeLifecycleProvisioning   NodeLifecycle = "provisioning"
	NodeLifecycleActive         NodeLifecycle = "active"
	NodeLifecycleMaintenance    NodeLifecycle = "maintenance"
	NodeLifecycleDraining       NodeLifecycle = "draining"
	NodeLifecycleDecommissioned NodeLifecycle = "decommissioned"
)

func (e *NodeLifecycle) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NodeLifecycle(s)
	case string:
		*e = NodeLifecycle(s)
	default:
		return fmt.Errorf("unsupported scan type for NodeLifecycle: %T", src)
	}
	return nil
}

type NullNodeLifecycle struct {
	NodeLifecycle NodeLifecycle
	Valid         bool // Valid is true if NodeLifecycle is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNodeLifecycle) Scan(value interface{}) error {
	if value == nil {
		ns.NodeLifecycle, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NodeLifecycle.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNodeLifecycle) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NodeLifecycle), nil
}

type UserRole string

const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleViewer UserRole = "viewer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Agent struct {
	ID              uuid.UUID
	NodeID          uuid.UUID
	NkeyPublic      string
	MachineID       string
	Version         string
	ProtocolVersion int32
	EnrolledAt      time.Time
	LastSeenAt      *time.Time
	RevokedAt       *time.Time
}

type BackupPolicy struct {
	ClusterID     uuid.UUID
	MaxAgeHours   int32
	UpdatedAt     time.Time
	UpdatedBy     *uuid.UUID
	VerifyEnabled bool
	NextRunAt     *time.Time
}

type BackupSandbox struct {
	ID           uuid.UUID
	ConnectionID uuid.UUID
	Vmid         int32
	SourceVmid   int32
	SourceNodeID *uuid.UUID
	RunID        *uuid.UUID
	Volid        string
	State        string
	Host         string
	Storage      string
	Error        string
	CreatedAt    time.Time
	DestroyedAt  *time.Time
}

type BackupStatus struct {
	ConnectionID   uuid.UUID
	Vmid           int32
	Freshness      string
	LatestBackupAt *time.Time
	ChangedAt      time.Time
}

type BackupWatch struct {
	ConnectionID uuid.UUID
	Vmid         int32
	Label        string
	CreatedAt    time.Time
}

type Cluster struct {
	ID              uuid.UUID
	Slug            string
	Name            string
	Description     string
	Type            string
	Environment     Environment
	GitRepoUrl      string
	Tags            []string
	Status          string
	Spec            []byte
	SpecRevision    int32
	TemplateName    *string
	TemplateVersion *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	StatusReason    string
	StatusSince     *time.Time
}

type ClusterOwner struct {
	ClusterID uuid.UUID
	UserID    uuid.UUID
}

type ClusterSpecRevision struct {
	ClusterID uuid.UUID
	Revision  int32
	Spec      []byte
	Source    string
	CreatedBy *uuid.UUID
	CreatedAt time.Time
}

type DriftCheck struct {
	NodeID          uuid.UUID
	Status          string
	Source          string
	SpecRevision    int32
	TemplateVersion string
	Findings        []byte
	Unchecked       []byte
	Fingerprint     string
	Error           string
	CheckedAt       time.Time
	DriftSince      *time.Time
}

type DriftIgnore struct {
	ID        uuid.UUID
	ClusterID uuid.UUID
	NodeID    *uuid.UUID
	Key       string
	Reason    string
	ExpiresAt *time.Time
	CreatedBy *uuid.UUID
	CreatedAt time.Time
}

type EnrollmentToken struct {
	ID          uuid.UUID
	TokenHash   []byte
	Description string
	NodeID      *uuid.UUID
	ClusterID   *uuid.UUID
	MaxUses     int32
	Uses        int32
	ExpiresAt   time.Time
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
}

type Event struct {
	ID          int64
	Ts          time.Time
	ActorType   ActorType
	ActorID     string
	SubjectType string
	SubjectID   string
	ClusterID   *uuid.UUID
	Action      string
	Payload     []byte
	NodeRef     *string
	JobRef      *string
}

type FailoverTest struct {
	ID                 uuid.UUID
	ClusterID          uuid.UUID
	VipID              uuid.UUID
	Name               string
	Scenario           string
	Service            string
	MaxTakeoverSeconds int32
	ExpectFailback     bool
	Probe              []byte
	CreatedBy          *uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Scheduled          bool
	NextRunAt          *time.Time
}

type Job struct {
	ID              uuid.UUID
	Kind            string
	Title           string
	Status          JobStatus
	Params          []byte
	ClusterID       *uuid.UUID
	NodeID          *uuid.UUID
	ProxmoxID       *uuid.UUID
	RequestedBy     *uuid.UUID
	Error           string
	CancelRequested bool
	Attempts        int32
	CreatedAt       time.Time
	StartedAt       *time.Time
	FinishedAt      *time.Time
	HeartbeatAt     *time.Time
	ClusterSlot     bool
}

type JobStep struct {
	JobID      uuid.UUID
	Seq        int32
	Name       string
	Status     JobStatus
	StartedAt  time.Time
	FinishedAt *time.Time
	State      []byte
	Log        []string
	Error      string
}

type Node struct {
	ID           uuid.UUID
	ClusterID    *uuid.UUID
	Hostname     string
	Role         string
	Description  string
	Lifecycle    NodeLifecycle
	PrimaryIp    *netip.Addr
	Tags         []string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Status       string
	StatusReason string
	StatusSince  *time.Time
	ProxmoxID    *uuid.UUID
	PveVmid      *int32
}

type NodeFact struct {
	NodeID      uuid.UUID
	Hash        string
	Facts       []byte
	CollectedAt time.Time
	ChangedAt   time.Time
}

type NodeStatus struct {
	NodeID        uuid.UUID
	HeartbeatAt   time.Time
	UptimeSeconds int64
	Load1         float64
	Load5         float64
	Load15        float64
	Addresses     []string
	Services      []byte
	DiskUsedRatio float64
	DiskUsedMount string
}

type ProxmoxBackup struct {
	ConnectionID uuid.UUID
	Volid        string
	Storage      string
	PveNode      string
	Vmid         int32
	GuestType    string
	Ctime        time.Time
	SizeBytes    int64
	Format       string
	Notes        string
	Protected    bool
	VerifyState  string
	SyncedAt     time.Time
}

type ProxmoxConnection struct {
	ID              uuid.UUID
	Name            string
	ApiUrl          string
	TokenID         string
	TokenSecretEnc  []byte
	KeyID           string
	TlsFingerprint  string
	PveVersion      string
	LastSyncAt      *time.Time
	LastError       string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	BackupCheckedAt *time.Time
	BackupError     string
	NotBackedUp     []byte
}

type ProxmoxResource struct {
	ConnectionID uuid.UUID
	PveID        string
	Type         string
	PveNode      string
	Vmid         *int32
	Name         string
	Status       string
	Template     bool
	Data         []byte
	SyncedAt     time.Time
}

type Secret struct {
	ID        uuid.UUID
	ClusterID uuid.UUID
	Name      string
	ValueEnc  []byte
	KeyID     string
	CreatedAt time.Time
}

type ServerSecret struct {
	Name      string
	Value     []byte
	CreatedAt time.Time
}

type Service struct {
	ID            uuid.UUID
	ClusterID     *uuid.UUID
	NodeID        *uuid.UUID
	Name          string
	Kind          string
	Unit          string
	Port          *int32
	Address       string
	Description   string
	Source        string
	State         string
	LastSeenAt    *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Status        *string
	StatusReason  string
	Impact        string
	ImpactReason  string
	ImpactCauseID *uuid.UUID
	ImpactSince   *time.Time
}

type ServiceDependency struct {
	ID            uuid.UUID
	FromServiceID uuid.UUID
	ToServiceID   uuid.UUID
	Strength      string
	Source        string
	State         string
	Note          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Session struct {
	ID         []byte
	UserID     uuid.UUID
	CsrfToken  string
	Ip         string
	UserAgent  string
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

type TestRun struct {
	ID           uuid.UUID
	Kind         string
	Trigger      string
	ClusterID    *uuid.UUID
	TestID       *uuid.UUID
	NodeID       *uuid.UUID
	Hostname     string
	JobID        *uuid.UUID
	Definition   []byte
	Result       *string
	Restored     *bool
	Summary      string
	Checks       []byte
	Timeline     []byte
	Measurements []byte
	RequestedBy  *uuid.UUID
	CreatedAt    time.Time
	FinishedAt   *time.Time
}

type User struct {
	ID            uuid.UUID
	Username      string
	PasswordHash  string
	Role          UserRole
	TotpSecret    *string
	TotpEnabledAt *time.Time
	TotpLastStep  *int64
	DisabledAt    *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Vip struct {
	ID          uuid.UUID
	ClusterID   uuid.UUID
	Address     netip.Addr
	Interface   string
	Vrid        *int32
	Description string
	OwnerNodeID *uuid.UUID
	OwnerSince  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
