// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type ActorType string

const (
	ActorTypeUser   ActorType = "user"
	ActorTypeAgent  ActorType = "agent"
	ActorTypeSystem ActorType = "system"
)

func (e *ActorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActorType(s)
	case string:
		*e = ActorType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActorType: %T", src)
	}
	return nil
}

type NullActorType struct {
	ActorType ActorType
	Valid     bool // Valid is true if ActorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActorType) Scan(value interface{}) error {
	if value == nil {
		ns.ActorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActorType), nil
}

type Environment string

const (
	EnvironmentLab  Environment = "lab"
	EnvironmentTest Environment = "test"
	EnvironmentProd Environment = "prod"
)

func (e *Environment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Environment(s)
	case string:
		*e = Environment(s)
	default:
		return fmt.Errorf("unsupported scan type for Environment: %T", src)
	}
	return nil
}

type NullEnvironment struct {
	Environment Environment
	Valid       bool // Valid is true if Environment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnvironment) Scan(value interface{}) error {
	if value == nil {
		ns.Environment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Environment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnvironment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Environment), nil
}

type NodeLifecycle string

const (
	NodeLifecycleProvisioning   NodeLifecycle = "provisioning"
	NodeLifecycleActive         NodeLifecycle = "active"
	NodeLifecycleMaintenance    NodeLifecycle = "maintenance"
	NodeLifecycleDraining       NodeLifecycle = "draining"
	NodeLifecycleDecommissioned NodeLifecycle = "decommissioned"
)

func (e *NodeLifecycle) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NodeLifecycle(s)
	case string:
		*e = NodeLifecycle(s)
	default:
		return fmt.Errorf("unsupported scan type for NodeLifecycle: %T", src)
	}
	return nil
}

type NullNodeLifecycle struct {
	NodeLifecycle NodeLifecycle
	Valid         bool // Valid is true if NodeLifecycle is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNodeLifecycle) Scan(value interface{}) error {
	if value == nil {
		ns.NodeLifecycle, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NodeLifecycle.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNodeLifecycle) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NodeLifecycle), nil
}

type UserRole string

const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleViewer UserRole = "viewer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Agent struct {
	ID              uuid.UUID
	NodeID          uuid.UUID
	NkeyPublic      string
	MachineID       string
	Version         string
	ProtocolVersion int32
	EnrolledAt      time.Time
	LastSeenAt      *time.Time
	RevokedAt       *time.Time
}

type Cluster struct {
	ID              uuid.UUID
	Slug            string
	Name            string
	Description     string
	Type            string
	Environment     Environment
	GitRepoUrl      string
	Tags            []string
	Status          string
	Spec            []byte
	SpecRevision    int32
	TemplateName    *string
	TemplateVersion *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	StatusReason    string
	StatusSince     *time.Time
}

type ClusterOwner struct {
	ClusterID uuid.UUID
	UserID    uuid.UUID
}

type EnrollmentToken struct {
	ID          uuid.UUID
	TokenHash   []byte
	Description string
	NodeID      *uuid.UUID
	ClusterID   *uuid.UUID
	MaxUses     int32
	Uses        int32
	ExpiresAt   time.Time
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
}

type Event struct {
	ID          int64
	Ts          time.Time
	ActorType   ActorType
	ActorID     string
	SubjectType string
	SubjectID   string
	ClusterID   *uuid.UUID
	Action      string
	Payload     []byte
}

type Node struct {
	ID           uuid.UUID
	ClusterID    *uuid.UUID
	Hostname     string
	Role         string
	Description  string
	Lifecycle    NodeLifecycle
	PrimaryIp    *netip.Addr
	Tags         []string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Status       string
	StatusReason string
	StatusSince  *time.Time
}

type NodeFact struct {
	NodeID      uuid.UUID
	Hash        string
	Facts       []byte
	CollectedAt time.Time
	ChangedAt   time.Time
}

type NodeStatus struct {
	NodeID        uuid.UUID
	HeartbeatAt   time.Time
	UptimeSeconds int64
	Load1         float64
	Load5         float64
	Load15        float64
	Addresses     []string
	Services      []byte
	DiskUsedRatio float64
	DiskUsedMount string
}

type ServerSecret struct {
	Name      string
	Value     []byte
	CreatedAt time.Time
}

type Session struct {
	ID         []byte
	UserID     uuid.UUID
	CsrfToken  string
	Ip         string
	UserAgent  string
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

type User struct {
	ID            uuid.UUID
	Username      string
	PasswordHash  string
	Role          UserRole
	TotpSecret    *string
	TotpEnabledAt *time.Time
	TotpLastStep  *int64
	DisabledAt    *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Vip struct {
	ID          uuid.UUID
	ClusterID   uuid.UUID
	Address     netip.Addr
	Interface   string
	Vrid        *int32
	Description string
	OwnerNodeID *uuid.UUID
	OwnerSince  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
