// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: nodes.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (cluster_id, hostname, role, description, lifecycle, primary_ip, tags, proxmox_id, pve_vmid)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, cluster_id, hostname, role, description, lifecycle, primary_ip, tags, created_at, updated_at, status, status_reason, status_since, proxmox_id, pve_vmid
`

type CreateNodeParams struct {
	ClusterID   *uuid.UUID
	Hostname    string
	Role        string
	Description string
	Lifecycle   NodeLifecycle
	PrimaryIp   *netip.Addr
	Tags        []string
	ProxmoxID   *uuid.UUID
	PveVmid     *int32
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.ClusterID,
		arg.Hostname,
		arg.Role,
		arg.Description,
		arg.Lifecycle,
		arg.PrimaryIp,
		arg.Tags,
		arg.ProxmoxID,
		arg.PveVmid,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Hostname,
		&i.Role,
		&i.Description,
		&i.Lifecycle,
		&i.PrimaryIp,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.StatusSince,
		&i.ProxmoxID,
		&i.PveVmid,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :execrows
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNode = `-- name: GetNode :one
SELECT n.id, n.cluster_id, n.hostname, n.role, n.description, n.lifecycle, n.primary_ip, n.tags, n.created_at, n.updated_at, n.status, n.status_reason, n.status_since, n.proxmox_id, n.pve_vmid, c.slug AS cluster_slug, c.name AS cluster_name,
       a.id AS agent_id, a.version AS agent_version, a.enrolled_at AS agent_enrolled_at,
       a.last_seen_at AS agent_last_seen_at, a.protocol_version AS agent_protocol,
       pc.name AS proxmox_name, r.type AS pve_type, r.pve_node, r.name AS pve_name, r.status AS pve_status,
       r.data AS pve_data
FROM nodes n
LEFT JOIN clusters c ON c.id = n.cluster_id
LEFT JOIN agents a ON a.node_id = n.id AND a.revoked_at IS NULL
LEFT JOIN proxmox_connections pc ON pc.id = n.proxmox_id
LEFT JOIN proxmox_resources r ON r.connection_id = n.proxmox_id AND r.vmid = n.pve_vmid AND r.type IN ('qemu', 'lxc')
WHERE n.id = $1
`

type GetNodeRow struct {
	Node            Node
	ClusterSlug     *string
	ClusterName     *string
	AgentID         *uuid.UUID
	AgentVersion    *string
	AgentEnrolledAt *time.Time
	AgentLastSeenAt *time.Time
	AgentProtocol   *int32
	ProxmoxName     *string
	PveType         *string
	PveNode         *string
	PveName         *string
	PveStatus       *string
	PveData         []byte
}

func (q *Queries) GetNode(ctx context.Context, id uuid.UUID) (GetNodeRow, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i GetNodeRow
	err := row.Scan(
		&i.Node.ID,
		&i.Node.ClusterID,
		&i.Node.Hostname,
		&i.Node.Role,
		&i.Node.Description,
		&i.Node.Lifecycle,
		&i.Node.PrimaryIp,
		&i.Node.Tags,
		&i.Node.CreatedAt,
		&i.Node.UpdatedAt,
		&i.Node.Status,
		&i.Node.StatusReason,
		&i.Node.StatusSince,
		&i.Node.ProxmoxID,
		&i.Node.PveVmid,
		&i.ClusterSlug,
		&i.ClusterName,
		&i.AgentID,
		&i.AgentVersion,
		&i.AgentEnrolledAt,
		&i.AgentLastSeenAt,
		&i.AgentProtocol,
		&i.ProxmoxName,
		&i.PveType,
		&i.PveNode,
		&i.PveName,
		&i.PveStatus,
		&i.PveData,
	)
	return i, err
}

const getNodeRef = `-- name: GetNodeRef :one
SELECT hostname, cluster_id FROM nodes WHERE id = $1
`

type GetNodeRefRow struct {
	Hostname  string
	ClusterID *uuid.UUID
}

// Naam en cluster van een node, voor een event.
func (q *Queries) GetNodeRef(ctx context.Context, id uuid.UUID) (GetNodeRefRow, error) {
	row := q.db.QueryRow(ctx, getNodeRef, id)
	var i GetNodeRefRow
	err := row.Scan(&i.Hostname, &i.ClusterID)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT n.id, n.cluster_id, n.hostname, n.role, n.description, n.lifecycle, n.primary_ip, n.tags, n.created_at, n.updated_at, n.status, n.status_reason, n.status_since, n.proxmox_id, n.pve_vmid, c.slug AS cluster_slug, c.name AS cluster_name,
       a.id AS agent_id, a.version AS agent_version, a.enrolled_at AS agent_enrolled_at,
       a.last_seen_at AS agent_last_seen_at, a.protocol_version AS agent_protocol,
       pc.name AS proxmox_name, r.type AS pve_type, r.pve_node, r.name AS pve_name, r.status AS pve_status,
       r.data AS pve_data
FROM nodes n
LEFT JOIN clusters c ON c.id = n.cluster_id
LEFT JOIN agents a ON a.node_id = n.id AND a.revoked_at IS NULL
LEFT JOIN proxmox_connections pc ON pc.id = n.proxmox_id
LEFT JOIN proxmox_resources r ON r.connection_id = n.proxmox_id AND r.vmid = n.pve_vmid AND r.type IN ('qemu', 'lxc')
ORDER BY lower(n.hostname)
`

type ListNodesRow struct {
	Node            Node
	ClusterSlug     *string
	ClusterName     *string
	AgentID         *uuid.UUID
	AgentVersion    *string
	AgentEnrolledAt *time.Time
	AgentLastSeenAt *time.Time
	AgentProtocol   *int32
	ProxmoxName     *string
	PveType         *string
	PveNode         *string
	PveName         *string
	PveStatus       *string
	PveData         []byte
}

func (q *Queries) ListNodes(ctx context.Context) ([]ListNodesRow, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodesRow{}
	for rows.Next() {
		var i ListNodesRow
		if err := rows.Scan(
			&i.Node.ID,
			&i.Node.ClusterID,
			&i.Node.Hostname,
			&i.Node.Role,
			&i.Node.Description,
			&i.Node.Lifecycle,
			&i.Node.PrimaryIp,
			&i.Node.Tags,
			&i.Node.CreatedAt,
			&i.Node.UpdatedAt,
			&i.Node.Status,
			&i.Node.StatusReason,
			&i.Node.StatusSince,
			&i.Node.ProxmoxID,
			&i.Node.PveVmid,
			&i.ClusterSlug,
			&i.ClusterName,
			&i.AgentID,
			&i.AgentVersion,
			&i.AgentEnrolledAt,
			&i.AgentLastSeenAt,
			&i.AgentProtocol,
			&i.ProxmoxName,
			&i.PveType,
			&i.PveNode,
			&i.PveName,
			&i.PveStatus,
			&i.PveData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByCluster = `-- name: ListNodesByCluster :many
SELECT n.id, n.cluster_id, n.hostname, n.role, n.description, n.lifecycle, n.primary_ip, n.tags, n.created_at, n.updated_at, n.status, n.status_reason, n.status_since, n.proxmox_id, n.pve_vmid, c.slug AS cluster_slug, c.name AS cluster_name,
       a.id AS agent_id, a.version AS agent_version, a.enrolled_at AS agent_enrolled_at,
       a.last_seen_at AS agent_last_seen_at, a.protocol_version AS agent_protocol,
       pc.name AS proxmox_name, r.type AS pve_type, r.pve_node, r.name AS pve_name, r.status AS pve_status,
       r.data AS pve_data
FROM nodes n
LEFT JOIN clusters c ON c.id = n.cluster_id
LEFT JOIN agents a ON a.node_id = n.id AND a.revoked_at IS NULL
LEFT JOIN proxmox_connections pc ON pc.id = n.proxmox_id
LEFT JOIN proxmox_resources r ON r.connection_id = n.proxmox_id AND r.vmid = n.pve_vmid AND r.type IN ('qemu', 'lxc')
WHERE n.cluster_id = $1
ORDER BY lower(n.hostname)
`

type ListNodesByClusterRow struct {
	Node            Node
	ClusterSlug     *string
	ClusterName     *string
	AgentID         *uuid.UUID
	AgentVersion    *string
	AgentEnrolledAt *time.Time
	AgentLastSeenAt *time.Time
	AgentProtocol   *int32
	ProxmoxName     *string
	PveType         *string
	PveNode         *string
	PveName         *string
	PveStatus       *string
	PveData         []byte
}

func (q *Queries) ListNodesByCluster(ctx context.Context, clusterID *uuid.UUID) ([]ListNodesByClusterRow, error) {
	rows, err := q.db.Query(ctx, listNodesByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodesByClusterRow{}
	for rows.Next() {
		var i ListNodesByClusterRow
		if err := rows.Scan(
			&i.Node.ID,
			&i.Node.ClusterID,
			&i.Node.Hostname,
			&i.Node.Role,
			&i.Node.Description,
			&i.Node.Lifecycle,
			&i.Node.PrimaryIp,
			&i.Node.Tags,
			&i.Node.CreatedAt,
			&i.Node.UpdatedAt,
			&i.Node.Status,
			&i.Node.StatusReason,
			&i.Node.StatusSince,
			&i.Node.ProxmoxID,
			&i.Node.PveVmid,
			&i.ClusterSlug,
			&i.ClusterName,
			&i.AgentID,
			&i.AgentVersion,
			&i.AgentEnrolledAt,
			&i.AgentLastSeenAt,
			&i.AgentProtocol,
			&i.ProxmoxName,
			&i.PveType,
			&i.PveNode,
			&i.PveName,
			&i.PveStatus,
			&i.PveData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNode = `-- name: LockNode :one
SELECT id, cluster_id, hostname, role, description, lifecycle, primary_ip, tags, created_at, updated_at, status, status_reason, status_since, proxmox_id, pve_vmid FROM nodes WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockNode(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, lockNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Hostname,
		&i.Role,
		&i.Description,
		&i.Lifecycle,
		&i.PrimaryIp,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.StatusSince,
		&i.ProxmoxID,
		&i.PveVmid,
	)
	return i, err
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes
SET cluster_id = $2, hostname = $3, role = $4, description = $5, lifecycle = $6,
    primary_ip = $7, tags = $8, proxmox_id = $9, pve_vmid = $10, updated_at = now()
WHERE id = $1
RETURNING id, cluster_id, hostname, role, description, lifecycle, primary_ip, tags, created_at, updated_at, status, status_reason, status_since, proxmox_id, pve_vmid
`

type UpdateNodeParams struct {
	ID          uuid.UUID
	ClusterID   *uuid.UUID
	Hostname    string
	Role        string
	Description string
	Lifecycle   NodeLifecycle
	PrimaryIp   *netip.Addr
	Tags        []string
	ProxmoxID   *uuid.UUID
	PveVmid     *int32
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNode,
		arg.ID,
		arg.ClusterID,
		arg.Hostname,
		arg.Role,
		arg.Description,
		arg.Lifecycle,
		arg.PrimaryIp,
		arg.Tags,
		arg.ProxmoxID,
		arg.PveVmid,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Hostname,
		&i.Role,
		&i.Description,
		&i.Lifecycle,
		&i.PrimaryIp,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.StatusSince,
		&i.ProxmoxID,
		&i.PveVmid,
	)
	return i, err
}
