// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: nodes.sql

package store

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (cluster_id, hostname, role, description, lifecycle, primary_ip, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, cluster_id, hostname, role, description, lifecycle, primary_ip, tags, created_at, updated_at
`

type CreateNodeParams struct {
	ClusterID   *uuid.UUID
	Hostname    string
	Role        string
	Description string
	Lifecycle   NodeLifecycle
	PrimaryIp   *netip.Addr
	Tags        []string
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.ClusterID,
		arg.Hostname,
		arg.Role,
		arg.Description,
		arg.Lifecycle,
		arg.PrimaryIp,
		arg.Tags,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Hostname,
		&i.Role,
		&i.Description,
		&i.Lifecycle,
		&i.PrimaryIp,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :execrows
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNode = `-- name: GetNode :one
SELECT n.id, n.cluster_id, n.hostname, n.role, n.description, n.lifecycle, n.primary_ip, n.tags, n.created_at, n.updated_at, c.slug AS cluster_slug, c.name AS cluster_name
FROM nodes n LEFT JOIN clusters c ON c.id = n.cluster_id
WHERE n.id = $1
`

type GetNodeRow struct {
	Node        Node
	ClusterSlug *string
	ClusterName *string
}

func (q *Queries) GetNode(ctx context.Context, id uuid.UUID) (GetNodeRow, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i GetNodeRow
	err := row.Scan(
		&i.Node.ID,
		&i.Node.ClusterID,
		&i.Node.Hostname,
		&i.Node.Role,
		&i.Node.Description,
		&i.Node.Lifecycle,
		&i.Node.PrimaryIp,
		&i.Node.Tags,
		&i.Node.CreatedAt,
		&i.Node.UpdatedAt,
		&i.ClusterSlug,
		&i.ClusterName,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT n.id, n.cluster_id, n.hostname, n.role, n.description, n.lifecycle, n.primary_ip, n.tags, n.created_at, n.updated_at, c.slug AS cluster_slug, c.name AS cluster_name
FROM nodes n LEFT JOIN clusters c ON c.id = n.cluster_id
ORDER BY lower(n.hostname)
`

type ListNodesRow struct {
	Node        Node
	ClusterSlug *string
	ClusterName *string
}

func (q *Queries) ListNodes(ctx context.Context) ([]ListNodesRow, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodesRow{}
	for rows.Next() {
		var i ListNodesRow
		if err := rows.Scan(
			&i.Node.ID,
			&i.Node.ClusterID,
			&i.Node.Hostname,
			&i.Node.Role,
			&i.Node.Description,
			&i.Node.Lifecycle,
			&i.Node.PrimaryIp,
			&i.Node.Tags,
			&i.Node.CreatedAt,
			&i.Node.UpdatedAt,
			&i.ClusterSlug,
			&i.ClusterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByCluster = `-- name: ListNodesByCluster :many
SELECT id, cluster_id, hostname, role, description, lifecycle, primary_ip, tags, created_at, updated_at FROM nodes WHERE cluster_id = $1 ORDER BY lower(hostname)
`

func (q *Queries) ListNodesByCluster(ctx context.Context, clusterID *uuid.UUID) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodesByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.Hostname,
			&i.Role,
			&i.Description,
			&i.Lifecycle,
			&i.PrimaryIp,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNode = `-- name: LockNode :one
SELECT id, cluster_id, hostname, role, description, lifecycle, primary_ip, tags, created_at, updated_at FROM nodes WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockNode(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, lockNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Hostname,
		&i.Role,
		&i.Description,
		&i.Lifecycle,
		&i.PrimaryIp,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes
SET cluster_id = $2, hostname = $3, role = $4, description = $5, lifecycle = $6,
    primary_ip = $7, tags = $8, updated_at = now()
WHERE id = $1
RETURNING id, cluster_id, hostname, role, description, lifecycle, primary_ip, tags, created_at, updated_at
`

type UpdateNodeParams struct {
	ID          uuid.UUID
	ClusterID   *uuid.UUID
	Hostname    string
	Role        string
	Description string
	Lifecycle   NodeLifecycle
	PrimaryIp   *netip.Addr
	Tags        []string
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNode,
		arg.ID,
		arg.ClusterID,
		arg.Hostname,
		arg.Role,
		arg.Description,
		arg.Lifecycle,
		arg.PrimaryIp,
		arg.Tags,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Hostname,
		&i.Role,
		&i.Description,
		&i.Lifecycle,
		&i.PrimaryIp,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
