// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: proxmox.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countProxmoxResources = `-- name: CountProxmoxResources :many
SELECT connection_id, type, count(*)::integer AS count
FROM proxmox_resources
WHERE NOT template
GROUP BY connection_id, type
`

type CountProxmoxResourcesRow struct {
	ConnectionID uuid.UUID
	Type         string
	Count        int32
}

func (q *Queries) CountProxmoxResources(ctx context.Context) ([]CountProxmoxResourcesRow, error) {
	rows, err := q.db.Query(ctx, countProxmoxResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountProxmoxResourcesRow{}
	for rows.Next() {
		var i CountProxmoxResourcesRow
		if err := rows.Scan(&i.ConnectionID, &i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProxmoxConnection = `-- name: CreateProxmoxConnection :one
INSERT INTO proxmox_connections (id, name, api_url, token_id, token_secret_enc, key_id, tls_fingerprint, pve_version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, api_url, token_id, token_secret_enc, key_id, tls_fingerprint, pve_version, last_sync_at, last_error, created_at, updated_at
`

type CreateProxmoxConnectionParams struct {
	ID             uuid.UUID
	Name           string
	ApiUrl         string
	TokenID        string
	TokenSecretEnc []byte
	KeyID          string
	TlsFingerprint string
	PveVersion     string
}

func (q *Queries) CreateProxmoxConnection(ctx context.Context, arg CreateProxmoxConnectionParams) (ProxmoxConnection, error) {
	row := q.db.QueryRow(ctx, createProxmoxConnection,
		arg.ID,
		arg.Name,
		arg.ApiUrl,
		arg.TokenID,
		arg.TokenSecretEnc,
		arg.KeyID,
		arg.TlsFingerprint,
		arg.PveVersion,
	)
	var i ProxmoxConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiUrl,
		&i.TokenID,
		&i.TokenSecretEnc,
		&i.KeyID,
		&i.TlsFingerprint,
		&i.PveVersion,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProxmoxConnection = `-- name: DeleteProxmoxConnection :execrows
DELETE FROM proxmox_connections WHERE id = $1
`

func (q *Queries) DeleteProxmoxConnection(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProxmoxConnection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleProxmoxResources = `-- name: DeleteStaleProxmoxResources :exec
DELETE FROM proxmox_resources WHERE connection_id = $1 AND synced_at < $2
`

type DeleteStaleProxmoxResourcesParams struct {
	ConnectionID uuid.UUID
	SyncedAt     time.Time
}

func (q *Queries) DeleteStaleProxmoxResources(ctx context.Context, arg DeleteStaleProxmoxResourcesParams) error {
	_, err := q.db.Exec(ctx, deleteStaleProxmoxResources, arg.ConnectionID, arg.SyncedAt)
	return err
}

const getNodeByGuest = `-- name: GetNodeByGuest :one
SELECT id, hostname, cluster_id FROM nodes WHERE proxmox_id = $1 AND pve_vmid = $2
`

type GetNodeByGuestParams struct {
	ProxmoxID *uuid.UUID
	PveVmid   *int32
}

type GetNodeByGuestRow struct {
	ID        uuid.UUID
	Hostname  string
	ClusterID *uuid.UUID
}

func (q *Queries) GetNodeByGuest(ctx context.Context, arg GetNodeByGuestParams) (GetNodeByGuestRow, error) {
	row := q.db.QueryRow(ctx, getNodeByGuest, arg.ProxmoxID, arg.PveVmid)
	var i GetNodeByGuestRow
	err := row.Scan(&i.ID, &i.Hostname, &i.ClusterID)
	return i, err
}

const getProxmoxConnection = `-- name: GetProxmoxConnection :one
SELECT id, name, api_url, token_id, token_secret_enc, key_id, tls_fingerprint, pve_version, last_sync_at, last_error, created_at, updated_at FROM proxmox_connections WHERE id = $1
`

func (q *Queries) GetProxmoxConnection(ctx context.Context, id uuid.UUID) (ProxmoxConnection, error) {
	row := q.db.QueryRow(ctx, getProxmoxConnection, id)
	var i ProxmoxConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiUrl,
		&i.TokenID,
		&i.TokenSecretEnc,
		&i.KeyID,
		&i.TlsFingerprint,
		&i.PveVersion,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProxmoxGuest = `-- name: GetProxmoxGuest :one
SELECT connection_id, pve_id, type, pve_node, vmid, name, status, template, data, synced_at FROM proxmox_resources
WHERE connection_id = $1 AND vmid = $2 AND type IN ('qemu', 'lxc')
`

type GetProxmoxGuestParams struct {
	ConnectionID uuid.UUID
	Vmid         *int32
}

func (q *Queries) GetProxmoxGuest(ctx context.Context, arg GetProxmoxGuestParams) (ProxmoxResource, error) {
	row := q.db.QueryRow(ctx, getProxmoxGuest, arg.ConnectionID, arg.Vmid)
	var i ProxmoxResource
	err := row.Scan(
		&i.ConnectionID,
		&i.PveID,
		&i.Type,
		&i.PveNode,
		&i.Vmid,
		&i.Name,
		&i.Status,
		&i.Template,
		&i.Data,
		&i.SyncedAt,
	)
	return i, err
}

const listLinkedGuests = `-- name: ListLinkedGuests :many
SELECT n.id AS node_id, n.hostname, n.cluster_id, n.pve_vmid::integer AS vmid,
       r.status, r.pve_node
FROM nodes n
LEFT JOIN proxmox_resources r ON r.connection_id = n.proxmox_id AND r.vmid = n.pve_vmid AND r.type IN ('qemu', 'lxc')
WHERE n.proxmox_id = $1
`

type ListLinkedGuestsRow struct {
	NodeID    uuid.UUID
	Hostname  string
	ClusterID *uuid.UUID
	Vmid      int32
	Status    *string
	PveNode   *string
}

// Gekoppelde VM's van een omgeving met hun toestand van de vorige sync.
func (q *Queries) ListLinkedGuests(ctx context.Context, proxmoxID *uuid.UUID) ([]ListLinkedGuestsRow, error) {
	rows, err := q.db.Query(ctx, listLinkedGuests, proxmoxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinkedGuestsRow{}
	for rows.Next() {
		var i ListLinkedGuestsRow
		if err := rows.Scan(
			&i.NodeID,
			&i.Hostname,
			&i.ClusterID,
			&i.Vmid,
			&i.Status,
			&i.PveNode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxmoxConnections = `-- name: ListProxmoxConnections :many
SELECT id, name, api_url, token_id, token_secret_enc, key_id, tls_fingerprint, pve_version, last_sync_at, last_error, created_at, updated_at FROM proxmox_connections ORDER BY lower(name)
`

func (q *Queries) ListProxmoxConnections(ctx context.Context) ([]ProxmoxConnection, error) {
	rows, err := q.db.Query(ctx, listProxmoxConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxmoxConnection{}
	for rows.Next() {
		var i ProxmoxConnection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiUrl,
			&i.TokenID,
			&i.TokenSecretEnc,
			&i.KeyID,
			&i.TlsFingerprint,
			&i.PveVersion,
			&i.LastSyncAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxmoxResources = `-- name: ListProxmoxResources :many
SELECT r.connection_id, r.pve_id, r.type, r.pve_node, r.vmid, r.name, r.status, r.template, r.data, r.synced_at, n.id AS node_id, n.hostname AS node_hostname
FROM proxmox_resources r
LEFT JOIN nodes n ON n.proxmox_id = r.connection_id AND n.pve_vmid = r.vmid AND r.type IN ('qemu', 'lxc')
WHERE r.connection_id = $1
ORDER BY r.type, r.vmid NULLS FIRST, r.pve_node, r.name
`

type ListProxmoxResourcesRow struct {
	ProxmoxResource ProxmoxResource
	NodeID          *uuid.UUID
	NodeHostname    *string
}

func (q *Queries) ListProxmoxResources(ctx context.Context, connectionID uuid.UUID) ([]ListProxmoxResourcesRow, error) {
	rows, err := q.db.Query(ctx, listProxmoxResources, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProxmoxResourcesRow{}
	for rows.Next() {
		var i ListProxmoxResourcesRow
		if err := rows.Scan(
			&i.ProxmoxResource.ConnectionID,
			&i.ProxmoxResource.PveID,
			&i.ProxmoxResource.Type,
			&i.ProxmoxResource.PveNode,
			&i.ProxmoxResource.Vmid,
			&i.ProxmoxResource.Name,
			&i.ProxmoxResource.Status,
			&i.ProxmoxResource.Template,
			&i.ProxmoxResource.Data,
			&i.ProxmoxResource.SyncedAt,
			&i.NodeID,
			&i.NodeHostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProxmoxConnection = `-- name: LockProxmoxConnection :one
SELECT id, name, api_url, token_id, token_secret_enc, key_id, tls_fingerprint, pve_version, last_sync_at, last_error, created_at, updated_at FROM proxmox_connections WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockProxmoxConnection(ctx context.Context, id uuid.UUID) (ProxmoxConnection, error) {
	row := q.db.QueryRow(ctx, lockProxmoxConnection, id)
	var i ProxmoxConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiUrl,
		&i.TokenID,
		&i.TokenSecretEnc,
		&i.KeyID,
		&i.TlsFingerprint,
		&i.PveVersion,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setProxmoxSyncResult = `-- name: SetProxmoxSyncResult :exec
UPDATE proxmox_connections
SET last_sync_at = CASE WHEN $1::text = '' THEN now() ELSE last_sync_at END,
    last_error = $1::text,
    pve_version = CASE WHEN $2::text = '' THEN pve_version ELSE $2::text END
WHERE id = $3
`

type SetProxmoxSyncResultParams struct {
	Error      string
	PveVersion string
	ID         uuid.UUID
}

func (q *Queries) SetProxmoxSyncResult(ctx context.Context, arg SetProxmoxSyncResultParams) error {
	_, err := q.db.Exec(ctx, setProxmoxSyncResult, arg.Error, arg.PveVersion, arg.ID)
	return err
}

const unlinkProxmoxNodes = `-- name: UnlinkProxmoxNodes :exec
UPDATE nodes SET proxmox_id = NULL, pve_vmid = NULL, updated_at = now() WHERE proxmox_id = $1
`

func (q *Queries) UnlinkProxmoxNodes(ctx context.Context, proxmoxID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, unlinkProxmoxNodes, proxmoxID)
	return err
}

const updateProxmoxConnection = `-- name: UpdateProxmoxConnection :one
UPDATE proxmox_connections
SET name = $2, api_url = $3, token_id = $4, token_secret_enc = $5, key_id = $6, tls_fingerprint = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, name, api_url, token_id, token_secret_enc, key_id, tls_fingerprint, pve_version, last_sync_at, last_error, created_at, updated_at
`

type UpdateProxmoxConnectionParams struct {
	ID             uuid.UUID
	Name           string
	ApiUrl         string
	TokenID        string
	TokenSecretEnc []byte
	KeyID          string
	TlsFingerprint string
}

func (q *Queries) UpdateProxmoxConnection(ctx context.Context, arg UpdateProxmoxConnectionParams) (ProxmoxConnection, error) {
	row := q.db.QueryRow(ctx, updateProxmoxConnection,
		arg.ID,
		arg.Name,
		arg.ApiUrl,
		arg.TokenID,
		arg.TokenSecretEnc,
		arg.KeyID,
		arg.TlsFingerprint,
	)
	var i ProxmoxConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiUrl,
		&i.TokenID,
		&i.TokenSecretEnc,
		&i.KeyID,
		&i.TlsFingerprint,
		&i.PveVersion,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
