// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sandboxes.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getBackup = `-- name: GetBackup :one
SELECT connection_id, volid, storage, pve_node, vmid, guest_type, ctime, size_bytes, format, notes, protected, verify_state, synced_at FROM proxmox_backups WHERE connection_id = $1 AND volid = $2
`

type GetBackupParams struct {
	ConnectionID uuid.UUID
	Volid        string
}

func (q *Queries) GetBackup(ctx context.Context, arg GetBackupParams) (ProxmoxBackup, error) {
	row := q.db.QueryRow(ctx, getBackup, arg.ConnectionID, arg.Volid)
	var i ProxmoxBackup
	err := row.Scan(
		&i.ConnectionID,
		&i.Volid,
		&i.Storage,
		&i.PveNode,
		&i.Vmid,
		&i.GuestType,
		&i.Ctime,
		&i.SizeBytes,
		&i.Format,
		&i.Notes,
		&i.Protected,
		&i.VerifyState,
		&i.SyncedAt,
	)
	return i, err
}

const getBackupSandbox = `-- name: GetBackupSandbox :one
SELECT id, connection_id, vmid, source_vmid, source_node_id, run_id, volid, state, host, storage, error, created_at, destroyed_at FROM backup_sandboxes WHERE id = $1
`

func (q *Queries) GetBackupSandbox(ctx context.Context, id uuid.UUID) (BackupSandbox, error) {
	row := q.db.QueryRow(ctx, getBackupSandbox, id)
	var i BackupSandbox
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Vmid,
		&i.SourceVmid,
		&i.SourceNodeID,
		&i.RunID,
		&i.Volid,
		&i.State,
		&i.Host,
		&i.Storage,
		&i.Error,
		&i.CreatedAt,
		&i.DestroyedAt,
	)
	return i, err
}

const getLatestGuestBackup = `-- name: GetLatestGuestBackup :one
SELECT connection_id, volid, storage, pve_node, vmid, guest_type, ctime, size_bytes, format, notes, protected, verify_state, synced_at FROM proxmox_backups
WHERE connection_id = $1 AND vmid = $2
ORDER BY ctime DESC LIMIT 1
`

type GetLatestGuestBackupParams struct {
	ConnectionID uuid.UUID
	Vmid         int32
}

func (q *Queries) GetLatestGuestBackup(ctx context.Context, arg GetLatestGuestBackupParams) (ProxmoxBackup, error) {
	row := q.db.QueryRow(ctx, getLatestGuestBackup, arg.ConnectionID, arg.Vmid)
	var i ProxmoxBackup
	err := row.Scan(
		&i.ConnectionID,
		&i.Volid,
		&i.Storage,
		&i.PveNode,
		&i.Vmid,
		&i.GuestType,
		&i.Ctime,
		&i.SizeBytes,
		&i.Format,
		&i.Notes,
		&i.Protected,
		&i.VerifyState,
		&i.SyncedAt,
	)
	return i, err
}

const getRunSandbox = `-- name: GetRunSandbox :one
SELECT id, connection_id, vmid, source_vmid, source_node_id, run_id, volid, state, host, storage, error, created_at, destroyed_at FROM backup_sandboxes WHERE run_id = $1 ORDER BY created_at DESC LIMIT 1
`

// De sandbox van een run; een run heeft er hoogstens één.
func (q *Queries) GetRunSandbox(ctx context.Context, runID *uuid.UUID) (BackupSandbox, error) {
	row := q.db.QueryRow(ctx, getRunSandbox, runID)
	var i BackupSandbox
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Vmid,
		&i.SourceVmid,
		&i.SourceNodeID,
		&i.RunID,
		&i.Volid,
		&i.State,
		&i.Host,
		&i.Storage,
		&i.Error,
		&i.CreatedAt,
		&i.DestroyedAt,
	)
	return i, err
}

const getSandboxView = `-- name: GetSandboxView :one
SELECT b.id, b.connection_id, b.vmid, b.source_vmid, b.source_node_id, b.run_id, b.volid, b.state, b.host, b.storage, b.error, b.created_at, b.destroyed_at, r.result AS run_result, j.status AS job_status,
       c.name AS connection_name, n.hostname AS source_hostname
FROM backup_sandboxes b
JOIN proxmox_connections c ON c.id = b.connection_id
LEFT JOIN test_runs r ON r.id = b.run_id
LEFT JOIN jobs j ON j.id = r.job_id
LEFT JOIN nodes n ON n.id = b.source_node_id
WHERE b.id = $1
`

type GetSandboxViewRow struct {
	BackupSandbox  BackupSandbox
	RunResult      *string
	JobStatus      NullJobStatus
	ConnectionName string
	SourceHostname *string
}

// Eén sandbox met de namen erbij, voor de API.
func (q *Queries) GetSandboxView(ctx context.Context, id uuid.UUID) (GetSandboxViewRow, error) {
	row := q.db.QueryRow(ctx, getSandboxView, id)
	var i GetSandboxViewRow
	err := row.Scan(
		&i.BackupSandbox.ID,
		&i.BackupSandbox.ConnectionID,
		&i.BackupSandbox.Vmid,
		&i.BackupSandbox.SourceVmid,
		&i.BackupSandbox.SourceNodeID,
		&i.BackupSandbox.RunID,
		&i.BackupSandbox.Volid,
		&i.BackupSandbox.State,
		&i.BackupSandbox.Host,
		&i.BackupSandbox.Storage,
		&i.BackupSandbox.Error,
		&i.BackupSandbox.CreatedAt,
		&i.BackupSandbox.DestroyedAt,
		&i.RunResult,
		&i.JobStatus,
		&i.ConnectionName,
		&i.SourceHostname,
	)
	return i, err
}

const getVerifyNode = `-- name: GetVerifyNode :one
SELECT n.id, n.hostname, n.cluster_id, n.proxmox_id, n.pve_vmid, c.name AS connection_name,
       c.last_error, r.type AS guest_type, r.name AS guest_name
FROM nodes n
LEFT JOIN proxmox_connections c ON c.id = n.proxmox_id
LEFT JOIN proxmox_resources r ON r.connection_id = n.proxmox_id AND r.vmid = n.pve_vmid AND r.type IN ('qemu', 'lxc')
WHERE n.id = $1
`

type GetVerifyNodeRow struct {
	ID             uuid.UUID
	Hostname       string
	ClusterID      *uuid.UUID
	ProxmoxID      *uuid.UUID
	PveVmid        *int32
	ConnectionName *string
	LastError      *string
	GuestType      *string
	GuestName      *string
}

// Wat de back-upcontrole van een node nodig heeft.
func (q *Queries) GetVerifyNode(ctx context.Context, id uuid.UUID) (GetVerifyNodeRow, error) {
	row := q.db.QueryRow(ctx, getVerifyNode, id)
	var i GetVerifyNodeRow
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.ClusterID,
		&i.ProxmoxID,
		&i.PveVmid,
		&i.ConnectionName,
		&i.LastError,
		&i.GuestType,
		&i.GuestName,
	)
	return i, err
}

const insertBackupSandbox = `-- name: InsertBackupSandbox :one
INSERT INTO backup_sandboxes (connection_id, vmid, source_vmid, source_node_id, run_id, volid, host, storage)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, connection_id, vmid, source_vmid, source_node_id, run_id, volid, state, host, storage, error, created_at, destroyed_at
`

type InsertBackupSandboxParams struct {
	ConnectionID uuid.UUID
	Vmid         int32
	SourceVmid   int32
	SourceNodeID *uuid.UUID
	RunID        *uuid.UUID
	Volid        string
	Host         string
	Storage      string
}

// Reserveert een VMID in het register, vóór het terugzetten.
func (q *Queries) InsertBackupSandbox(ctx context.Context, arg InsertBackupSandboxParams) (BackupSandbox, error) {
	row := q.db.QueryRow(ctx, insertBackupSandbox,
		arg.ConnectionID,
		arg.Vmid,
		arg.SourceVmid,
		arg.SourceNodeID,
		arg.RunID,
		arg.Volid,
		arg.Host,
		arg.Storage,
	)
	var i BackupSandbox
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Vmid,
		&i.SourceVmid,
		&i.SourceNodeID,
		&i.RunID,
		&i.Volid,
		&i.State,
		&i.Host,
		&i.Storage,
		&i.Error,
		&i.CreatedAt,
		&i.DestroyedAt,
	)
	return i, err
}

const isSandboxGuest = `-- name: IsSandboxGuest :one
SELECT (
    EXISTS (
        SELECT 1 FROM backup_sandboxes b
        WHERE b.connection_id = $1 AND b.vmid = $2 AND b.state IN ('reserved', 'present', 'destroy_failed')
    ) OR EXISTS (
        SELECT 1 FROM proxmox_resources r
        WHERE r.connection_id = $1 AND r.vmid = $2 AND r.type IN ('qemu', 'lxc') AND r.data->>'pool' = 'cf-sandbox'
    )
)::boolean
`

type IsSandboxGuestParams struct {
	ConnectionID uuid.UUID
	Vmid         int32
}

// true als dit VMID nu als sandbox in het register staat, of bij de laatste
// sync in de pool cf-sandbox (proxmox.SandboxPool) zat.
func (q *Queries) IsSandboxGuest(ctx context.Context, arg IsSandboxGuestParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSandboxGuest, arg.ConnectionID, arg.Vmid)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const latestVerifications = `-- name: LatestVerifications :many
SELECT DISTINCT ON (r.node_id) r.node_id, r.id, r.result, r.summary, r.finished_at, r.measurements
FROM test_runs r
WHERE r.kind = 'backup.verify' AND r.node_id IS NOT NULL AND r.result IS NOT NULL
ORDER BY r.node_id, r.created_at DESC
`

type LatestVerificationsRow struct {
	NodeID       *uuid.UUID
	ID           uuid.UUID
	Result       *string
	Summary      string
	FinishedAt   *time.Time
	Measurements []byte
}

// De laatste afgeronde back-upcontrole per node.
func (q *Queries) LatestVerifications(ctx context.Context) ([]LatestVerificationsRow, error) {
	rows, err := q.db.Query(ctx, latestVerifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestVerificationsRow{}
	for rows.Next() {
		var i LatestVerificationsRow
		if err := rows.Scan(
			&i.NodeID,
			&i.ID,
			&i.Result,
			&i.Summary,
			&i.FinishedAt,
			&i.Measurements,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSandboxes = `-- name: ListLiveSandboxes :many
SELECT b.id, b.connection_id, b.vmid, b.source_vmid, b.source_node_id, b.run_id, b.volid, b.state, b.host, b.storage, b.error, b.created_at, b.destroyed_at, r.result AS run_result, j.status AS job_status,
       c.name AS connection_name, n.hostname AS source_hostname
FROM backup_sandboxes b
JOIN proxmox_connections c ON c.id = b.connection_id
LEFT JOIN test_runs r ON r.id = b.run_id
LEFT JOIN jobs j ON j.id = r.job_id
LEFT JOIN nodes n ON n.id = b.source_node_id
WHERE b.state IN ('reserved', 'present', 'destroy_failed')
ORDER BY b.created_at
`

type ListLiveSandboxesRow struct {
	BackupSandbox  BackupSandbox
	RunResult      *string
	JobStatus      NullJobStatus
	ConnectionName string
	SourceHostname *string
}

// Sandboxes die nog kunnen bestaan, met de stand van hun run en taak, voor
// de opruimer en de pagina Back-ups.
func (q *Queries) ListLiveSandboxes(ctx context.Context) ([]ListLiveSandboxesRow, error) {
	rows, err := q.db.Query(ctx, listLiveSandboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveSandboxesRow{}
	for rows.Next() {
		var i ListLiveSandboxesRow
		if err := rows.Scan(
			&i.BackupSandbox.ID,
			&i.BackupSandbox.ConnectionID,
			&i.BackupSandbox.Vmid,
			&i.BackupSandbox.SourceVmid,
			&i.BackupSandbox.SourceNodeID,
			&i.BackupSandbox.RunID,
			&i.BackupSandbox.Volid,
			&i.BackupSandbox.State,
			&i.BackupSandbox.Host,
			&i.BackupSandbox.Storage,
			&i.BackupSandbox.Error,
			&i.BackupSandbox.CreatedAt,
			&i.BackupSandbox.DestroyedAt,
			&i.RunResult,
			&i.JobStatus,
			&i.ConnectionName,
			&i.SourceHostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestRunsFiltered = `-- name: ListTestRunsFiltered :many
SELECT r.id, r.kind, r.trigger, r.cluster_id, r.test_id, r.node_id, r.hostname, r.job_id, r.definition, r.result, r.restored, r.summary, r.checks, r.timeline, r.measurements, r.requested_by, r.created_at, r.finished_at, j.status AS job_status, u.username AS requested_by_name, c.name AS cluster_name
FROM test_runs r
LEFT JOIN jobs j ON j.id = r.job_id
LEFT JOIN users u ON u.id = r.requested_by
LEFT JOIN clusters c ON c.id = r.cluster_id
WHERE ($1::text IS NULL OR r.kind = $1)
  AND ($2::uuid IS NULL OR r.cluster_id = $2)
  AND ($3::uuid IS NULL OR r.node_id = $3)
  AND ($4::text IS NULL OR r.result = $4)
ORDER BY r.created_at DESC
LIMIT $5
`

type ListTestRunsFilteredParams struct {
	Kind      *string
	ClusterID *uuid.UUID
	NodeID    *uuid.UUID
	Result    *string
	Lim       int32
}

type ListTestRunsFilteredRow struct {
	TestRun         TestRun
	JobStatus       NullJobStatus
	RequestedByName *string
	ClusterName     *string
}

// Runs met filters, nieuwste eerst.
func (q *Queries) ListTestRunsFiltered(ctx context.Context, arg ListTestRunsFilteredParams) ([]ListTestRunsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listTestRunsFiltered,
		arg.Kind,
		arg.ClusterID,
		arg.NodeID,
		arg.Result,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestRunsFilteredRow{}
	for rows.Next() {
		var i ListTestRunsFilteredRow
		if err := rows.Scan(
			&i.TestRun.ID,
			&i.TestRun.Kind,
			&i.TestRun.Trigger,
			&i.TestRun.ClusterID,
			&i.TestRun.TestID,
			&i.TestRun.NodeID,
			&i.TestRun.Hostname,
			&i.TestRun.JobID,
			&i.TestRun.Definition,
			&i.TestRun.Result,
			&i.TestRun.Restored,
			&i.TestRun.Summary,
			&i.TestRun.Checks,
			&i.TestRun.Timeline,
			&i.TestRun.Measurements,
			&i.TestRun.RequestedBy,
			&i.TestRun.CreatedAt,
			&i.TestRun.FinishedAt,
			&i.JobStatus,
			&i.RequestedByName,
			&i.ClusterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sandboxActiveForNode = `-- name: SandboxActiveForNode :one
SELECT EXISTS (
    SELECT 1 FROM backup_sandboxes
    WHERE source_node_id = $1 AND state IN ('reserved', 'present', 'destroy_failed')
)::boolean
`

// true zolang er een sandbox van de VM van deze node kan bestaan.
func (q *Queries) SandboxActiveForNode(ctx context.Context, nodeID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, sandboxActiveForNode, nodeID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setBackupSandboxState = `-- name: SetBackupSandboxState :one
UPDATE backup_sandboxes
SET state = $1, error = $2,
    destroyed_at = CASE WHEN $1 IN ('destroyed', 'none') THEN now() ELSE destroyed_at END
WHERE id = $3
RETURNING id, connection_id, vmid, source_vmid, source_node_id, run_id, volid, state, host, storage, error, created_at, destroyed_at
`

type SetBackupSandboxStateParams struct {
	State string
	Error string
	ID    uuid.UUID
}

func (q *Queries) SetBackupSandboxState(ctx context.Context, arg SetBackupSandboxStateParams) (BackupSandbox, error) {
	row := q.db.QueryRow(ctx, setBackupSandboxState, arg.State, arg.Error, arg.ID)
	var i BackupSandbox
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Vmid,
		&i.SourceVmid,
		&i.SourceNodeID,
		&i.RunID,
		&i.Volid,
		&i.State,
		&i.Host,
		&i.Storage,
		&i.Error,
		&i.CreatedAt,
		&i.DestroyedAt,
	)
	return i, err
}
