// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, csrf_token, ip, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	ID        []byte
	UserID    uuid.UUID
	CsrfToken string
	Ip        string
	UserAgent string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CsrfToken,
		arg.Ip,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUserSessionsExcept = `-- name: DeleteUserSessionsExcept :exec
DELETE FROM sessions WHERE user_id = $1 AND id <> $2
`

type DeleteUserSessionsExceptParams struct {
	UserID uuid.UUID
	ID     []byte
}

func (q *Queries) DeleteUserSessionsExcept(ctx context.Context, arg DeleteUserSessionsExceptParams) error {
	_, err := q.db.Exec(ctx, deleteUserSessionsExcept, arg.UserID, arg.ID)
	return err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT sessions.id, sessions.user_id, sessions.csrf_token, sessions.ip, sessions.user_agent, sessions.created_at, sessions.last_seen_at, sessions.expires_at, users.id, users.username, users.password_hash, users.role, users.totp_secret, users.totp_enabled_at, users.totp_last_step, users.disabled_at, users.created_at, users.updated_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.id = $1
  AND sessions.expires_at > now()
  AND users.disabled_at IS NULL
`

type GetSessionWithUserRow struct {
	Session Session
	User    User
}

func (q *Queries) GetSessionWithUser(ctx context.Context, id []byte) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, id)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.CsrfToken,
		&i.Session.Ip,
		&i.Session.UserAgent,
		&i.Session.CreatedAt,
		&i.Session.LastSeenAt,
		&i.Session.ExpiresAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.PasswordHash,
		&i.User.Role,
		&i.User.TotpSecret,
		&i.User.TotpEnabledAt,
		&i.User.TotpLastStep,
		&i.User.DisabledAt,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now(), expires_at = $2 WHERE id = $1
`

type TouchSessionParams struct {
	ID        []byte
	ExpiresAt time.Time
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}
