// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: status.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const getMetricLabels = `-- name: GetMetricLabels :one
SELECT n.hostname, n.cluster_id, coalesce(c.slug, '')::text AS cluster, coalesce(c.environment::text, '')::text AS environment
FROM nodes n LEFT JOIN clusters c ON c.id = n.cluster_id
WHERE n.id = $1
`

type GetMetricLabelsRow struct {
	Hostname    string
	ClusterID   *uuid.UUID
	Cluster     string
	Environment string
}

// Labels die de server aan de metrics van een node hangt.
func (q *Queries) GetMetricLabels(ctx context.Context, id uuid.UUID) (GetMetricLabelsRow, error) {
	row := q.db.QueryRow(ctx, getMetricLabels, id)
	var i GetMetricLabelsRow
	err := row.Scan(
		&i.Hostname,
		&i.ClusterID,
		&i.Cluster,
		&i.Environment,
	)
	return i, err
}

const listAllVIPs = `-- name: ListAllVIPs :many
SELECT id, cluster_id, address, owner_node_id FROM vips
`

type ListAllVIPsRow struct {
	ID          uuid.UUID
	ClusterID   uuid.UUID
	Address     netip.Addr
	OwnerNodeID *uuid.UUID
}

func (q *Queries) ListAllVIPs(ctx context.Context) ([]ListAllVIPsRow, error) {
	rows, err := q.db.Query(ctx, listAllVIPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllVIPsRow{}
	for rows.Next() {
		var i ListAllVIPsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.Address,
			&i.OwnerNodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusterStatuses = `-- name: ListClusterStatuses :many
SELECT id, status, status_reason FROM clusters
`

type ListClusterStatusesRow struct {
	ID           uuid.UUID
	Status       string
	StatusReason string
}

func (q *Queries) ListClusterStatuses(ctx context.Context) ([]ListClusterStatusesRow, error) {
	rows, err := q.db.Query(ctx, listClusterStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClusterStatusesRow{}
	for rows.Next() {
		var i ListClusterStatusesRow
		if err := rows.Scan(&i.ID, &i.Status, &i.StatusReason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeStatusInputs = `-- name: ListNodeStatusInputs :many
SELECT n.id, n.hostname, n.cluster_id, n.lifecycle, n.status, n.status_reason,
       (a.id IS NOT NULL)::boolean AS has_agent,
       s.heartbeat_at,
       coalesce(s.addresses, '{}')::text[] AS addresses,
       coalesce(s.services, '{}'::jsonb)::jsonb AS services,
       coalesce(s.disk_used_ratio, 0)::float8 AS disk_used_ratio,
       coalesce(s.disk_used_mount, '')::text AS disk_used_mount,
       coalesce(jsonb_path_query_array(f.facts, '$.services[*] ? (@.enabled == "enabled").name'), '[]'::jsonb)::jsonb AS enabled_services
FROM nodes n
LEFT JOIN agents a ON a.node_id = n.id AND a.revoked_at IS NULL
LEFT JOIN node_status s ON s.node_id = n.id
LEFT JOIN node_facts f ON f.node_id = n.id
`

type ListNodeStatusInputsRow struct {
	ID              uuid.UUID
	Hostname        string
	ClusterID       *uuid.UUID
	Lifecycle       NodeLifecycle
	Status          string
	StatusReason    string
	HasAgent        bool
	HeartbeatAt     *time.Time
	Addresses       []string
	Services        []byte
	DiskUsedRatio   float64
	DiskUsedMount   string
	EnabledServices []byte
}

// Alles wat de statusregels per node nodig hebben.
func (q *Queries) ListNodeStatusInputs(ctx context.Context) ([]ListNodeStatusInputsRow, error) {
	rows, err := q.db.Query(ctx, listNodeStatusInputs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeStatusInputsRow{}
	for rows.Next() {
		var i ListNodeStatusInputsRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.ClusterID,
			&i.Lifecycle,
			&i.Status,
			&i.StatusReason,
			&i.HasAgent,
			&i.HeartbeatAt,
			&i.Addresses,
			&i.Services,
			&i.DiskUsedRatio,
			&i.DiskUsedMount,
			&i.EnabledServices,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setClusterStatus = `-- name: SetClusterStatus :exec
UPDATE clusters
SET status = $1, status_reason = $2,
    status_since = CASE WHEN status = $1 THEN status_since ELSE now() END
WHERE id = $3
`

type SetClusterStatusParams struct {
	Status       string
	StatusReason string
	ID           uuid.UUID
}

func (q *Queries) SetClusterStatus(ctx context.Context, arg SetClusterStatusParams) error {
	_, err := q.db.Exec(ctx, setClusterStatus, arg.Status, arg.StatusReason, arg.ID)
	return err
}

const setNodeDiskUsage = `-- name: SetNodeDiskUsage :exec
UPDATE node_status SET disk_used_ratio = $2, disk_used_mount = $3 WHERE node_id = $1
`

type SetNodeDiskUsageParams struct {
	NodeID        uuid.UUID
	DiskUsedRatio float64
	DiskUsedMount string
}

func (q *Queries) SetNodeDiskUsage(ctx context.Context, arg SetNodeDiskUsageParams) error {
	_, err := q.db.Exec(ctx, setNodeDiskUsage, arg.NodeID, arg.DiskUsedRatio, arg.DiskUsedMount)
	return err
}

const setNodeStatus = `-- name: SetNodeStatus :exec
UPDATE nodes
SET status = $1, status_reason = $2,
    status_since = CASE WHEN status = $1 THEN status_since ELSE now() END
WHERE id = $3
`

type SetNodeStatusParams struct {
	Status       string
	StatusReason string
	ID           uuid.UUID
}

func (q *Queries) SetNodeStatus(ctx context.Context, arg SetNodeStatusParams) error {
	_, err := q.db.Exec(ctx, setNodeStatus, arg.Status, arg.StatusReason, arg.ID)
	return err
}
