// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, username, password_hash, role, totp_secret, totp_enabled_at, totp_last_step, disabled_at, created_at, updated_at
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
	Role         UserRole
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE users SET totp_secret = NULL, totp_enabled_at = NULL, totp_last_step = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) DisableTOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableTOTP, id)
	return err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE users SET totp_enabled_at = now(), updated_at = now() WHERE id = $1 AND totp_secret IS NOT NULL
`

func (q *Queries) EnableTOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, enableTOTP, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role, totp_secret, totp_enabled_at, totp_last_step, disabled_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, totp_secret, totp_enabled_at, totp_last_step, disabled_at, created_at, updated_at FROM users WHERE lower(username) = lower($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPendingTOTPSecret = `-- name: SetPendingTOTPSecret :exec
UPDATE users SET totp_secret = $2, totp_enabled_at = NULL, totp_last_step = NULL, updated_at = now() WHERE id = $1
`

type SetPendingTOTPSecretParams struct {
	ID         uuid.UUID
	TotpSecret *string
}

func (q *Queries) SetPendingTOTPSecret(ctx context.Context, arg SetPendingTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, setPendingTOTPSecret, arg.ID, arg.TotpSecret)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const useTOTPStep = `-- name: UseTOTPStep :execrows
UPDATE users SET totp_last_step = $2
WHERE id = $1 AND (totp_last_step IS NULL OR totp_last_step < $2)
`

type UseTOTPStepParams struct {
	ID           uuid.UUID
	TotpLastStep *int64
}

// Legt de gebruikte TOTP-periode vast; 0 rijen betekent dat de code (of een
// latere) al gebruikt is.
func (q *Queries) UseTOTPStep(ctx context.Context, arg UseTOTPStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, useTOTPStep, arg.ID, arg.TotpLastStep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
