// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vips.sql

package store

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const createVIP = `-- name: CreateVIP :one
INSERT INTO vips (cluster_id, address, interface, vrid, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, cluster_id, address, interface, vrid, description, owner_node_id, owner_since, created_at, updated_at
`

type CreateVIPParams struct {
	ClusterID   uuid.UUID
	Address     netip.Addr
	Interface   string
	Vrid        *int32
	Description string
}

func (q *Queries) CreateVIP(ctx context.Context, arg CreateVIPParams) (Vip, error) {
	row := q.db.QueryRow(ctx, createVIP,
		arg.ClusterID,
		arg.Address,
		arg.Interface,
		arg.Vrid,
		arg.Description,
	)
	var i Vip
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Address,
		&i.Interface,
		&i.Vrid,
		&i.Description,
		&i.OwnerNodeID,
		&i.OwnerSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVIP = `-- name: DeleteVIP :execrows
DELETE FROM vips WHERE id = $1
`

func (q *Queries) DeleteVIP(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVIP, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVIP = `-- name: GetVIP :one
SELECT id, cluster_id, address, interface, vrid, description, owner_node_id, owner_since, created_at, updated_at FROM vips WHERE id = $1
`

func (q *Queries) GetVIP(ctx context.Context, id uuid.UUID) (Vip, error) {
	row := q.db.QueryRow(ctx, getVIP, id)
	var i Vip
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Address,
		&i.Interface,
		&i.Vrid,
		&i.Description,
		&i.OwnerNodeID,
		&i.OwnerSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVIPsByCluster = `-- name: ListVIPsByCluster :many
SELECT v.id, v.cluster_id, v.address, v.interface, v.vrid, v.description, v.owner_node_id, v.owner_since, v.created_at, v.updated_at, n.hostname AS owner_hostname
FROM vips v LEFT JOIN nodes n ON n.id = v.owner_node_id
WHERE v.cluster_id = $1
ORDER BY v.address
`

type ListVIPsByClusterRow struct {
	Vip           Vip
	OwnerHostname *string
}

func (q *Queries) ListVIPsByCluster(ctx context.Context, clusterID uuid.UUID) ([]ListVIPsByClusterRow, error) {
	rows, err := q.db.Query(ctx, listVIPsByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVIPsByClusterRow{}
	for rows.Next() {
		var i ListVIPsByClusterRow
		if err := rows.Scan(
			&i.Vip.ID,
			&i.Vip.ClusterID,
			&i.Vip.Address,
			&i.Vip.Interface,
			&i.Vip.Vrid,
			&i.Vip.Description,
			&i.Vip.OwnerNodeID,
			&i.Vip.OwnerSince,
			&i.Vip.CreatedAt,
			&i.Vip.UpdatedAt,
			&i.OwnerHostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockVIP = `-- name: LockVIP :one
SELECT id, cluster_id, address, interface, vrid, description, owner_node_id, owner_since, created_at, updated_at FROM vips WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockVIP(ctx context.Context, id uuid.UUID) (Vip, error) {
	row := q.db.QueryRow(ctx, lockVIP, id)
	var i Vip
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Address,
		&i.Interface,
		&i.Vrid,
		&i.Description,
		&i.OwnerNodeID,
		&i.OwnerSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVIP = `-- name: UpdateVIP :one
UPDATE vips
SET address = $2, interface = $3, vrid = $4, description = $5, updated_at = now()
WHERE id = $1
RETURNING id, cluster_id, address, interface, vrid, description, owner_node_id, owner_since, created_at, updated_at
`

type UpdateVIPParams struct {
	ID          uuid.UUID
	Address     netip.Addr
	Interface   string
	Vrid        *int32
	Description string
}

func (q *Queries) UpdateVIP(ctx context.Context, arg UpdateVIPParams) (Vip, error) {
	row := q.db.QueryRow(ctx, updateVIP,
		arg.ID,
		arg.Address,
		arg.Interface,
		arg.Vrid,
		arg.Description,
	)
	var i Vip
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Address,
		&i.Interface,
		&i.Vrid,
		&i.Description,
		&i.OwnerNodeID,
		&i.OwnerSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
